import { AlertTriangle, CheckCircle2, Copy, Download, FileJson, FolderOpen, Plus, Save, Trash2, Upload } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react'
import { useAcademyLocalState } from '../academy/useAcademyLocalState'
import {
  ACADEMY_STAGE_5_ASSEMBLY_PLAN,
  ACADEMY_STAGE_5_CHAIN_TEMPLATES,
  ACADEMY_STAGE_5_DOSSIER_SECTIONS,
  ACADEMY_STAGE_5_INTERFACE_SEEDS,
  ACADEMY_STAGE_5_METHOD_SELF_REVIEW,
  ACADEMY_STAGE_5_VISUAL_QUESTION_COVERAGE,
  buildIntegrationDossier,
  createIntegrationProject,
  duplicateIntegrationProject,
  exportIntegrationProject,
  importIntegrationProject,
  type IntegrationProjectStatus,
  type WatchIntegrationProject,
} from '../academy/reader/personal/phase014k'
import { useLearning } from './LearningContext'
import './academy-integration-lab.css'

const panels = [
  ['overview','Proyecto'],['requirements','Requisitos'],['movement','Movimiento'],['inventory','Inventario'],['authority','Documentos'],
  ['matrix','Matriz'],['chains','Cadenas'],['interferences','Interferencias'],['donors','Donantes'],['assembly','Montaje'],['dossier','Dossier'],['review','Revisión'],
] as const

function fixtureProject(profileId:string,status:IntegrationProjectStatus):WatchIntegrationProject{
  const project=createIntegrationProject(profileId,'2026-08-16T12:00:00.000Z','fixture.qa.stage5.integration')
  project.title='FIXTURE QA · proyecto documental sin datos privados'
  project.requirements=[{requirementId:'requirement.fixture.use',category:'use',statement:'Reloj cotidiano conceptual para probar el método.',metric:'Pendiente de convertir a criterio verificable',priority:'must',verificationMethod:'revisión documental',status:'draft'}]
  project.documents=[{documentId:'document.fixture.movement',componentIds:['component.movement'],title:'Drawing oficial de ejemplo · snapshot 0.14J',authority:'manufacturer-drawing',sourceId:'source.miyota.8215.drawing',locator:'snapshot local verificado; sin binario en runtime',applicableReference:'MIYOTA 8215 como ejemplo',verificationStatus:'verified',notes:'No se generaliza.'}]
  project.unknowns=['altura interior del cristal del componente elegido','fit aplicable de agujas','sección y alojamiento de juntas']
  project.status=status
  if(status==='conflict-found')project.conflicts=['La altura de eje declarada por dos documentos del fixture no coincide.']
  if(status==='documentally-compatible')project.unknowns=[]
  return project
}

function downloadJson(project:WatchIntegrationProject){const blob=new Blob([exportIntegrationProject(project)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${project.projectId.replaceAll(/[^a-z0-9.-]/gi,'-')}.json`;anchor.hidden=true;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
const statusLabel:Record<IntegrationProjectStatus,string>={draft:'Borrador','source-needed':'Necesita fuente','measurement-needed':'Necesita medición','conflict-found':'Conflicto encontrado','documentally-compatible':'Compatible documentalmente','physical-validation-pending':'Validación física pendiente',rejected:'Rechazado'}
const componentLabels:Record<string,string>={movement:'Movimiento',case:'Caja','movement-holder':'Aro del movimiento',stem:'Tija',crown:'Corona',tube:'Tubo',dial:'Esfera','hand-hour':'Aguja de horas','hand-minute':'Aguja de minutos','hand-second':'Aguja de segundos',crystal:'Cristal',bezel:'Bisel',rehaut:'Rehaut',caseback:'Fondo',gasket:'Junta','donor-part':'Pieza donante',other:'Receptor'}
const componentLabel=(value:string)=>componentLabels[value.replace('component.','')]??'Componente'
const lessonByPanel:Record<string,string>={requirements:'lesson.capstone.design.requirements',movement:'lesson.capstone.design.acquired-movement',inventory:'lesson.capstone.validation.calibre-transfer',authority:'lesson.capstone.design.acquired-movement',matrix:'lesson.capstone.design.capstone',chains:'lesson.encyclopedia.cases-water.toh-exterior-interfaces',interferences:'lesson.encyclopedia.cases-water.toh-materiales-exterior',donors:'lesson.encyclopedia.atlas-restoration-design.restauracion-y-fabricacion-de-repuesto',assembly:'lesson.mechanical.final-project',dossier:'lesson.capstone.design.capstone',review:'lesson.capstone.validation.calibre-transfer',overview:'lesson.capstone.design.requirements'}

export default function AcademyIntegrationLabSurface(){
  const {snapshot}=useLearning();const profileId=snapshot.profile?.id??'profile.local-default';const {state,actions}=useAcademyLocalState(profileId,snapshot.profile?.educationalPreferences.academyStateV1)
  const fixture=snapshot.location.query['qa-fixture']==='1';const fixtureSubject=fixture?snapshot.location.query['qa-subject']:undefined;const invalidImportFixture=fixture&&snapshot.location.query['invalid-import']==='1';const fallbackFixture=fixture&&snapshot.location.query.fallback==='1';const darkFixture=fixture&&snapshot.location.query.theme==='dark';const reducedMotionFixture=fixture&&snapshot.location.query.motion==='reduced';const reflowFixture=fixture&&snapshot.location.query.reflow==='200';const requestedStatus=(snapshot.location.query.status??'source-needed') as IntegrationProjectStatus
  const qaProject=useMemo(()=>fixtureProject(profileId,Object.keys(statusLabel).includes(requestedStatus)?requestedStatus:'source-needed'),[profileId,requestedStatus])
  const stored=state?.integrationProjects.find(({projectId})=>projectId===state.activeIntegrationProjectId)??state?.integrationProjects[0]
  const base=fixture?qaProject:stored??createIntegrationProject(profileId)
  const [editableDraft,setDraft]=useState(base);const draft=fixture?qaProject:editableDraft;const [message,setMessage]=useState('');const [error,setError]=useState('');const visibleMessage=fixture?(message||'Fixture QA etiquetado: no se guarda ni contiene datos personales.'):message;const visibleError=fixture?(invalidImportFixture?'Fixture QA · importación rechazada: JSON inválido; los datos siguen intactos.':''):error
  const autosaveFingerprint=useRef(JSON.stringify({...base,revision:0,updatedAt:''}))
  const fileInput=useRef<HTMLInputElement>(null);const panel=snapshot.location.query.panel??'overview';const dossier=buildIntegrationDossier(draft)
  const save=()=>{if(fixture){setMessage('Fixture QA: guardado desactivado para no crear perfiles o proyectos de prueba.');return}try{const saved=actions.saveIntegrationProject(draft,stored?.projectId===draft.projectId?stored.revision:undefined);setDraft(saved);setMessage('Proyecto guardado localmente y preparado para la copia durable del perfil.');setError('')}catch(cause){if(cause instanceof Error&&cause.message==='integration-project-version-conflict'){const preserved=duplicateIntegrationProject(draft,new Date().toISOString(),`${draft.projectId}.conflict.${draft.revision}`);const saved=actions.saveIntegrationProject(preserved);setDraft(saved);setError('Se detectó un conflicto de versión. Se conservó esta edición como copia en conflicto; no se perdió ningún dato.')}else setError('No se pudo guardar. La edición permanece abierta en memoria.')}}
  const create=()=>{if(fixture){setMessage('Fixture QA: creación desactivada.');return}const project=createIntegrationProject(profileId);setDraft(project);actions.setActiveIntegrationProject(undefined);setMessage('Proyecto vacío creado en memoria. Pulsa Guardar para conservarlo.');setError('')}
  const duplicate=()=>{const copy=duplicateIntegrationProject(draft,new Date().toISOString(),`integration.${crypto.randomUUID()}`);setDraft(copy);if(!fixture)actions.saveIntegrationProject(copy);setMessage('Copia independiente creada; conserva las fuentes y unknowns.');setError('')}
  const remove=()=>{if(fixture){setMessage('Fixture QA: eliminación desactivada.');return}if(!window.confirm('¿Eliminar explícitamente este proyecto local? Esta acción no modifica progreso ni otros proyectos.'))return;actions.deleteIntegrationProject(draft.projectId);const next=state?.integrationProjects.find(({projectId})=>projectId!==draft.projectId)??createIntegrationProject(profileId);setDraft(next);setMessage('Proyecto eliminado del perfil local.');setError('')}
  const importFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;const result=importIntegrationProject(await file.text(),profileId);if(!result.ok){setError(result.errors.join(' '));return}const saved=actions.saveIntegrationProject(result.project);setDraft(saved);setMessage(`Proyecto importado y validado. ${result.warnings.join(' ')}`);setError('')}
  const setTitle=(title:string)=>setDraft((current)=>({...current,title,updatedAt:new Date().toISOString()}))
  useEffect(()=>{if(fixture)return;const fingerprint=JSON.stringify({...draft,revision:0,updatedAt:''});if(fingerprint===autosaveFingerprint.current)return;const timeout=window.setTimeout(()=>{try{const saved=actions.saveIntegrationProject(draft,stored?.projectId===draft.projectId?stored.revision:undefined);autosaveFingerprint.current=JSON.stringify({...saved,revision:0,updatedAt:''});setDraft(saved);setMessage('Guardado automático local completado.')}catch{setError('El guardado automático detectó otra versión. Esta edición sigue abierta; usa Guardar para conservar una copia en conflicto.')}},700);return()=>window.clearTimeout(timeout)},[actions,draft,fixture,stored?.projectId,stored?.revision])
  return <div className="academy-integration-lab" data-qa-fixture={fixture?'stage5-integration':undefined} data-qa-theme={darkFixture?'dark':undefined} data-qa-motion={reducedMotionFixture?'reduced':undefined} data-qa-reflow={reflowFixture?'200':undefined}>
    <header className="academy-integration-hero"><div><span>LABORATORIO LOCAL · ETAPA 5</span><h1>Integrar un reloj alrededor de un movimiento adquirido</h1><p>Método documental, dimensional y reversible. No ejecuta montaje ni acredita compatibilidad física.</p></div><a href="#/learning/my-learning?stage=stage.5">Volver a la etapa 5</a></header>
    {fixture&&<aside className="integration-fixture"><FileJson size={18}/><strong>FIXTURE QA{fixtureSubject?` · ${fixtureSubject}`:''}</strong><span>Datos sintéticos, sin documentos privados, notas reales ni validación humana simulada.</span></aside>}
    {fallbackFixture&&<aside className="integration-fixture"><AlertTriangle size={18}/><strong>FALLBACK SIN WEBGL</strong><span>Las cadenas, datums, márgenes, estados omitidos y límites siguen disponibles como texto semántico.</span></aside>}
    {reducedMotionFixture&&<aside className="integration-fixture"><CheckCircle2 size={18}/><strong>MOVIMIENTO REDUCIDO</strong><span>Las transiciones y animaciones quedan desactivadas; no se pierde información.</span></aside>}
    <div className="integration-project-bar"><label>Título del proyecto<input value={draft.title} onChange={(event)=>setTitle(event.target.value)} maxLength={200}/></label><div className="integration-actions"><button onClick={create}><Plus size={16}/>Nuevo</button><button onClick={save}><Save size={16}/>Guardar</button><button onClick={duplicate}><Copy size={16}/>Duplicar</button><button onClick={()=>downloadJson(draft)}><Download size={16}/>Exportar JSON</button><button onClick={()=>fileInput.current?.click()}><Upload size={16}/>Importar</button><input ref={fileInput} hidden type="file" accept="application/json,.json" onChange={importFile}/><button className="is-danger" onClick={remove}><Trash2 size={16}/>Eliminar</button></div></div>
    <div className="integration-status-line"><span className={`integration-status status-${draft.status}`}>{draft.status==='conflict-found'?<AlertTriangle size={16}/>:<CheckCircle2 size={16}/>} {statusLabel[draft.status]}</span><span>Currículo: <strong>método completo</strong></span><span>Proyecto: <strong>{statusLabel[draft.status]}</strong></span><span>Revisión física: <strong>pendiente</strong></span></div>
    {visibleMessage&&<p className="integration-message" role="status">{visibleMessage}</p>}{visibleError&&<p className="integration-error" role="alert">{visibleError}</p>}
    <nav className="integration-tabs" aria-label="Apartados del proyecto">{panels.map(([id,label])=><a key={id} className={panel===id?'is-active':undefined} href={`#/learning/workshop?integration=1&panel=${id}${fixture?'&qa-fixture=1':''}`}>{label}</a>)}</nav>
    <main className="integration-panel">
      {panel==='overview'&&<><h2>Proyecto vacío, método disponible</h2><div className="integration-callout"><strong>No falta contenido curricular.</strong><span>Faltan los datos aplicables del conjunto que elijas. Unknown no significa cero.</span></div><div className="integration-summary-grid"><article><span>Componentes</span><strong>{draft.components.length}</strong><small>categorías preinventariadas</small></article><article><span>Interfaces</span><strong>{ACADEMY_STAGE_5_INTERFACE_SEEDS.length}</strong><small>ninguna se cierra por parecido</small></article><article><span>Cadenas</span><strong>{ACADEMY_STAGE_5_CHAIN_TEMPLATES.length}</strong><small>radial, mando, esfera, axial y posterior</small></article><article><span>Unknowns</span><strong>{draft.unknowns.length}</strong><small>conservados en el dossier</small></article></div><h3>Qué puede concluir 0.14K</h3><p>Compatible en papel, condicional, incompatible o pendiente. Nunca “reloj montado” ni “hermético” sin evidencia física aplicable.</p></>}
      {panel==='requirements'&&<><h2>Requisitos antes de componentes</h2><p>Un deseo solo se vuelve requisito técnico cuando declara métrica o método de verificación. Uso, tamaño, indicaciones, entorno, coste, mantenimiento, reversibilidad y donantes se revisan por separado.</p><table><thead><tr><th>Requisito</th><th>Métrica</th><th>Prioridad</th><th>Estado</th></tr></thead><tbody>{draft.requirements.length?draft.requirements.map((row)=><tr key={row.requirementId}><td>{row.statement}</td><td>{row.metric??'unknown'}</td><td>{row.priority}</td><td>{row.status}</td></tr>):<tr><td colSpan={4}>Aún no hay requisitos. Añadirlos no exige comprar piezas.</td></tr>}</tbody></table></>}
      {panel==='movement'&&<><h2>Elección documentada del movimiento</h2><p>Compara funciones, drawing, altura, tija, soportes, esfera, agujas, repuestos y mantenibilidad. MIYOTA 8215 es ejemplo verificado, no la única opción.</p><div className="integration-flow"><span>Pliego</span><span>→</span><span>Candidatos</span><span>→</span><span>Documentación</span><span>→</span><span>Elección limitada</span></div></>}
      {panel==='inventory'&&<><h2>Inventario del reloj completo</h2><div className="integration-component-grid">{draft.components.map((component)=><article key={component.componentId}><strong>{componentLabel(component.category)}</strong><span>{component.reference||'Referencia desconocida'}</span><small>{component.sourceType} · {component.modificationStatus}</small></article>)}</div></>}
      {panel==='authority'&&<><h2>Autoridad documental por componente</h2><p>Fabricante y drawing prevalecen para el movimiento; proveedor concreto, medición trazable y derivados limitados para el resto. Visual-match-only nunca valida.</p>{draft.documents.length?<table><thead><tr><th>Documento</th><th>Autoridad</th><th>Aplicabilidad</th><th>Estado</th></tr></thead><tbody>{draft.documents.map((doc)=><tr key={doc.documentId}><td>{doc.title}</td><td>{doc.authority}</td><td>{doc.applicableReference??'unknown'}</td><td>{doc.verificationStatus}</td></tr>)}</tbody></table>:<div className="integration-callout"><FolderOpen/><strong>Método disponible · necesita documentación del componente elegido</strong></div>}</>}
      {panel==='matrix'&&<><h2>Matriz de compatibilidad</h2><p>Una combinación solo puede declararse documentally-compatible cuando todas las interfaces críticas disponen de datos aplicables y no presentan conflictos documentales.</p><table><thead><tr><th>Interfaz</th><th>Pregunta</th><th>Datos requeridos</th><th>Resultado</th></tr></thead><tbody>{draft.compatibilityChecks.map((row)=><tr key={row.interfaceId}><td>{componentLabel(row.componentA)} ↔ {componentLabel(row.componentB)}</td><td>{row.question}</td><td>{row.requiredData.map((value)=>value.replaceAll('-',' ')).join(', ')}</td><td>{row.result}</td></tr>)}</tbody></table></>}
      {panel==='chains'&&<><h2>Cadenas dimensionales</h2><p>Toda altura exige datum. Una entrada desconocida abre la cadena; un margen negativo propaga conflicto.</p><div className="integration-chain-list">{draft.dimensionalChains.map((chain)=><article key={chain.chainId}><strong>{chain.name}</strong><span>Datum: {chain.datum}</span><div>{chain.members.map(({role},index)=><span key={role}>{index?' → ':''}{role}</span>)}</div><small>Estado: {chain.status} · margen: {chain.margin??'unknown'} {chain.unit}</small></article>)}</div></>}
      {panel==='interferences'&&<><h2>Interferencias estáticas y dinámicas</h2><p>La ausencia de colisión en el modelo no acredita compatibilidad física.</p><div className="integration-chain-list">{draft.interferenceChecks.map((check)=><article key={check.checkId}><strong>{check.kind==='static'?'Estático':'Dinámico'} · {check.componentIds.map(componentLabel).join(' ↔ ')}</strong><span>Evaluados: {check.statesEvaluated.join(', ')}</span><span>Omitidos: {check.statesOmitted.join(', ')}</span><small>{check.result}</small></article>)}</div></>}
      {panel==='donors'&&<><h2>Donante frente a receptor</h2><p>Semejanza visual y misma marca no prueban identidad ni compatibilidad. Conserva procedencia, referencia, interfaces, modificación prevista y reversibilidad.</p><div className="integration-callout"><AlertTriangle/><strong>Modificar caja, aro, tija, esfera o agujas pertenece a etapa 6.</strong></div></>}
      {panel==='assembly'&&<><h2>Plan de montaje reversible</h2><ol className="integration-assembly">{ACADEMY_STAGE_5_ASSEMBLY_PLAN.map((step)=><li key={step.stepId}><strong>{step.title}</strong><span>Checkpoint: {step.checkpoint}</span><span>Detener: {step.stopCondition}</span><small>Rollback: {step.rollback} · planned-only</small></li>)}</ol></>}
      {panel==='dossier'&&<><h2>Dossier final</h2><div className="integration-dossier">{ACADEMY_STAGE_5_DOSSIER_SECTIONS.map((section)=><div key={section}><CheckCircle2 size={15}/><span>{section}</span><small>{dossier.sectionCoverage[section]}</small></div>)}</div><div className="integration-callout"><strong>Conclusión limitada</strong><span>{dossier.conclusion}</span></div></>}
      {panel==='review'&&<><h2>Revisión personal del método</h2><p>No es certificación ni revisión humana completada. Permite anotar qué parte quieres volver a estudiar.</p><div className="integration-review-list">{ACADEMY_STAGE_5_METHOD_SELF_REVIEW.map((item)=><label key={item}><input type="checkbox"/> {item.replaceAll('-',' ')}</label>)}</div><p><strong>{ACADEMY_STAGE_5_VISUAL_QUESTION_COVERAGE.length}</strong> preguntas visuales cuentan con alternativa textual y límites.</p></>}
    </main>
    <footer className="integration-learning-link"><a href={`#/learning/lesson/${encodeURIComponent(snapshot.location.query.fromLesson??lessonByPanel[panel]??lessonByPanel.overview)}`}>Volver a la lección que explica este apartado</a><span>El laboratorio aplica el método; la teoría permanece en Academia.</span></footer>
  </div>
}
