import type { AcademyLegacySectionAlias, AcademyReaderSection, AcademyVisualCue } from '../../academyReaderModel'
import type { AcademySourcePreservingLessonContext, AcademyStage5SectionSpec } from '../types'
import { academySourceSectionWordCount } from '../sourcePreservingComposition'
import { academy014KSourceSectionDispositions } from './contentPreservation'
import { academyStage5LessonCuration } from './stage5Lessons'

const glossaryTerms=(value:string)=>[...new Set([...value.matchAll(/\{\{term:([^}]+)\}\}/g)].map((match)=>match[1]))]
function cue(lessonId:string,sectionId:string,title:string):AcademyVisualCue{return{cueId:`reader.cue.${sectionId}`,lessonId,sectionId,order:0,purpose:'compare',kind:'none',sourceType:'none',visualDecision:'text-sufficient',selectorIds:[],isolation:[],isolationIds:[],transparencyById:{},labels:[],labelDefinitions:[],pedagogicalQuestion:`¿Qué dato permite resolver «${title}»?`,caption:title,altText:`El apartado ${title} conserva alternativa textual completa.`,fidelity:'not-applicable',limitations:['No se añade escala, cota o geometría inventada.'],expectedObservation:'Se distinguen dato, unknown, conflicto y validación pendiente.',readingModePolicy:'omit',semanticSpecificity:'section-specific',evidenceOfSpecificity:[],reviewStatus:'unreviewed',implementationStatus:'not-required',provenance:'editorial-decision',sourceRole:'none',curationStatus:'unnecessary'}}
function curated(lessonId:string,spec:AcademyStage5SectionSpec,sources:readonly AcademyReaderSection[]):AcademyReaderSection{const first=sources[0];const curation=academyStage5LessonCuration(lessonId);if(!first||!curation)throw new Error(`Falta fuente o curación 0.14K para ${lessonId}.`);return{sectionId:spec.sectionId,lessonId,blockId:curation.sourceBlockId,sourceBlockId:curation.sourceBlockId,sourceBlockIds:[...new Set(sources.flatMap(({sourceBlockIds,sourceBlockId})=>sourceBlockIds.length?sourceBlockIds:[sourceBlockId]))],sourceBlockVersion:first.sourceBlockVersion,order:0,ordinal:0,heading:spec.title,headingLevel:2,title:spec.title,role:spec.role,markdown:spec.markdown,wordCount:academySourceSectionWordCount(spec.markdown),visualCueIds:[`reader.cue.${spec.sectionId}`],glossaryTermIds:glossaryTerms(spec.markdown),conceptIds:[...new Set(sources.flatMap(({conceptIds=[]})=>conceptIds))],claimIds:[...curation.sourceClaimIds],sourceLocators:[...new Set(sources.flatMap(({sourceLocators=[]})=>sourceLocators))],requiredForStudy:spec.requiredForStudy??true,collapsible:spec.collapsible??false,defaultExpanded:!(spec.collapsible??false),curationMethod:'pilot-override',curationConfidence:'high',visualCue:cue(lessonId,spec.sectionId,spec.title)}}
const reorder=(sections:readonly AcademyReaderSection[])=>sections.map((section,index)=>({...section,order:index+1,ordinal:index+1,visualCue:{...section.visualCue,order:index+1}}))
export function applyAcademy014KLessonCuration(context:AcademySourcePreservingLessonContext):AcademyReaderSection[]{const curation=academyStage5LessonCuration(context.lessonId);if(!curation)return[...context.currentSections];const dispositions=academy014KSourceSectionDispositions(context.lessonId,context.authoredSections);if(dispositions.length!==context.authoredSections.length||dispositions.some(({action})=>action!=='retained'))throw new Error(`Etapa 5 debe conservar toda la teoría de ${context.lessonId}.`);const additions=curation.sections.map((spec)=>({spec,section:curated(context.lessonId,spec,context.authoredSections)}));const before=additions.filter(({spec})=>spec.placement==='before-source').map(({section})=>section);const adjacent=additions.filter(({spec})=>spec.placement==='after-first-substantive-source').map(({section})=>section);const after=additions.filter(({spec})=>spec.placement==='after-source').map(({section})=>section);const tail=additions.filter(({spec})=>spec.placement==='reference-tail').map(({section})=>section);const substantive=context.currentSections.filter(({role,markdown})=>!['reference','sources','limitations'].includes(role)&&markdown.trim());const references=context.currentSections.filter((section)=>!substantive.includes(section));const[first,...rest]=substantive;return reorder([...before,...(first?[first]:[]),...adjacent,...rest,...after,...references,...tail])}
export function academy014KLegacyAliases(context:AcademySourcePreservingLessonContext,currentSections:readonly AcademyReaderSection[]):AcademyLegacySectionAlias[]{if(!academyStage5LessonCuration(context.lessonId)||!currentSections[0])return[];return context.previousPhaseSections.map((historical)=>{const target=currentSections.find(({sectionId})=>sectionId===historical.sectionId)??currentSections.find(({role})=>role===historical.role)??currentSections[0];return{lessonId:context.lessonId,legacySegmentId:historical.sectionId,sectionId:target.sectionId,newSectionId:target.sectionId,method:'explicit-alias',matchMethod:'explicit-alias',confidence:target.sectionId===historical.sectionId?'high':'medium',fallbackSectionId:currentSections[0].sectionId,reason:target.sectionId===historical.sectionId?'El apartado conserva su ID.':'El apartado resuelve a un equivalente visible de 0.14K.'}})}

