import { academyStage5SectionId } from './stage5Sections'

export interface AcademyStage5IntegrationRefResolution {
  ref: string
  historicalStatus: 'planned-reference-preserved'
  curriculumResolutionStatus: 'implemented-method' | 'implemented-source-limited' | 'implemented-project-input-required'
  projectDataStatus: 'not-evaluated' | 'source-needed' | 'measurement-needed' | 'conflict-found' | 'documentally-compatible' | 'physical-validation-pending'
  resolvedByLessonIds: readonly string[]
  resolvedBySectionIds: readonly string[]
  resolvedByVisualIds: readonly string[]
  resolvedByActivityIds: readonly string[]
  resolvedByPracticeIds: readonly string[]
  requiredInputs: readonly string[]
  sourceAuthority: readonly string[]
  limitations: readonly string[]
}

const ref = (value: Omit<AcademyStage5IntegrationRefResolution,'historicalStatus'|'curriculumResolutionStatus'|'projectDataStatus'>): AcademyStage5IntegrationRefResolution => ({
  historicalStatus:'planned-reference-preserved',curriculumResolutionStatus:'implemented-method',projectDataStatus:'source-needed',...value,
})

export const ACADEMY_STAGE_5_INTEGRATION_REFS: readonly AcademyStage5IntegrationRefResolution[] = [
  ref({ref:'stage5-gap.movement-holder',resolvedByLessonIds:['lesson.encyclopedia.cases-water.arquitectura-de-caja'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.encyclopedia.cases-water.arquitectura-de-caja')],resolvedByVisualIds:['visual.stage5.holder-functions.v1','visual.stage5.radial-fit.v1'],resolvedByActivityIds:['activity.encyclopedia.cases-water.arquitectura-de-caja'],resolvedByPracticeIds:['personal-practice.stage5.holder-envelope'],requiredInputs:['envolvente del movimiento','asiento de caja','apoyo axial','alineación de tija'],sourceAuthority:['manufacturer-drawing','supplier-technical-sheet','measured-own-component'],limitations:['No genera una geometría fabricable ni autoriza modificar caja o aro.']}),
  ref({ref:'stage5-gap.dial-feet',resolvedByLessonIds:['lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera')],resolvedByVisualIds:['visual.stage5.dial-feet.v1'],resolvedByActivityIds:['activity.encyclopedia.dials-hands-finishing.arquitectura-de-esfera'],resolvedByPracticeIds:['personal-practice.stage5.dial-feet-map'],requiredInputs:['cantidad','radio','ángulos','longitud','agujeros del movimiento'],sourceAuthority:['manufacturer-drawing','supplier-technical-sheet','measured-own-component'],limitations:['No propone cortar, soldar o pegar pies.']}),
  ref({ref:'stage5-gap.dial-diameter',resolvedByLessonIds:['lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera')],resolvedByVisualIds:['visual.stage5.dial-seat.v1'],resolvedByActivityIds:['activity.encyclopedia.dials-hands-finishing.arquitectura-de-esfera'],resolvedByPracticeIds:['personal-practice.stage5.dial-seat'],requiredInputs:['diámetro total','asiento','apertura visible','juego radial'],sourceAuthority:['supplier-technical-sheet','measured-own-component'],limitations:['El diámetro comercial de la esfera no equivale automáticamente al asiento útil.']}),
  ref({ref:'stage5-gap.hand-holes-fit',resolvedByLessonIds:['lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste')],resolvedByVisualIds:['visual.stage5.hand-holes.v1'],resolvedByActivityIds:['activity.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],resolvedByPracticeIds:['personal-practice.stage5.hand-interface-table'],requiredInputs:['postes','agujeros','tubos','material','ajuste aplicable'],sourceAuthority:['manufacturer-drawing','supplier-technical-sheet'],limitations:['La igualdad nominal no valida el ajuste; este método no enseña brochado ni reducción.']}),
  ref({ref:'stage5-gap.hour-wheel-stack',resolvedByLessonIds:['lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste')],resolvedByVisualIds:['visual.stage5.hand-stack.v1','visual.stage5.axial-chain.v1'],resolvedByActivityIds:['activity.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],resolvedByPracticeIds:['personal-practice.stage5.axial-stack'],requiredInputs:['altura rueda de horas','esfera','alturas de agujas','altura interior cristal'],sourceAuthority:['manufacturer-drawing','supplier-technical-sheet','measured-own-component'],limitations:['Una cadena con una entrada desconocida permanece abierta.']}),
  ref({ref:'stage5-gap.caseback-clearance',resolvedByLessonIds:['lesson.encyclopedia.cases-water.toh-exterior-interfaces'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.encyclopedia.cases-water.toh-exterior-interfaces')],resolvedByVisualIds:['visual.stage5.rotor-caseback.v1'],resolvedByActivityIds:['activity.encyclopedia.cases-water.toh-exterior-interfaces'],resolvedByPracticeIds:['personal-practice.stage5.rear-clearance'],requiredInputs:['envolvente posterior','barrido del rotor','fijación','junta','cavidad del fondo'],sourceAuthority:['manufacturer-drawing','supplier-technical-sheet'],limitations:['La ausencia de colisión digital no acredita holgura real.']}),
  ref({ref:'stage5-gap.dynamic-interferences',resolvedByLessonIds:['lesson.encyclopedia.cases-water.toh-materiales-exterior'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.encyclopedia.cases-water.toh-materiales-exterior')],resolvedByVisualIds:['visual.stage5.dynamic-sweeps.v1'],resolvedByActivityIds:['activity.encyclopedia.cases-water.toh-materiales-exterior'],resolvedByPracticeIds:['personal-practice.stage5.dynamic-state-list'],requiredInputs:['envolventes','estados','referencias geométricas','márgenes'],sourceAuthority:['manufacturer-drawing','derived-from-verified-inputs'],limitations:['Solo se comprueban los estados representados.']}),
  ref({ref:'stage5-gap.final-assembly-verification',resolvedByLessonIds:['lesson.mechanical.final-project','lesson.capstone.design.capstone'],resolvedBySectionIds:[academyStage5SectionId.method('lesson.mechanical.final-project')],resolvedByVisualIds:['visual.stage5.assembly-plan.v1','visual.stage5.checkpoints.v1'],resolvedByActivityIds:['activity.mechanical.build-final-project','activity.capstone.design.capstone'],resolvedByPracticeIds:['personal-practice.stage5.assembly-stop-conditions'],requiredInputs:['dependencias','puntos de control','condiciones de parada','método de reversión','plan de verificación'],sourceAuthority:['derived-from-verified-inputs'],limitations:['Planifica; no ejecuta un montaje físico ni declara el reloj completado.']}),
] as const

export const ACADEMY_STAGE_5_PARTIAL_RESOLUTIONS = [
  {ref:'stage5-partial.external-dimensions',lessonIds:['lesson.encyclopedia.cases-water.toh-exterior-interfaces'],visualIds:['visual.stage5.axial-chain.v1'],dossierSection:'Dimensiones',status:'implemented-method'},
  {ref:'stage5-partial.cannon-pinion',lessonIds:['lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],visualIds:['visual.stage5.hand-holes.v1'],dossierSection:'Matriz de compatibilidad',status:'implemented-method'},
  {ref:'stage5-partial.axial-stack',lessonIds:['lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],visualIds:['visual.stage5.hand-stack.v1'],dossierSection:'Cadena axial',status:'implemented-method'},
  {ref:'stage5-partial.water-resistance',lessonIds:['lesson.encyclopedia.cases-water.toh-materiales-exterior','lesson.encyclopedia.cases-water.pruebas-de-presion'],visualIds:['visual.stage5.leak-paths.v1'],dossierSection:'Plan de verificación',status:'implemented-method',projectDefault:'not-verified'},
  {ref:'stage5-partial.donor-parts',lessonIds:['lesson.encyclopedia.atlas-restoration-design.restauracion-y-fabricacion-de-repuesto'],visualIds:['visual.stage5.donor-receiver.v1'],dossierSection:'Donantes',status:'implemented-method'},
] as const
