import { academyReaderStableHash } from '../../academyReaderIdentity'
import type { AcademyDiagramData, AcademyReaderSection, AcademySectionVisualCuration } from '../../academyReaderModel'
import type { AcademySourceLocator, AcademyStage0PhotoBrief, AcademyStage5VisualDesign } from '../types'
import { academyStage5SectionId } from './stage5Sections'

interface Spec { id:string; question:string; title:string; lessonId:string; section:'method'|'example'; nodes:readonly string[]; sourceId:string; limitation:string }
const specs: readonly Spec[] = [
  {id:'visual.stage5.requirements-to-movement.v1',question:'¿Cómo lleva un requisito a elegir movimiento?',title:'Requisitos y movimiento',lessonId:'lesson.capstone.design.requirements',section:'method',nodes:['intención','métrica o unknown','candidatos','elección limitada'],sourceId:'source.miyota.8215.official',limitation:'El 8215 es ejemplo, no requisito.'},
  {id:'visual.stage5.document-authority.v1',question:'¿Qué autoridad corresponde a cada dato?',title:'Autoridad documental',lessonId:'lesson.capstone.design.acquired-movement',section:'method',nodes:['pregunta','fabricante','supplier','medición','unknown'],sourceId:'source.miyota.8215.drawing',limitation:'Una ficha comercial no se eleva a drawing.'},
  {id:'visual.stage5.inventory.v1',question:'¿Qué integra el reloj completo?',title:'Inventario del conjunto',lessonId:'lesson.capstone.validation.calibre-transfer',section:'method',nodes:['movimiento','caja y cierre','mando','esfera y agujas','documentos'],sourceId:'source.private.daniels.movement-design',limitation:'El esquema no aporta cotas comerciales.'},
  {id:'visual.stage5.radial-fit.v1',question:'¿Cómo encajan movimiento, aro y caja?',title:'Cadena radial',lessonId:'lesson.encyclopedia.cases-water.arquitectura-de-caja',section:'method',nodes:['eje','movimiento','aro interior','aro exterior','asiento'],sourceId:'source.private.daniels.movement-design',limitation:'Sobre conceptual sin escala.'},
  {id:'visual.stage5.holder-functions.v1',question:'¿Qué funciones puede cumplir el aro?',title:'Funciones del aro',lessonId:'lesson.encyclopedia.cases-water.arquitectura-de-caja',section:'example',nodes:['centrado','apoyo','retención','antirrotación','acceso'],sourceId:'source.private.daniels.movement-design',limitation:'No es plano fabricable.'},
  {id:'visual.stage5.control-chain.v1',question:'¿Cómo conecta tija, tubo y corona?',title:'Cadena de mando',lessonId:'lesson.encyclopedia.cases-water.corona-tubo-y-tija',section:'method',nodes:['movimiento','eje de tija','tubo','corona','estados'],sourceId:'source.miyota.8215.drawing',limitation:'No instruye corte ni roscado.'},
  {id:'visual.stage5.axial-chain.v1',question:'¿Cómo se construye la cadena axial completa?',title:'Cadena axial',lessonId:'lesson.encyclopedia.cases-water.toh-exterior-interfaces',section:'method',nodes:['datum','movimiento','esfera','agujas','cristal y fondo'],sourceId:'source.private.daniels.movement-design',limitation:'Unknowns mantienen la cadena abierta.'},
  {id:'visual.stage5.dial-seat.v1',question:'¿Qué diferencia diámetro total, asiento y apertura?',title:'Geometría de esfera y asiento',lessonId:'lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera',section:'method',nodes:['diámetro total','asiento','apertura visible','rehaut'],sourceId:'source.private.daniels.movement-design',limitation:'No usa un valor comercial como fit.'},
  {id:'visual.stage5.dial-feet.v1',question:'¿Cómo se localizan y fijan los pies?',title:'Mapa polar de pies',lessonId:'lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera',section:'example',nodes:['centro','radio','ángulo','longitud','agujero receptor'],sourceId:'source.private.daniels.movement-design',limitation:'No propone cortar, soldar o pegar.'},
  {id:'visual.stage5.hand-holes.v1',question:'¿Cómo se comparan agujeros y tubos?',title:'Interfaces de agujas',lessonId:'lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste',section:'method',nodes:['poste','agujero','tubo','material','fit pendiente'],sourceId:'source.miyota.8215.drawing',limitation:'Nominal igual no prueba ajuste.'},
  {id:'visual.stage5.hand-stack.v1',question:'¿Cómo se apilan las agujas?',title:'Stack de indicación',lessonId:'lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste',section:'example',nodes:['rueda de horas','esfera','hora','minuto','segundo'],sourceId:'source.miyota.8215.drawing',limitation:'Todas las alturas requieren datum.'},
  {id:'visual.stage5.crystal-clearance.v1',question:'¿Qué altura interior deja el cristal?',title:'Cristal y volumen interior',lessonId:'lesson.encyclopedia.cases-water.cristales-y-biseles',section:'method',nodes:['asiento','retención','cara interior','aguja','margen'],sourceId:'source.private.daniels.movement-design',limitation:'No prescribe instalación.'},
  {id:'visual.stage5.rotor-caseback.v1',question:'¿Cómo se compara rotor y fondo?',title:'Holgura posterior',lessonId:'lesson.encyclopedia.cases-water.toh-exterior-interfaces',section:'example',nodes:['rotor','barrido','fijación','junta','fondo'],sourceId:'source.miyota.8215.drawing',limitation:'No simula juego ni deformación.'},
  {id:'visual.stage5.leak-paths.v1',question:'¿Dónde están las rutas de fuga y juntas?',title:'Rutas de fuga',lessonId:'lesson.encyclopedia.cases-water.toh-materiales-exterior',section:'method',nodes:['cristal','corona','fondo','juntas','ensayo pendiente'],sourceId:'source.private.daniels.movement-design',limitation:'Sin ensayo: not-verified.'},
  {id:'visual.stage5.dynamic-sweeps.v1',question:'¿Qué estados dinámicos se comprobaron?',title:'Barridos y estados',lessonId:'lesson.encyclopedia.cases-water.toh-materiales-exterior',section:'example',nodes:['agujas','rotor','corona','evaluados','omitidos'],sourceId:'source.miyota.8215.drawing',limitation:'Solo modelo representado.'},
  {id:'visual.stage5.donor-receiver.v1',question:'¿Qué diferencia donante y receptor?',title:'Auditoría de donante',lessonId:'lesson.encyclopedia.atlas-restoration-design.restauracion-y-fabricacion-de-repuesto',section:'method',nodes:['procedencia','identidad','interfaces','modificación','reversibilidad'],sourceId:'source.private.daniels.movement-design',limitation:'Parecido y marca no prueban compatibilidad.'},
  {id:'visual.stage5.compatibility-matrix.v1',question:'¿Cómo se lee la matriz de compatibilidad?',title:'Matriz de interfaces',lessonId:'lesson.capstone.design.capstone',section:'method',nodes:['interfaz','datos requeridos','datos disponibles','resultado','decisión'],sourceId:'source.miyota.8215.drawing',limitation:'Incomplete no se presenta como compatible.'},
  {id:'visual.stage5.assembly-plan.v1',question:'¿Cómo se ordena el plan de montaje?',title:'Plan reversible',lessonId:'lesson.mechanical.final-project',section:'method',nodes:['dependencia','paso','checkpoint','stop','rollback'],sourceId:'source.private.daniels.movement-design',limitation:'Planificación, no ejecución.'},
  {id:'visual.stage5.checkpoints.v1',question:'¿Dónde se detiene el proyecto?',title:'Checkpoints y stop conditions',lessonId:'lesson.mechanical.final-project',section:'example',nodes:['dato','control','conflicto','detener','reabrir'],sourceId:'source.private.daniels.movement-design',limitation:'No existe secuencia universal.'},
  {id:'visual.stage5.dossier.v1',question:'¿Qué conserva el dossier final?',title:'Dossier de integración',lessonId:'lesson.capstone.design.capstone',section:'example',nodes:['requisitos','documentos','matriz y cadenas','unknowns','conclusión'],sourceId:'source.miyota.8215.drawing',limitation:'No declara reloj completado.'},
] as const

const locator = (sourceId:string):AcademySourceLocator => ({sourceId,documentLocator:sourceId.startsWith('source.miyota')?'Snapshot oficial MIYOTA 8215 verificado en 0.14J':'Registro canónico de fuente privada; método conceptual sin cotas comerciales',verificationMethod:'source-limited'})
const diagram = (spec:Spec):AcademyDiagramData => ({title:spec.title,nodes:spec.nodes.map((label,index) => ({id:`node.${index+1}`,label,emphasis:index===0?'primary':index===spec.nodes.length-1?'warning':'normal'})),edges:spec.nodes.slice(1).map((_,index) => ({from:`node.${index+1}`,to:`node.${index+2}`,label:'conduce a',kind:'decision'})),annotations:['Las etiquetas y el orden conservan el significado sin depender del color.']})

export const ACADEMY_STAGE_5_VISUAL_DESIGNS: readonly AcademyStage5VisualDesign[] = specs.map((spec) => {
  const semanticPayload=diagram(spec); const sectionId=spec.section==='method'?academyStage5SectionId.method(spec.lessonId):academyStage5SectionId.example(spec.lessonId)
  return {visualDesignId:spec.id,lessonIds:[spec.lessonId],sectionIds:[sectionId],pedagogicalQuestion:spec.question,semanticPayload,sourceIds:[spec.sourceId],sourceLocators:[locator(spec.sourceId)],fidelity:'conceptual',limitations:[spec.limitation,'Diagrama semántico sin dimensiones inventadas.'],accessibilitySummary:`${spec.title}: ${spec.nodes.join(', ')}.`,longDescription:`${spec.title}. ${spec.nodes.join(' conduce a ')}. ${spec.limitation}`,implementationStatus:'implemented',contentHash:academyReaderStableHash(`${spec.question}\n${spec.limitation}`),visualHash:academyReaderStableHash(JSON.stringify(semanticPayload)),colorIndependent:true,reducedMotionSafe:true}
})
export const ACADEMY_STAGE_5_VISUAL_QUESTION_COVERAGE = specs.map(({question}) => question)
export const ACADEMY_STAGE_5_REUSED_VISUALS = ['visual.mechanical.final-project'] as const

const photoIds=['case-interior','movement-seat','stem-tube-alignment','dial-feet','dial-seat','hand-tubes','hand-stack','crystal-clearance','caseback-rotor','gasket-path','donor-identification','completed-dry-layout'] as const
export const ACADEMY_STAGE_5_PHOTO_BRIEFS: readonly AcademyStage0PhotoBrief[] = photoIds.map((id) => ({photoBriefId:`photo-brief.stage5.${id}`,subject:id.replaceAll('-',' '),scale:'macro con escala declarada',angle:'frontal y rasante; segundo ángulo para datum',lighting:'difusa y rasante documentadas',background:'neutro mate',requiredDetail:'las dos caras de la interfaz y su referencia',comparison:'componente receptor o condición alternativa real',metadata:['autoría','licencia','fecha','equipo','aumento','referencia','unidad'],avoidConfusionWith:['perspectiva','reflejo','pieza de otra variante','escala no declarada'],authorshipAndLicense:'Fotografía real propia o licenciada; no IA.',status:'future-real-photo-required'}))

export function academyStage5VisualForSection(sectionId:string){return ACADEMY_STAGE_5_VISUAL_DESIGNS.find(({sectionIds})=>sectionIds.includes(sectionId))}
export function academyStage5SectionVisualCuration(input:{lessonId:string;section:AcademyReaderSection;contentHash:string}):AcademySectionVisualCuration|undefined{
  const design=academyStage5VisualForSection(input.section.sectionId); if(!design||!design.lessonIds.includes(input.lessonId))return undefined
  return {curationId:`curation.0.14k.${design.visualDesignId}.${academyReaderStableHash(input.section.sectionId)}`,lessonId:input.lessonId,sectionId:input.section.sectionId,contentHash:input.contentHash,sectionHash:academyReaderStableHash(input.section.markdown),pedagogicalPurpose:design.semanticPayload.title,pedagogicalQuestion:design.pedagogicalQuestion,essentialConcepts:design.semanticPayload.nodes.map(({label})=>label),visualDecision:'content-specific-diagram',visualDesignId:design.visualDesignId,visualKind:'diagram',diagramSchemaId:`diagram.${design.visualDesignId}.semantic`,diagramData:design.semanticPayload,selectorIds:[],isolationIds:[],transparencyById:{},labelDefinitions:design.semanticPayload.nodes.map(({id,label,detail})=>({id,label,description:detail})),expectedObservation:design.longDescription,readingModePolicy:'inline-essential',fidelity:'conceptual',limitations:[...design.limitations],sourceBasis:[...design.sourceIds],curationMethod:'codex-assisted-personal-curation',ownerReviewStatus:'owner-review-pending',technicalReviewStatus:'technical-expert-review-pending',technicalStatus:'source-limited',notes:['Original, textual alternative, color independent and reduced-motion safe.']}
}

