import type { AcademyStage5PersonalPractice } from '../types'

const practice = (id:string,lessonIds:string[],title:string,objective:string,record:string[]): AcademyStage5PersonalPractice => ({
  personalPracticeId:`personal-practice.stage5.${id}`,lessonIds,title,objective,inexpensiveMaterials:['documentos del proyecto','hoja local o laboratorio de integración'],preparation:['Trabaja con un modelo didáctico o con datos no sensibles.','Marca de forma explícita cualquier dato ausente.'],steps:['Formula la pregunta.','Registra entradas y procedencia.','Aplica el método sin completar datos ausentes.','Guarda la decisión, el límite y el siguiente dato necesario.'],help:['Usa la jerarquía de autoridad.','Vuelve a la interfaz mínima.'],stopSignal:'Detente ante una adaptación física, un dato sin autoridad o una conclusión más fuerte que la evidencia.',possibleDamage:['Ninguno: es una práctica documental y local; no manipula componentes.'],observe:['Qué dato cambia la decisión.','Qué dato pendiente impide cerrar la interfaz.'],record,personalCriterion:['Puedo explicar por qué la interfaz está abierta, en conflicto o pendiente.','No afirmo una validación física.'],suggestedRepetition:'Una vez por familia de interfaces y cada vez que cambie una entrada.',certificationStatus:'optional-local-not-certified',affectsProgress:false,createsMastery:false,completesLesson:false,
})

export const ACADEMY_STAGE_5_PERSONAL_PRACTICES: readonly AcademyStage5PersonalPractice[] = [
  practice('requirements-sheet',['lesson.capstone.design.requirements'],'Pliego verificable','Convertir una intención en requisitos sin inventar métricas.',['deseo','métrica o dato pendiente','prioridad','verificación futura']),
  practice('movement-candidates',['lesson.capstone.design.acquired-movement'],'Tabla de movimientos candidatos','Comparar función, documentación y riesgo de integración.',['candidatos','documentos','datos pendientes','razón de la elección']),
  practice('component-inventory',['lesson.capstone.validation.calibre-transfer'],'Inventario del reloj completo','Comprobar que ninguna categoría queda implícita.',['categoría','referencia','estado','procedencia']),
  practice('holder-envelope',['lesson.encyclopedia.cases-water.arquitectura-de-caja'],'Envolvente conceptual del aro','Asignar funciones e interfaces al aro sin fabricar.',['funciones','referencias geométricas','entradas ausentes','estado conceptual']),
  practice('control-chain',['lesson.encyclopedia.cases-water.corona-tubo-y-tija'],'Cadena de mando','Separar eje, rosca, longitud y recorrido.',['estados','interfaces','datos pendientes','condiciones de parada']),
  practice('rear-clearance',['lesson.encyclopedia.cases-water.toh-exterior-interfaces'],'Holgura posterior','Construir la cadena rotor–fondo.',['envolvente','junta','margen o dato pendiente','límite dinámico']),
  practice('dial-feet-map',['lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera'],'Mapa de pies de esfera','Registrar cantidad, radio y ángulo sin adaptar.',['pies','agujeros','referencias','adaptación necesaria']),
  practice('dial-seat',['lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera'],'Esfera, asiento y apertura','Distinguir los tres diámetros y sus referencias geométricas.',['diámetro total','asiento','apertura','juego']),
  practice('hand-interface-table',['lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],'Tabla de agujas y postes','Comparar las dos caras del ajuste.',['postes','agujeros','tubos','autoridad']),
  practice('axial-stack',['lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste'],'Apilado axial','Propagar una altura ausente sin convertirla en cero.',['referencia geométrica','miembros','margen','datos pendientes']),
  practice('leak-paths',['lesson.encyclopedia.cases-water.toh-materiales-exterior'],'Mapa de rutas de fuga','Separar diseño y ensayo.',['rutas','juntas','documentos','estado no verificado']),
  practice('dynamic-state-list',['lesson.encyclopedia.cases-water.toh-materiales-exterior'],'Estados dinámicos','Enumerar barridos comprobados y omitidos.',['estados evaluados','estados omitidos','envolventes','limitaciones']),
  practice('donor-audit',['lesson.encyclopedia.atlas-restoration-design.restauracion-y-fabricacion-de-repuesto'],'Auditoría de donante','Sustituir parecido por identidad e interfaces.',['procedencia','identidad','interfaces','reversibilidad']),
  practice('assembly-stop-conditions',['lesson.mechanical.final-project'],'Condiciones de parada del montaje','Revisar dependencias y métodos de reversión sin ejecutar el montaje.',['pasos','dependencias','puntos de control','método de reversión']),
  practice('dossier-conclusion',['lesson.capstone.design.capstone'],'Conclusión limitada','Emitir una decisión que conserve los conflictos y la validación pendiente.',['estado','evidencia','datos pendientes','pruebas físicas pendientes']),
] as const
export function academyStage5PersonalPracticesForLesson(lessonId:string) { return ACADEMY_STAGE_5_PERSONAL_PRACTICES.filter(({lessonIds}) => lessonIds.includes(lessonId)) }
