import type { AcademyCurriculumPathRole, AcademyStage5EditorialArchetype } from '../types'
import { academyStage5EditorialContract } from './stage5EditorialContracts'

export interface AcademyStage5CatalogEntry {
  lessonId: string
  chapterId: 'chapter.5.1' | 'chapter.5.2' | 'chapter.5.3' | 'chapter.5.4' | 'chapter.5.5'
  pathRole: Extract<AcademyCurriculumPathRole,'anchor'|'support'>
  requiredActivityId?: string
  centralQuestion: string
  observableOutcome: string
  methodFocus: string
  workedExample: string
  sourceScope: string
  visualDesignIds: readonly string[]
  editorialArchetype: AcademyStage5EditorialArchetype
  whyNow: string
  checkpointExpectedElements: readonly string[]
}

type Seed = Omit<AcademyStage5CatalogEntry,'editorialArchetype'|'whyNow'|'checkpointExpectedElements'>
const entry = (seed: Seed): AcademyStage5CatalogEntry => ({...seed,...academyStage5EditorialContract(seed.chapterId)})

export const ACADEMY_STAGE_5_CATALOG: readonly AcademyStage5CatalogEntry[] = [
  entry({lessonId:'lesson.capstone.design.requirements',chapterId:'chapter.5.1',pathRole:'anchor',requiredActivityId:'activity.capstone.design.requirements',centralQuestion:'¿Qué reloj quiero integrar y cómo sabré si satisface cada requisito?',observableOutcome:'Redactar un pliego que separe deseos, métricas, datos pendientes y método de verificación.',methodFocus:'Uso, tamaño, indicaciones, mantenimiento, entorno, coste, reversibilidad y política de donantes.',workedExample:'«Cómodo» se mantiene como deseo hasta declarar una métrica o una comprobación futura.',sourceScope:'Método de diseño; no inventa especificaciones comerciales.',visualDesignIds:['visual.stage5.requirements-to-movement.v1'] }),
  entry({lessonId:'lesson.capstone.design.acquired-movement',chapterId:'chapter.5.1',pathRole:'anchor',requiredActivityId:'activity.capstone.design.acquired-movement',centralQuestion:'¿Qué movimiento adquirido ofrece funciones, documentación e interfaces suficientes?',observableOutcome:'Comparar candidatos y elegir uno con incertidumbres explícitas.',methodFocus:'Funciones, documentación, disponibilidad, dimensiones, tija, esfera, agujas, repuestos y mantenibilidad.',workedExample:'El 8215 demuestra el método con la documentación oficial verificada en 0.14J; otro calibre sigue siendo válido si aporta una autoridad equivalente.',sourceScope:'Solo documentos oficiales verificados de cada referencia.',visualDesignIds:['visual.stage5.document-authority.v1'] }),
  entry({lessonId:'lesson.encyclopedia.cases-water.arquitectura-de-caja',chapterId:'chapter.5.2',pathRole:'anchor',requiredActivityId:'activity.encyclopedia.cases-water.arquitectura-de-caja',centralQuestion:'¿Cómo se referencia el movimiento dentro de la caja?',observableOutcome:'Definir envolvente, asiento, apoyo, retención, orientación y aro conceptual.',methodFocus:'Resuelve el método del aro portamovimiento sin generar cotas fabricables.',workedExample:'Un aro centra radialmente y puede apoyar axialmente; cada función exige una interfaz documentada distinta.',sourceScope:'Teoría de arquitectura y planos del componente elegido.',visualDesignIds:['visual.stage5.radial-fit.v1','visual.stage5.holder-functions.v1'] }),
  entry({lessonId:'lesson.encyclopedia.cases-water.corona-tubo-y-tija',chapterId:'chapter.5.2',pathRole:'anchor',requiredActivityId:'activity.encyclopedia.cases-water.corona-tubo-y-tija',centralQuestion:'¿Cómo se alinea movimiento, tija, tubo y corona en todos sus estados?',observableOutcome:'Construir la cadena de mando con ejes, roscas, recorrido y datos pendientes.',methodFocus:'Separar longitud, alineación, rosca, recorrido, estanqueidad y ergonomía.',workedExample:'Una rosca coincidente no compensa un eje desalineado ni demuestra longitud funcional.',sourceScope:'Plano del movimiento y ficha aplicable de tija, tubo y corona.',visualDesignIds:['visual.stage5.control-chain.v1'] }),
  entry({lessonId:'lesson.encyclopedia.cases-water.toh-exterior-interfaces',chapterId:'chapter.5.2',pathRole:'anchor',requiredActivityId:'activity.encyclopedia.cases-water.toh-exterior-interfaces',centralQuestion:'¿Qué referencias geométricas conectan el interior y el exterior?',observableOutcome:'Cerrar la cadena estructural o conservarla abierta cuando falta una entrada.',methodFocus:'Movimiento, caja, aro, mando, fondo y holgura posterior.',workedExample:'Una altura sin referencia geométrica no entra en una suma aunque su valor parezca plausible.',sourceScope:'Theory of Horology para el principio general; documentación del componente comercial para las cotas.',visualDesignIds:['visual.stage5.axial-chain.v1','visual.stage5.rotor-caseback.v1'] }),
  entry({lessonId:'lesson.capstone.manufacturing.case',chapterId:'chapter.5.2',pathRole:'support',centralQuestion:'¿Qué información necesitaría una futura fabricación de caja?',observableOutcome:'Reconocer referencias geométricas, superficies funcionales y límites sin fabricar.',methodFocus:'Apoyo conceptual; toda modificación o fabricación pertenece a etapa 6.',workedExample:'El dossier marca una adaptación prevista y se detiene antes de definir una operación.',sourceScope:'Daniels aporta método de taller, no cotas del conjunto comercial.',visualDesignIds:[] }),
  entry({lessonId:'lesson.encyclopedia.dials-hands-finishing.arquitectura-de-esfera',chapterId:'chapter.5.3',pathRole:'anchor',requiredActivityId:'activity.encyclopedia.dials-hands-finishing.arquitectura-de-esfera',centralQuestion:'¿Cómo se relacionan esfera, asiento, apertura y pies?',observableOutcome:'Comparar diámetro total, apertura, apoyo, espesor y pies con referencias geométricas comunes.',methodFocus:'Resuelve la posición de los pies y los diámetros de la esfera como método, no como adaptación física.',workedExample:'El diámetro comercial de la esfera (dial size) no se equipara al diámetro útil del asiento sin plano o medición.',sourceScope:'Ficha del proveedor, plano y medición propia trazable.',visualDesignIds:['visual.stage5.dial-seat.v1','visual.stage5.dial-feet.v1'] }),
  entry({lessonId:'lesson.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste',chapterId:'chapter.5.3',pathRole:'anchor',requiredActivityId:'activity.encyclopedia.dials-hands-finishing.agujas-geometria-y-ajuste',centralQuestion:'¿Cómo se comprueban agujeros, tubos, alturas y barridos?',observableOutcome:'Abrir una matriz de ajuste y una cadena axial sin confundir el valor nominal con el ajuste real.',methodFocus:'Resuelve el ajuste entre agujas y postes y la cadena de alturas sin brochado ni reducción.',workedExample:'Dos diámetros nominales iguales siguen pendientes de tolerancia, material y método aplicable.',sourceScope:'Plano del movimiento y ficha técnica de las agujas elegidas.',visualDesignIds:['visual.stage5.hand-holes.v1','visual.stage5.hand-stack.v1'] }),
  entry({lessonId:'lesson.capstone.manufacturing.hands',chapterId:'chapter.5.3',pathRole:'support',centralQuestion:'¿Qué información exige una futura aguja fabricada?',observableOutcome:'Reconocer geometría, tubo, equilibrio y holguras sin ejecutar fabricación.',methodFocus:'Apoyo de etapa 6; no es solución automática a incompatibilidades.',workedExample:'Una incompatibilidad se registra; no se oculta proponiendo modificar la aguja.',sourceScope:'Daniels para fabricación avanzada, con revisión de seguridad.',visualDesignIds:[] }),
  entry({lessonId:'lesson.encyclopedia.cases-water.cristales-y-biseles',chapterId:'chapter.5.4',pathRole:'anchor',requiredActivityId:'activity.encyclopedia.cases-water.cristales-y-biseles',centralQuestion:'¿Qué volumen interior deja el conjunto cristal–bisel?',observableOutcome:'Comparar asiento, retención, altura interior y barrido de agujas.',methodFocus:'La instalación física queda fuera; el modelo solo comprueba entradas declaradas.',workedExample:'Un cristal más alto comercialmente no garantiza más altura interior útil.',sourceScope:'Ficha técnica aplicable del cristal, bisel y junta.',visualDesignIds:['visual.stage5.crystal-clearance.v1'] }),
  entry({lessonId:'lesson.encyclopedia.cases-water.toh-materiales-exterior',chapterId:'chapter.5.4',pathRole:'anchor',requiredActivityId:'activity.encyclopedia.cases-water.toh-materiales-exterior',centralQuestion:'¿Cómo se documentan juntas, rutas de fuga y límites de material?',observableOutcome:'Separar diseño de cierre, preparación, ensayo y resultado.',methodFocus:'La hermeticidad permanece sin verificar mientras no exista un ensayo documentado.',workedExample:'Una junta presente en el modelo no aporta automáticamente compresión, material o clasificación.',sourceScope:'Teoría general y ficha moderna del conjunto elegido.',visualDesignIds:['visual.stage5.leak-paths.v1','visual.stage5.dynamic-sweeps.v1'] }),
  entry({lessonId:'lesson.encyclopedia.cases-water.pruebas-de-presion',chapterId:'chapter.5.4',pathRole:'support',centralQuestion:'¿Qué podría demostrar un ensayo real y qué no demuestra el diseño?',observableOutcome:'Definir un plan de verificación sin simular resultado de presión.',methodFocus:'Ensayo profesional futuro, con autoridad moderna y seguridad aplicable.',workedExample:'Sin el resultado de un ensayo, el estado sigue siendo «no verificado», nunca «hermético».',sourceScope:'Protocolo moderno aplicable pendiente; las fuentes históricas no autorizan el ensayo.',visualDesignIds:[] }),
  entry({lessonId:'lesson.capstone.design.capstone',chapterId:'chapter.5.5',pathRole:'anchor',requiredActivityId:'activity.capstone.design.capstone',centralQuestion:'¿Qué conclusión permite el dossier completo?',observableOutcome:'Emitir una conclusión de compatibilidad documental, condicional, incompatible o pendiente.',methodFocus:'Matriz, cadenas, interferencias, decisiones y validación física pendiente.',workedExample:'Sin conflictos y con todas las interfaces documentadas puede afirmarse que el proyecto es compatible documentalmente, no que el reloj esté terminado.',sourceScope:'Síntesis trazable de los documentos del proyecto.',visualDesignIds:['visual.stage5.compatibility-matrix.v1','visual.stage5.dossier.v1'] }),
  entry({lessonId:'lesson.mechanical.final-project',chapterId:'chapter.5.5',pathRole:'anchor',requiredActivityId:'activity.mechanical.build-final-project',centralQuestion:'¿Cómo se planifica un montaje final reversible?',observableOutcome:'Ordenar dependencias, puntos de control, condiciones de parada y métodos de reversión.',methodFocus:'El plan no es una secuencia universal ni se ejecuta físicamente.',workedExample:'Cada paso se detiene ante un dato crítico pendiente y vuelve a la interfaz responsable.',sourceScope:'Método de proyecto; la secuencia física depende del conjunto real.',visualDesignIds:['visual.stage5.assembly-plan.v1','visual.stage5.checkpoints.v1'] }),
  entry({lessonId:'lesson.capstone.validation.calibre-transfer',chapterId:'chapter.5.5',pathRole:'anchor',requiredActivityId:'activity.capstone.validation.calibre-transfer',centralQuestion:'¿Qué se transfiere entre calibres y qué debe volver a documentarse?',observableOutcome:'Transferir el método sin transferir cotas, ajustes ni afirmaciones del 8215.',methodFocus:'Trazar fuente, aplicabilidad y cambio de entradas.',workedExample:'El esquema de cadena axial se reutiliza; todas sus dimensiones se sustituyen por datos del nuevo calibre.',sourceScope:'Principio general transferible; cada dato comercial requiere fuente propia.',visualDesignIds:['visual.stage5.inventory.v1'] }),
  entry({lessonId:'lesson.encyclopedia.atlas-restoration-design.restauracion-y-fabricacion-de-repuesto',chapterId:'chapter.5.5',pathRole:'support',centralQuestion:'¿Cuándo una pieza donante es identificable y compatible?',observableOutcome:'Auditar identidad, procedencia, interfaces, reversibilidad y modificaciones.',methodFocus:'La semejanza visual o la marca nunca cierran la compatibilidad.',workedExample:'Un donante visualmente idéntico queda pendiente de fuente hasta cotejar la referencia y las interfaces.',sourceScope:'Los casos reales sirven como casos particulares; no se generalizan.',visualDesignIds:['visual.stage5.donor-receiver.v1'] }),
] as const

export const ACADEMY_STAGE_5_ANCHOR_IDS = ACADEMY_STAGE_5_CATALOG.filter(({pathRole}) => pathRole === 'anchor').map(({lessonId}) => lessonId)
export const ACADEMY_STAGE_5_SUPPORT_IDS = ACADEMY_STAGE_5_CATALOG.filter(({pathRole}) => pathRole === 'support').map(({lessonId}) => lessonId)
export const ACADEMY_STAGE_5_CHAPTER_SEQUENCE = ['chapter.5.1','chapter.5.2','chapter.5.3','chapter.5.4','chapter.5.5'] as const
