export const ACADEMY_STAGE_4_FINAL_CHECKPOINT = {
  checkpointId: 'checkpoint.stage4.miyota8215-dossier',
  title: 'Cierre de etapa 4 · MIYOTA 8215 documentado',
  questions: [
    '¿Qué evidencia sostiene la identidad y la variante?',
    '¿Qué documento responde a funciones, cotas, corona y piezas?',
    '¿Qué cambió entre las versiones verificadas de la lista de piezas?',
    '¿Qué relaciones del modelo son oficiales, inferidas o conceptuales?',
    '¿Qué demuestra una secuencia virtual y qué no demuestra?',
    '¿Qué escenario simbólico necesitaría fotografía o medición real?',
    '¿Dónde se colocó una verificación del simulador y cuál sería la verificación física?',
    '¿Qué prueba virtual separa dos hipótesis?',
    '¿Qué afirmaciones, versiones documentales y límites conserva el dossier?',
    '¿Qué dato del 8215 no debe transferirse a otro calibre?',
    '¿Qué permanece pendiente de una fuente aplicable antes de abrir un movimiento?',
    '¿Por qué un resultado revisable no equivale a ejecución física en este cierre?',
    '¿Qué fundamento y alcance tiene cada paso virtual?',
    '¿Qué queda expresamente fuera hasta la etapa 5?',
  ],
  actions: [
    { label: 'Repasar identificación', href: '#/learning/lesson/lesson.miyota8215.identify' },
    { label: 'Repasar documentos', href: '#/learning/lesson/lesson.miyota8215.documentation' },
    { label: 'Repasar arquitectura', href: '#/learning/lesson/lesson.miyota8215.architecture' },
    { label: 'Repasar subsistemas', href: '#/learning/lesson/lesson.miyota8215.automatic' },
    { label: 'Repasar frontera virtual', href: '#/learning/lesson/lesson.miyota8215.guided-disassembly' },
    { label: 'Repasar inspección', href: '#/learning/lesson/lesson.miyota8215.inspection' },
    { label: 'Repasar verificaciones', href: '#/learning/lesson/lesson.miyota8215.assembly-verification' },
    { label: 'Abrir dossier', href: '#/learning/lesson/lesson.miyota8215.diagnosis-project' },
    { label: 'Continuar a etapa 5', href: '#/learning/my-learning?chapter=chapter.5.1' },
  ],
  evidence: 'El cierre puede demostrar conocimiento, práctica virtual y un resultado revisable dentro del entorno local. No acredita ejecución física, no diagnostica una unidad real y no inicia la integración del reloj de etapa 5.',
} as const
