import { academyReaderStableHash } from '../../academyReaderIdentity'
import type { AcademyDiagramData, AcademyReaderSection, AcademySectionVisualCuration } from '../../academyReaderModel'
import type { AcademySourceLocator, AcademyStage0PhotoBrief, AcademyStage4VisualDesign } from '../types'
import { deriveAcademyTechnicalStatus } from './activeTechnicalStatus'
import { academyStage4SectionId } from './stage4Sections'
import { academyStage4VisibleSpanish } from './visibleLanguage'

interface Spec { visualDesignId: string; question: string; title: string; lessonIds: readonly string[]; nodes: readonly [string,string,string][]; edges: readonly [string,string,string][]; source: AcademySourceLocator; limitation: string; status: 'source-reviewed' | 'source-limited' }
const source = (sourceId: string, snapshot: string, page?: string): AcademySourceLocator => ({ sourceId, documentLocator: snapshot, page, verificationMethod: 'visual-pdf-inspection', verifiedAt: '2026-08-16' })
const internal = (title: string): AcademySourceLocator => ({ sourceId: 'source.project.horologia-system4b-blueprint', documentLocator: title, verificationMethod: 'source-limited' })
const PARTS = source('source.miyota.8215.parts-list-exploded-view', 'snapshot.miyota.8215.parts-list.fdafef81', '1')
const MANUAL = source('source.miyota.8215.instruction-manual', 'snapshot.miyota.8215.instruction-manual.6286b843', '1')

const rawSpecs: readonly Spec[] = [
  { visualDesignId: 'visual.stage4.identity-evidence.v1', question: '¿Cómo se identifica el 8215?', title: 'Escalera de identidad', lessonIds: ['lesson.miyota8215.identify'], nodes: [['evidence','Evidencia visible','observación'],['mark','Inscripción','indicio'],['document','Documento oficial','confirmación'],['variant','Variante','alcance'],['limit','Límite','provisional']], edges: [['evidence','mark','localiza'],['mark','document','coteja'],['document','variant','delimita'],['variant','limit','conserva']], source: source('source.miyota.8215.product-page','snapshot.miyota.8215.product-page.2026-08-16'), limitation: 'No identifica una unidad física por parecido.', status: 'source-reviewed' },
  { visualDesignId: 'visual.stage4.document-authority.v1', question: '¿Qué documento responde cada pregunta?', title: 'Matriz de autoridad documental', lessonIds: ['lesson.miyota8215.documentation'], nodes: [['question','Pregunta','entrada'],['spec','Specification','función y datos'],['drawing','Drawing','cotas expresas'],['manual','Manual','corona'],['parts','Parts list','piezas'],['missing','No disponible','servicio y lubricación']], edges: [['question','spec','clasifica'],['question','drawing','clasifica'],['question','manual','clasifica'],['question','parts','clasifica'],['question','missing','bloquea']], source: source('source.miyota.8215.specification','snapshot.miyota.8215.specification.bcb22d8e','1–2'), limitation: 'El documento se elige por alcance, no por posición en una lista.', status: 'source-reviewed' },
  { visualDesignId: 'visual.stage4.parts-drift.v1', question: '¿Qué cambió entre snapshots de la parts list?', title: 'Drift revisado de parts list', lessonIds: ['lesson.miyota8215.documentation'], nodes: [['previous','Snapshot anterior','hash ea5f…'],['current','Snapshot vigente','hash fdaf…'],['terms','3 términos','renombrados'],['layout','1 cambio','maquetación'],['parts','0 piezas','altas o bajas']], edges: [['previous','current','compara'],['current','terms','clasifica'],['current','layout','clasifica'],['current','parts','confirma']], source: PARTS, limitation: 'La revisión no demuestra que sea una edición formalmente numerada.', status: 'source-reviewed' },
  { visualDesignId: 'visual.stage4.architecture-authority.v1', question: '¿Cómo se leen capas, subsistemas y piezas?', title: 'Arquitectura y autoridad', lessonIds: ['lesson.miyota8215.architecture'], nodes: [['whole','Calibre completo','un ensamblaje'],['systems','Subsistemas','función'],['parts','Piezas','identidad oficial'],['relations','Relaciones','inferidas'],['geometry','Geometría','normalizada'],['unknown','Desconocidos','no rellenar']], edges: [['whole','systems','organiza'],['systems','parts','agrupa'],['parts','relations','no demuestra'],['relations','geometry','modela'],['geometry','unknown','declara']], source: PARTS, limitation: 'Fixture G2/K2/P0, no gemelo ni escala real.', status: 'source-limited' },
  { visualDesignId: 'visual.stage4.crown-states.v1', question: '¿Qué estados externos permite la corona?', title: 'Estados documentados de corona', lessonIds: ['lesson.miyota8215.winding-setting','lesson.miyota8215.calendar'], nodes: [['normal','Normal','marcha y cuerda'],['first','Primera','fecha'],['second','Segunda','hora'],['warning','Advertencia','9 PM–1 AM'],['internal','Cinemática interna','no demostrada']], edges: [['normal','first','extraer'],['first','second','extraer'],['first','warning','limita'],['second','internal','no prueba']], source: MANUAL, limitation: 'Solo manual 8215 vigente; no mezcla 8205.', status: 'source-reviewed' },
  { visualDesignId: 'visual.stage4.dependency-plan.v1', question: '¿Qué diferencia dependencia y procedimiento?', title: 'Grafo de dependencia estructural', lessonIds: ['lesson.miyota8215.plan-disassembly'], nodes: [['piece','Pieza','identidad'],['fastener','Fijación','asociación'],['retained','Elemento retenido','dependencia'],['access','Acceso','modelo'],['procedure','Procedimiento','source-needed']], edges: [['fastener','piece','retiene'],['piece','retained','cubre'],['retained','access','condiciona'],['access','procedure','no determina']], source: PARTS, limitation: 'No codifica herramienta, sentido, par ni orden físico.', status: 'source-limited' },
  { visualDesignId: 'visual.stage4.simulation-service-boundary.v1', question: '¿Qué valida una secuencia virtual?', title: 'Frontera simulación y servicio', lessonIds: ['lesson.miyota8215.guided-disassembly','lesson.miyota8215.assisted-free-disassembly'], nodes: [['state','Estado del modelo','inicio'],['action','Acción virtual','reversible'],['dependency','Dependencia','mostrada'],['checkpoint','Checkpoint','contrato interno'],['physical','Servicio físico','source-needed']], edges: [['state','action','cambia'],['action','dependency','expone'],['dependency','checkpoint','comprueba'],['checkpoint','physical','no acredita']], source: internal('Contrato de simulación 0.14J'), limitation: 'La reversibilidad digital no define montaje físico.', status: 'source-limited' },
  { visualDesignId: 'visual.stage4.symbolic-inspection.v1', question: '¿Qué puede observar el modelo y qué requiere evidencia real?', title: 'Inspección simbólica', lessonIds: ['lesson.miyota8215.inspection'], nodes: [['scenario','Escenario','símbolo'],['observation','Observación válida','estado marcado'],['hypotheses','Hipótesis','rivales'],['test','Prueba física','pendiente'],['uncertainty','Incertidumbre','conservada']], edges: [['scenario','observation','permite'],['observation','hypotheses','abre'],['hypotheses','test','distingue'],['test','uncertainty','delimita']], source: internal('Contrato de escenarios simbólicos 0.14J'), limitation: 'No representa desgaste, suciedad, aceite, holgura o amplitud reales.', status: 'source-limited' },
  { visualDesignId: 'visual.stage4.verification-layers.v1', question: '¿Dónde colocar checkpoints virtuales?', title: 'Cuatro niveles de verificación', lessonIds: ['lesson.miyota8215.assembly-verification'], nodes: [['simulation','Simulador','estado interno'],['structural','Estructural','relación documentada'],['physical','Física','unidad y método'],['acceptance','Aceptación','autoridad aplicable']], edges: [['simulation','structural','separa'],['structural','physical','no sustituye'],['physical','acceptance','no garantiza']], source: internal('Contrato de verificación 0.14J'), limitation: 'No prescribe lubricación, apriete, ajuste o fuerza.', status: 'source-limited' },
  { visualDesignId: 'visual.stage4.dossier-provenance.v1', question: '¿Cómo construir un dossier con procedencia?', title: 'Cadena de diagnóstico y dossier', lessonIds: ['lesson.miyota8215.diagnosis-project'], nodes: [['symptom','Síntoma simulado','escenario'],['hypotheses','Hipótesis','rivales'],['test','Prueba virtual','resultado'],['claim','Claim','fuente'],['limit','Límite','dato físico pendiente'],['transfer','Transferencia','solo principio']], edges: [['symptom','hypotheses','abre'],['hypotheses','test','distingue'],['test','claim','documenta'],['claim','limit','delimita'],['limit','transfer','controla']], source: internal('Contrato de dossier 0.14J'), limitation: 'Diagnostica el escenario, nunca una unidad física.', status: 'source-limited' },
]

const specs: readonly Spec[] = rawSpecs.map((spec) => ({
  ...spec,
  question: academyStage4VisibleSpanish(spec.question),
  title: academyStage4VisibleSpanish(spec.title),
  nodes: spec.nodes.map(([id, label, detail]) => [id, academyStage4VisibleSpanish(label), academyStage4VisibleSpanish(detail)] as const),
  edges: spec.edges.map(([from, to, label]) => [from, to, academyStage4VisibleSpanish(label)] as const),
  limitation: academyStage4VisibleSpanish(spec.limitation),
}))

const diagram = (spec: Spec): AcademyDiagramData => ({ title: spec.title, nodes: spec.nodes.map(([id,label,detail], index) => ({ id,label,detail,emphasis: index === 0 ? 'primary' : id === 'unknown' || id === 'missing' || id === 'physical' ? 'warning' : 'normal' })), edges: spec.edges.map(([from,to,label]) => ({ from,to,label,kind: 'decision' })), annotations: ['Etiquetas, orden y patrones conservan el significado sin depender del color.'] })

const describeRelations = (spec: Spec): string => {
  const labels = new Map(spec.nodes.map(([id, label]) => [id, label]))
  return spec.edges
    .map(([from, to, relation]) => `${labels.get(from) ?? from} se relaciona con ${labels.get(to) ?? to}: ${relation}`)
    .join('. ')
}

export const ACADEMY_STAGE_4_VISUAL_DESIGNS: readonly AcademyStage4VisualDesign[] = specs.map((spec) => {
  const semanticPayload = diagram(spec)
  return { visualDesignId: spec.visualDesignId, lessonIds: spec.lessonIds, sectionIds: spec.lessonIds.map((lessonId) => spec.visualDesignId === 'visual.stage4.parts-drift.v1' ? academyStage4SectionId.visual(lessonId,spec.visualDesignId) : academyStage4SectionId.evidence(lessonId)), pedagogicalQuestion: spec.question, semanticPayload, sourceIds: [spec.source.sourceId], sourceLocators: [spec.source], fidelity: 'calibre-specific', limitations: [spec.limitation], accessibilitySummary: `${spec.title}: ${spec.nodes.map(([,label]) => label).join(', ')}.`, longDescription: `${spec.title}. ${describeRelations(spec)}. ${spec.limitation}`, implementationStatus: 'implemented', contentHash: academyReaderStableHash([spec.question,spec.title,spec.limitation].join('\n')), visualHash: academyReaderStableHash(JSON.stringify(semanticPayload)), colorIndependent: true, reducedMotionSafe: true }
})

export const ACADEMY_STAGE_4_REUSED_VISUALS = ['visual.miyota8215.identify','visual.miyota8215.documentation','visual.miyota8215.architecture','visual.miyota8215.automatic','visual.miyota8215.winding-setting','visual.miyota8215.calendar','visual.miyota8215.barrel-energy','visual.miyota8215.train','visual.miyota8215.escapement-oscillator','visual.miyota8215.plan-disassembly','visual.miyota8215.guided-disassembly','visual.miyota8215.assisted-free-disassembly','visual.miyota8215.inspection','visual.miyota8215.assembly-verification','visual.miyota8215.diagnosis-project'] as const
export const ACADEMY_STAGE_4_VISUAL_QUESTION_COVERAGE = ['identidad','autoridad-documental','datos-vigentes','drift-parts-list','capas-exploded-view','subsistemas','automático','corona','barrilete-tren','piezas-tren','escape-oscilador','calendario','dependencia-estructural','simulación-servicio','alcance-modelo','evidencia-real','checkpoints','diagnóstico','dossier','transferencia'] as const

const photo = (subject: string): AcademyStage0PhotoBrief => ({ photoBriefId: `photo-brief.014j.${subject}`, subject, scale: 'macro con escala o aumento declarado', angle: 'frontal y rasante', lighting: 'difusa y rasante documentadas', background: 'neutro mate', requiredDetail: 'interfaz completa y detalle localizado', comparison: 'referencia o segunda condición real cuando exista', metadata: ['autoría','licencia','fecha','equipo','aumento','unidad y zona'], avoidConfusionWith: ['reflejo','polvo de preparación','fibra','artefacto de compresión'], authorshipAndLicense: 'Fotografía real propia o licenciada; no generar con IA.', status: 'future-real-photo-required' })
export const ACADEMY_STAGE_4_PHOTO_BRIEFS = ['desgaste-diente','pivote-doblado','rebaba','grieta','suciedad','exceso-aceite','estado-rubi','endshake-sideshake','marca-herramienta'].map(photo)

export function academyStage4VisualForSection(sectionId: string) { return ACADEMY_STAGE_4_VISUAL_DESIGNS.find(({ sectionIds }) => sectionIds.includes(sectionId)) }
export function academyStage4SectionVisualCuration(input: { lessonId: string; section: AcademyReaderSection; contentHash: string }): AcademySectionVisualCuration | undefined {
  const design = academyStage4VisualForSection(input.section.sectionId)
  if (!design || !design.lessonIds.includes(input.lessonId)) return undefined
  const spec = specs.find(({ visualDesignId }) => visualDesignId === design.visualDesignId)!
  const technicalStatus = deriveAcademyTechnicalStatus({ visualStatuses: [{ evidenceId: `visual-status.${design.visualDesignId}`, kind: 'visual', status: spec.status, central: true, explanation: spec.limitation }] }).technicalStatus
  return { curationId: `curation.0.14j.${design.visualDesignId}.${academyReaderStableHash(input.section.sectionId)}`, lessonId: input.lessonId, sectionId: input.section.sectionId, contentHash: input.contentHash, sectionHash: academyReaderStableHash(input.section.markdown), pedagogicalPurpose: design.semanticPayload.title, pedagogicalQuestion: design.pedagogicalQuestion, essentialConcepts: design.semanticPayload.nodes.map(({ label }) => label), visualDecision: 'content-specific-diagram', visualDesignId: design.visualDesignId, visualKind: 'diagram', diagramSchemaId: `diagram.${design.visualDesignId}.semantic`, diagramData: design.semanticPayload, selectorIds: [], isolationIds: [], transparencyById: {}, labelDefinitions: design.semanticPayload.nodes.map(({ id,label,detail }) => ({ id,label,description: detail })), expectedObservation: design.longDescription, readingModePolicy: 'inline-essential', fidelity: 'calibre-specific', limitations: [...design.limitations], sourceBasis: [...design.sourceIds], curationMethod: 'codex-assisted-personal-curation', ownerReviewStatus: 'owner-review-pending', technicalReviewStatus: technicalStatus === 'source-reviewed' ? 'not-required' : 'technical-expert-review-pending', technicalStatus, notes: ['Diagrama semántico original; alternativa textual, color independiente y movimiento reducido seguro.'] }
}
