import type { AcademySourceLocator, AcademyStage4ClaimReview } from '../types'
import { ACADEMY_STAGE_4_CATALOG } from './stage4Catalog'
import { academyStage4SectionId } from './stage4Sections'

const locator = (sourceId: string, documentLocator: string, page?: string): AcademySourceLocator => ({ sourceId, documentLocator, page, verificationMethod: 'visual-pdf-inspection', verifiedAt: '2026-08-16' })
const SPEC = locator('source.miyota.8215.specification', 'snapshot.miyota.8215.specification.bcb22d8e', '1–2')
const PRODUCT = locator('source.miyota.8215.product-page', 'snapshot.miyota.8215.product-page.2026-08-16')
const MANUAL = locator('source.miyota.8215.instruction-manual', 'snapshot.miyota.8215.instruction-manual.6286b843', '1')
const PARTS = locator('source.miyota.8215.parts-list-exploded-view', 'snapshot.miyota.8215.parts-list.fdafef81', '1')

const claim = (value: AcademyStage4ClaimReview) => value
const officialLimit = ['Aplicable únicamente al documento y variante citados.', 'No autoriza una secuencia física de servicio.']

const centralBoundaryClaims: readonly AcademyStage4ClaimReview[] = ACADEMY_STAGE_4_CATALOG.map((item) => claim({
  claimId: `claim.014j.${item.lessonId}.boundary`, lessonId: item.lessonId, sectionId: academyStage4SectionId.boundary(item.lessonId),
  claim: item.pathRole === 'optional-branch' ? 'El procedimiento físico permanece source-needed y esta rama es opcional.' : 'La evidencia digital de esta lección no acredita ejecución física.',
  claimType: item.pathRole === 'optional-branch' ? 'simulation-boundary' : item.editorialArchetype === 'traceable-dossier' ? 'diagnosis-boundary' : 'simulation-boundary',
  technicalStatus: item.pathRole === 'optional-branch' ? 'source-needed' : 'source-reviewed', central: item.pathRole === 'optional-branch', sourceIds: [], snapshotIds: [], locators: [], numericValues: [],
  verificationStatus: item.pathRole === 'optional-branch' ? 'source-needed' : 'verified-primary', limitations: ['Es un contrato pedagógico local, no una afirmación del fabricante.'],
}))

export const ACADEMY_STAGE_4_CLAIMS: readonly AcademyStage4ClaimReview[] = [
  ...centralBoundaryClaims,
  claim({ claimId: 'claim.014j.miyota8215.identity.product', lessonId: 'lesson.miyota8215.identify', sectionId: academyStage4SectionId.focus('lesson.miyota8215.identify'), claim: 'La página oficial vigente identifica el producto como MIYOTA 8215 dentro de la familia Standard Automatic.', claimType: 'identity', technicalStatus: 'source-reviewed', central: true, sourceIds: [PRODUCT.sourceId], snapshotIds: [PRODUCT.documentLocator], locators: [PRODUCT], numericValues: ['8215'], verificationStatus: 'verified-primary', limitations: officialLimit }),
  claim({ claimId: 'claim.014j.miyota8215.spec.core', lessonId: 'lesson.miyota8215.documentation', sectionId: academyStage4SectionId.evidence('lesson.miyota8215.documentation'), claim: 'El specification visible declara 11½ ligne, 5,67 mm, 21 rubíes, 21.600 vibraciones por hora, aproximadamente 42 horas, ángulo de elevación 49° y exactitud de −20 a +40 segundos por día bajo sus condiciones.', claimType: 'official-specification', technicalStatus: 'source-reviewed', central: true, sourceIds: [SPEC.sourceId], snapshotIds: [SPEC.documentLocator], locators: [SPEC], numericValues: ['11.5 ligne', '5.67 mm', '21 jewels', '21,600 vph', 'approximately 42 hours', '49°', '−20/+40 s/day'], verificationStatus: 'visually-verified', limitations: ['“Aproximadamente” se conserva.', 'La exactitud declarada no describe toda unidad en cualquier condición.'] }),
  claim({ claimId: 'claim.014j.miyota8215.spec.stop-second', lessonId: 'lesson.miyota8215.winding-setting', sectionId: academyStage4SectionId.focus('lesson.miyota8215.winding-setting'), claim: 'La documentación vigente consultada declara stop second device para el 8215.', claimType: 'user-operation', technicalStatus: 'source-reviewed', central: true, sourceIds: [PRODUCT.sourceId, SPEC.sourceId, MANUAL.sourceId], snapshotIds: [PRODUCT.documentLocator, SPEC.documentLocator, MANUAL.documentLocator], locators: [PRODUCT, SPEC, MANUAL], numericValues: [], verificationStatus: 'visually-verified', limitations: ['No se generaliza a todas las unidades históricas 8215.'] }),
  claim({ claimId: 'claim.014j.miyota8215.manual.crown', lessonId: 'lesson.miyota8215.winding-setting', sectionId: academyStage4SectionId.evidence('lesson.miyota8215.winding-setting'), claim: 'El manual 8215 documenta posición normal, primera posición para fecha y segunda posición para hora.', claimType: 'user-operation', technicalStatus: 'source-reviewed', central: true, sourceIds: [MANUAL.sourceId], snapshotIds: [MANUAL.documentLocator], locators: [MANUAL], numericValues: ['0', '1', '2'], verificationStatus: 'visually-verified', limitations: ['Operaciones externas de usuario; no autoriza servicio.'] }),
  claim({ claimId: 'claim.014j.miyota8215.manual.date-warning', lessonId: 'lesson.miyota8215.calendar', sectionId: academyStage4SectionId.focus('lesson.miyota8215.calendar'), claim: 'El manual vigente del 8215 advierte no ajustar rápidamente la fecha aproximadamente entre las 9 PM y la 1 AM.', claimType: 'user-operation', technicalStatus: 'source-reviewed', central: true, sourceIds: [MANUAL.sourceId], snapshotIds: [MANUAL.documentLocator], locators: [MANUAL], numericValues: ['9 PM', '1 AM'], verificationStatus: 'visually-verified', limitations: ['Se limita al 8215 del manual consultado.', 'No se mezcla con advertencias del 8205.'] }),
  ...[
    ['automatic', 'Oscillating weight', '119-A76'], ['automatic', 'Pawl winding wheel', '141-190'], ['automatic', 'Reduction wheel', '088-120'], ['automatic', 'Ratchet wheel', '059-560'],
    ['barrel-energy', 'Barrel complete', '001-870'], ['train', 'Center wheel and pinion', '012-116'], ['train', 'Third wheel and pinion', '017-760'], ['train', 'Fourth wheel and pinion', '023-940'], ['train', 'Escape wheel and pinion', '032-106'], ['train', 'Center second pinion', '025-670'],
    ['escapement-oscillator', 'Jeweled pallet fork and staff', '035-560'], ['escapement-oscillator', 'Balance with hairspring regulated', '039-102'], ['calendar', 'Date dial', '108-9500'], ['calendar', 'Date dial driving wheel', '103-650'],
  ].map(([lessonSuffix, officialName, partReference]) => claim({
    claimId: `claim.014j.miyota8215.part.${partReference.toLowerCase()}`, lessonId: `lesson.miyota8215.${lessonSuffix}`, sectionId: academyStage4SectionId.evidence(`lesson.miyota8215.${lessonSuffix}`),
    claim: `La parts list vigente identifica “${officialName}” con referencia ${partReference}.`, claimType: 'official-part', technicalStatus: 'source-reviewed', central: false,
    sourceIds: [PARTS.sourceId], snapshotIds: [PARTS.documentLocator], locators: [PARTS], numericValues: [], partReference, verificationStatus: 'visually-verified', limitations: officialLimit,
  })),
  claim({ claimId: 'claim.014j.miyota8215.parts.exploded-not-sequence', lessonId: 'lesson.miyota8215.plan-disassembly', sectionId: academyStage4SectionId.focus('lesson.miyota8215.plan-disassembly'), claim: 'La vista explosionada respalda identidad y posición relativa aproximada; no respalda orden, herramienta, dirección, par o técnica.', claimType: 'structural-relation', technicalStatus: 'source-limited', central: true, sourceIds: [PARTS.sourceId], snapshotIds: [PARTS.documentLocator], locators: [PARTS], numericValues: [], verificationStatus: 'source-limited', limitations: ['Toda secuencia del laboratorio se etiqueta simulation-only.'] }),
  claim({ claimId: 'claim.014j.miyota8215.parts.barrel-bridge-source-needed', lessonId: 'lesson.miyota8215.guided-disassembly', sectionId: academyStage4SectionId.focus('lesson.miyota8215.guided-disassembly'), claim: 'El checkpoint del puente de barrilete representa una dependencia del fixture; cualquier orden físico permanece source-needed.', claimType: 'simulation-boundary', technicalStatus: 'source-needed', central: false, sourceIds: [PARTS.sourceId], snapshotIds: [PARTS.documentLocator], locators: [PARTS], numericValues: [], verificationStatus: 'source-needed', limitations: ['No bloquea la comprensión central de la secuencia virtual.'] }),
  claim({ claimId: 'claim.014j.miyota8215.fixture.g2k2p0', lessonId: 'lesson.miyota8215.architecture', sectionId: academyStage4SectionId.evidence('lesson.miyota8215.architecture'), claim: 'El fixture usa geometría normalizada G2, cinemática K2 y física P0; no representa escala, holgura, desgaste ni comportamiento real.', claimType: 'simulation-boundary', technicalStatus: 'source-limited', central: true, sourceIds: [], snapshotIds: [], locators: [], numericValues: ['G2', 'K2', 'P0'], verificationStatus: 'source-limited', limitations: ['Contrato interno del fixture, no dato MIYOTA.'] }),
]

export function academyStage4ClaimsForLesson(lessonId: string) { return ACADEMY_STAGE_4_CLAIMS.filter((item) => item.lessonId === lessonId) }
