import type { AcademyStage2EditorialArchetype } from '../types'

export interface AcademyStage2EditorialContract {
  whyNow: string
  editorialArchetype: AcademyStage2EditorialArchetype
  topicLabel: string
  checkpointPrompt: string
  checkpointExpectedElements: readonly string[]
  checkpointCommonFailure: string
}

const contract = (value: AcademyStage2EditorialContract) => value

/**
 * Decisiones humanas, por lección. No se derivan del capítulo ni del orden incidental
 * del catálogo: son el contrato editorial que impide volver a una plantilla uniforme.
 */
export const ACADEMY_STAGE_2_EDITORIAL_CONTRACTS: Readonly<Record<string, AcademyStage2EditorialContract>> = {
  'lesson.mechanical.energy': contract({ whyNow: 'Ya reconoces el reloj como sistema; ahora puedes seguir qué se almacena, qué se transmite y qué se pierde antes de estudiar cada órgano.', editorialArchetype: 'mechanism', topicLabel: 'la cadena de energía', checkpointPrompt: '¿Puede quedar energía almacenada aunque las agujas no avancen? Explica qué interfaz podría estar interrumpida.', checkpointExpectedElements: ['energía aún almacenada', 'interfaz concreta interrumpida', 'diferencia entre origen y transmisión'], checkpointCommonFailure: 'Confundir ausencia de indicación con ausencia de energía.' }),
  'lesson.mechanical.barrel': contract({ whyNow: 'Ahora que sabes de dónde sale la energía, puedes estudiar el conjunto que la almacena y la entrega al tren.', editorialArchetype: 'visual-anatomy', topicLabel: 'el barrilete', checkpointPrompt: 'Compara cuerda y marcha: indica qué recibe el giro, qué queda retenido y por dónde sale la energía en cada estado.', checkpointExpectedElements: ['árbol', 'muelle', 'tambor', 'dos estados diferenciados'], checkpointCommonFailure: 'Asignar al árbol y al tambor el mismo papel en ambos estados.' }),
  'lesson.encyclopedia.mechanical-energy-trains.muelle-real-y-barrilete': contract({ whyNow: 'Después de localizar el barrilete, conviene distinguir su estado de carga de la entrega real sin atribuirle una curva universal.', editorialArchetype: 'state-system', topicLabel: 'la carga y descarga del muelle', checkpointPrompt: 'Describe dos estados de reserva distintos y explica por qué la posición de las agujas no basta para distinguirlos.', checkpointExpectedElements: ['estado de reserva', 'entrega de par cualitativa', 'límite de la indicación'], checkpointCommonFailure: 'Tratar un esquema cualitativo como curva medida de un calibre.' }),
  'lesson.encyclopedia.math-physics-metrology.fuerza-par-energia': contract({ whyNow: 'Las magnitudes aparecen ya en la cadena mecánica; este apoyo evita usar energía, par, potencia y velocidad como si fueran sinónimos.', editorialArchetype: 'calculation', topicLabel: 'las magnitudes rotatorias', checkpointPrompt: 'Para una rueda que gira más deprisa, enumera qué puedes afirmar y qué no puedes deducir todavía sobre par, energía y potencia.', checkpointExpectedElements: ['velocidad observada', 'magnitudes no deducibles', 'datos o modelo que faltarían'], checkpointCommonFailure: 'Inferir más par o potencia únicamente a partir de la velocidad.' }),
  'lesson.mechanical.gear-pair': contract({ whyNow: 'Con una entrada de giro identificada, ya puedes estudiar la interfaz mínima que cambia sentido y relación entre dos ruedas.', editorialArchetype: 'calculation', topicLabel: 'una pareja de engranajes', checkpointPrompt: 'Una conductora abstracta de 60 dientes mueve un piñón de 10. Sin calcular pérdidas, explica sentido y cambio ideal de velocidad.', checkpointExpectedElements: ['sentido opuesto', 'relación seis a uno', 'salida ideal más rápida', 'modelo sin pérdidas'], checkpointCommonFailure: 'Sumar dientes o usar el diámetro dibujado como dato.' }),
  'lesson.mechanical.train': contract({ whyNow: 'Después de entender una pareja de engranajes, ya puedes seguir varias etapas sin confundir ruedas que comparten eje.', editorialArchetype: 'mechanism', topicLabel: 'el tren compuesto', checkpointPrompt: 'Recorre un tren de tres ejes y explica qué contactos invierten el sentido y qué ruedas giran solidarias.', checkpointExpectedElements: ['ejes diferenciados', 'interfaces de engrane', 'elementos solidarios', 'sentido final'], checkpointCommonFailure: 'Contar como engrane dos piezas que comparten eje.' }),
  'lesson.encyclopedia.mechanical-energy-trains.relaciones-y-arquitectura-del-tren': contract({ whyNow: 'Una vez seguido el tren, necesitas separar la ruta que llega al escape de la derivación que mueve la indicación.', editorialArchetype: 'visual-anatomy', topicLabel: 'las ramas del tren', checkpointPrompt: 'Dibuja dos salidas desde la transmisión y explica por qué la minutería no sustituye al tren de rodaje.', checkpointExpectedElements: ['ruta al escape', 'rama de indicación', 'funciones diferentes'], checkpointCommonFailure: 'Presentar la minutería como toda la cadena energética.' }),
  'lesson.encyclopedia.math-physics-metrology.toh-contar-tren': contract({ whyNow: 'El camino físico del tren ya está claro; ahora puedes convertir solo sus interfaces activas en una relación comprobable.', editorialArchetype: 'calculation', topicLabel: 'el recuento del tren', checkpointPrompt: 'Escribe dos relaciones consecutivas con un eje intermedio y explica qué término se cancela y qué efecto mecánico no desaparece.', checkpointExpectedElements: ['dos etapas', 'cancelación correcta', 'sentido o geometría aún relevante'], checkpointCommonFailure: 'Cancelar el eje como si dejara de existir físicamente.' }),
  'lesson.encyclopedia.mechanical-energy-trains.toh-engranaje-geometria': contract({ whyNow: 'El cálculo de dientes no basta para que dos ruedas engranen; este apoyo introduce las condiciones geométricas que el cociente no demuestra.', editorialArchetype: 'visual-anatomy', topicLabel: 'la geometría del engrane', checkpointPrompt: 'Explica por qué una relación numérica plausible puede fallar si el paso o la distancia entre centros no son compatibles.', checkpointExpectedElements: ['relación numérica', 'paso compatible', 'distancia entre centros', 'límite del dibujo'], checkpointCommonFailure: 'Aceptar la proximidad visual como prueba de engrane.' }),
  'lesson.mechanical.escapement': contract({ whyNow: 'El escape se estudia después del tren porque recibe su energía, y antes del oscilador porque ambos funcionan como un bucle.', editorialArchetype: 'state-system', topicLabel: 'el ciclo del escape', checkpointPrompt: 'Distingue qué ocurre durante desbloqueo, impulso y caída. Indica qué elemento inicia cada transición.', checkpointExpectedElements: ['desbloqueo iniciado por el oscilador', 'impulso transferido', 'caída hasta el siguiente bloqueo'], checkpointCommonFailure: 'Llamar impulso a cualquier avance de la rueda.' }),
  'lesson.encyclopedia.escapements-chronometry.geometria-del-escape': contract({ whyNow: 'Tras conocer la secuencia, puedes localizar qué superficies hacen posibles el bloqueo, el impulso y la seguridad sin intentar ajustarlas.', editorialArchetype: 'visual-anatomy', topicLabel: 'las interfaces del escape', checkpointPrompt: 'Localiza una cara de bloqueo, una de impulso y un seguro, y explica su función sin proponer una corrección física.', checkpointExpectedElements: ['tres interfaces', 'función de cada una', 'límite no operativo'], checkpointCommonFailure: 'Convertir el diagrama conceptual en una plantilla de ajuste.' }),
  'lesson.encyclopedia.escapements-chronometry.toh-escape-fases': contract({ whyNow: 'Con la anatomía localizada, puedes recorrer el ciclo completo y separar estados estables de transiciones.', editorialArchetype: 'state-system', topicLabel: 'las fases del escape', checkpointPrompt: 'Ordena bloqueo, desbloqueo, impulso y caída; para cada transición identifica contacto, movimiento permitido y transferencia de energía.', checkpointExpectedElements: ['orden completo', 'contactos', 'movimiento permitido', 'energía'], checkpointCommonFailure: 'Memorizar nombres sin indicar qué cambia entre fases.' }),
  'lesson.advanced.escapement-compare': contract({ whyNow: 'La comparación es útil solo después de dominar las funciones del escape básico; esta rama muestra qué analogías se pueden transferir y cuáles no.', editorialArchetype: 'comparison', topicLabel: 'familias de escapes', checkpointPrompt: 'Compara dos familias mediante bloqueo, impulso y seguridad, y señala una diferencia que impida tratarlas como equivalentes.', checkpointExpectedElements: ['criterios comunes', 'dos casos', 'diferencia no transferible', 'fuente pendiente cuando corresponda'], checkpointCommonFailure: 'Trasladar piezas, tolerancias o lubricación entre familias.' }),
  'lesson.mechanical.oscillator': contract({ whyNow: 'Después de ver cómo el escape libera e impulsa, puedes separar la referencia temporal que aportan volante y espiral.', editorialArchetype: 'mechanism', topicLabel: 'el oscilador', checkpointPrompt: 'Compara dos movimientos con la misma frecuencia y amplitudes distintas; explica qué observación cambia y cuál permanece.', checkpointExpectedElements: ['frecuencia igual', 'amplitud distinta', 'periodo o ciclos', 'posición no suficiente'], checkpointCommonFailure: 'Usar amplitud, frecuencia y rapidez como sinónimos.' }),
  'lesson.mechanical.escape-oscillator': contract({ whyNow: 'Ya conoces ambos órganos por separado; ahora puedes cerrar el bucle entre energía de impulso y momento de liberación.', editorialArchetype: 'mechanism', topicLabel: 'el bucle regulador', checkpointPrompt: 'Explica dos direcciones de la interacción: qué entrega el escape y qué devuelve el oscilador al ciclo.', checkpointExpectedElements: ['impulso hacia el oscilador', 'temporización hacia el escape', 'pérdidas'], checkpointCommonFailure: 'Dibujar una cadena de una sola dirección.' }),
  'lesson.encyclopedia.escapements-chronometry.volante-y-espiral': contract({ whyNow: 'Con el bucle funcional entendido, puedes localizar los apoyos y fijaciones que permiten al órgano regulador oscilar.', editorialArchetype: 'visual-anatomy', topicLabel: 'volante y espiral', checkpointPrompt: 'Localiza volante, eje, pivotes, espiral, virola y pitón, y asigna a cada uno una función observable.', checkpointExpectedElements: ['componentes localizados', 'apoyo', 'inercia', 'retorno y fijación'], checkpointCommonFailure: 'Inferir un ajuste de marcha a partir de la anatomía.' }),
  'lesson.encyclopedia.math-physics-metrology.oscilacion-amortiguamiento': contract({ whyNow: 'El comportamiento cualitativo ya está visible; este apoyo permite interpretar periodo, amplitud y pérdidas sin publicar fórmulas no verificadas.', editorialArchetype: 'calculation', topicLabel: 'la oscilación amortiguada', checkpointPrompt: 'Describe qué cambia en una oscilación amortiguada y qué dato adicional necesitarías para cuantificar ese cambio.', checkpointExpectedElements: ['amplitud decreciente', 'frecuencia diferenciada', 'dato o modelo faltante'], checkpointCommonFailure: 'Presentar una tendencia cualitativa como medición de marcha.' }),
  'lesson.mechanical.motion-works': contract({ whyNow: 'Cuando el movimiento regulado ya está explicado, puedes seguir la rama que convierte ese giro en minutos y horas visibles.', editorialArchetype: 'visual-anatomy', topicLabel: 'la minutería', checkpointPrompt: 'Separa la entrada del movimiento, la relación de minutos y la relación de horas, e indica qué interfaz permite la puesta en hora.', checkpointExpectedElements: ['entrada', 'cañón de minutos', 'rueda de horas', 'interfaz de ajuste'], checkpointCommonFailure: 'Confundir la rama de indicación con el tren que llega al escape.' }),
  'lesson.mechanical.keyless': contract({ whyNow: 'Después de conocer la indicación, puedes estudiar cómo corona y tija seleccionan entre cargar el muelle y mover las agujas.', editorialArchetype: 'state-system', topicLabel: 'el sistema de mando', checkpointPrompt: 'Explica por qué la misma rotación de corona puede producir cuerda o movimiento de agujas según la posición de la tija.', checkpointExpectedElements: ['entrada común', 'posición axial', 'dos rutas', 'resultado de cada estado'], checkpointCommonFailure: 'Atribuir el cambio de función al sentido de giro sin considerar la selección.' }),
  'lesson.encyclopedia.mechanical-energy-trains.minuteria-y-puesta-en-hora': contract({ whyNow: 'Con mando y minutería separados, este apoyo permite seguir la transferencia completa desde la corona hasta las agujas.', editorialArchetype: 'mechanism', topicLabel: 'la puesta en hora', checkpointPrompt: 'Recorre la ruta de puesta en hora y distingue selección, transmisión, fricción controlada e indicación.', checkpointExpectedElements: ['selección', 'ruta mecánica', 'fricción', 'salida en agujas'], checkpointCommonFailure: 'Suponer que todas las arquitecturas usan las mismas piezas o sentidos.' }),
  'lesson.mechanical.automatic-calendar': contract({ whyNow: 'La cadena básica ya está completa; ahora puedes situar automático y calendario como ampliaciones de entrada y salida.', editorialArchetype: 'comparison', topicLabel: 'las ampliaciones del sistema', checkpointPrompt: 'Compara qué añade el automático a la entrada y qué añade el calendario a la salida sin mezclarlos con la regulación.', checkpointExpectedElements: ['entrada automática', 'salida de calendario', 'cadena básica conservada', 'regulación separada'], checkpointCommonFailure: 'Tratar ambas complicaciones como parte del escape.' }),
  'lesson.encyclopedia.complications.automatico-y-reserva': contract({ whyNow: 'Una vez situada la ampliación de entrada, puedes seguir cómo el movimiento del usuario llega al muelle y qué no revela la indicación instantánea.', editorialArchetype: 'mechanism', topicLabel: 'la carga automática', checkpointPrompt: 'Sigue usuario, masa oscilante, reducción y muelle; señala dos prestaciones que el esquema no permite cuantificar.', checkpointExpectedElements: ['ruta funcional completa', 'reserva o eficiencia no cuantificada', 'sentido no universal'], checkpointCommonFailure: 'Deducir eficiencia, reserva o sentido de carga del diagrama.' }),
  'lesson.encyclopedia.complications.calendarios': contract({ whyNow: 'Después de entender la indicación continua, puedes estudiar cómo un tren lento produce un cambio discreto y lo mantiene estable.', editorialArchetype: 'state-system', topicLabel: 'el calendario simple', checkpointPrompt: 'Separa arrastre, liberación, avance y retención en un cambio de fecha, indicando qué función cumple cada elemento.', checkpointExpectedElements: ['arrastre', 'liberación', 'avance discreto', 'retención'], checkpointCommonFailure: 'Convertir la secuencia conceptual en una zona horaria segura universal.' }),
  'lesson.advanced.calendars': contract({ whyNow: 'La fecha simple sirve de referencia; esta rama muestra qué estados adicionales exigen los calendarios complejos y qué datos siguen dependiendo del calibre.', editorialArchetype: 'advanced-reference', topicLabel: 'los calendarios avanzados', checkpointPrompt: 'Compara una fecha simple con un calendario de ciclo mayor e identifica el estado adicional que debe conservarse.', checkpointExpectedElements: ['caso simple', 'caso avanzado', 'estado adicional', 'límite de transferencia'], checkpointCommonFailure: 'Generalizar una arquitectura o un procedimiento de corrección.' }),
  'lesson.advanced.chronograph-control': contract({ whyNow: 'Los sistemas de estados del calendario ofrecen un contraste útil para estudiar mando, memoria mecánica e indicación sin confundir arquitecturas.', editorialArchetype: 'advanced-reference', topicLabel: 'el control del cronógrafo', checkpointPrompt: 'Distingue entrada de mando, estado retenido y salida indicada; después señala qué comparación con un calendario deja de ser válida.', checkpointExpectedElements: ['mando', 'estado', 'indicación', 'límite de la analogía'], checkpointCommonFailure: 'Usar una analogía de estados como descripción de un mecanismo concreto.' }),
}

export function academyStage2EditorialContract(lessonId: string): AcademyStage2EditorialContract {
  const result = ACADEMY_STAGE_2_EDITORIAL_CONTRACTS[lessonId]
  if (!result) throw new Error(`Falta el contrato editorial explícito de ${lessonId}.`)
  return result
}
