export function polishStudentCopy(value) {
  const glossaryTokens = []
  const protectedValue = value.replace(/\{\{term:[^}]+\}\}/gu, (token) => {
    const index = glossaryTokens.push(token) - 1
    return `\uE000${index}\uE001`
  })
  const polished = protectedValue
    .replace(/^Identificar y explicar .+? con fuentes\.$/giu, 'Explicar el objetivo de la lección y justificar cada conclusión con la fuente adecuada.')
    .replace(/^(.+?) con un modelo estructural, fuentes, operaciones y límites declarados\.$/giu, '$1 se estudia sobre el modelo estructural del calibre; cada operación conserva su fuente, su alcance y sus límites.')
    .replace(/\b((?:Identificar|Leer|Distinguir|Reconocer|Explicar|Desmontar|Inspeccionar|Montar|Verificar|Preparar|Documentar|Formular|Practicar|Relacionar|Conservar|Diagnosticar)[^.!?\n]{0,100}?) con un modelo estructural, fuentes, operaciones y límites declarados\./giu, '$1 se estudia sobre el modelo estructural del calibre; cada operación conserva su fuente, su alcance y sus límites.')
    .replace(/([.!?]\s+)[^.!?]{2,120}? con un modelo estructural, fuentes, operaciones y límites declarados\./giu, '$1En este contexto se usa un modelo estructural del calibre; cada operación conserva su fuente, su alcance y sus límites.')
    .replace(/En documentación inglesa, contrasta \*\*([^*]+)\*\* con \*\*([^*]+)\*\*\./giu, 'Usa **$1** como término principal (en la documentación inglesa: **$2**).')
    .replace(/^Entender (.+?) permite razonar sobre el reloj completo y no memorizar piezas aisladas\.$/giu, 'Este concepto permite relacionar «$1» con el funcionamiento del reloj completo, en lugar de memorizar piezas aisladas.')
    .replace(/^Dominar (.+?) permite actuar de forma trazable, reversible y segura\.$/giu, 'Esta habilidad permite aplicar «$1» de forma documentada, reversible y segura.')
    .replace(/^Reconocer (.+?) permite seguir la causa y el efecto entre subsistemas\.$/giu, 'Este subsistema permite seguir causas y efectos al estudiar «$1».')
    .replace(/^Explicar qué recibe y qué entrega (.+?) dentro de la cadena funcional\.$/giu, 'Explicar la entrada, la relación y el resultado observable asociados a «$1» dentro de la cadena funcional.')
    .replace(/^Predecir qué cambia si se interrumpe su relación con el subsistema (.+?)\.$/giu, 'Predecir qué cambiaría al interrumpir una interfaz del subsistema $1.')
    .replace(/^(.+?) se reconoce por su posición relativa, sus apoyos y sus interfaces dentro de (.+?)\. /giu, 'Para reconocer «$1», examina su posición relativa, sus apoyos y sus interfaces dentro de $2. ')
    .replace(/¿Qué relación\s+(?:remove-before|retirar antes de|de retirada previa)\s+justifica cada retirada\?/giu, '¿Qué dependencia obliga a retirar una pieza antes que otra?')
    .replace(/\brelación\s+remove-before\b/giu, 'dependencia de retirada previa')
    .replace(/\b(?:assembly\s*[–—-]\s*disassembly|assembly\s+and\s+disassembly)\s+charts?\b/giu, 'esquema de montaje y desmontaje')
    .replace(/\bcharts? web\b/giu, 'esquemas web')
    .replace(/\bparts list and exploded view\b/giu, 'lista de piezas y vista explosionada')
    .replace(/\bparts lists?\b/giu, 'lista de piezas')
    .replace(/\binstruction manuals?\b/giu, 'manual de instrucciones')
    .replace(/\bspecifications?\b/giu, (match) => match.toLocaleLowerCase('en-US').endsWith('s') ? 'especificaciones' : 'especificación')
    .replace(/\bcomparar snapshots? de (?:la )?lista de piezas\b/giu, 'comparar versiones verificadas de la lista de piezas')
    .replace(/\bentre snapshots? de (?:la )?lista de piezas\b/giu, 'entre las versiones verificadas de la lista de piezas')
    .replace(/\bsnapshot oficial\b/giu, 'copia documental oficial verificada')
    .replace(/\bsnapshot anterior\b/giu, 'versión documental anterior')
    .replace(/\bsnapshot vigente\b/giu, 'versión documental vigente')
    .replace(/\bsnapshot utilizado\b/giu, 'versión documental utilizada')
    .replace(/\bcita el snapshot\b/giu, 'cita la versión documental')
    .replace(/dominio retenido/giu, 'consolidación del aprendizaje')
    .replace(/R2\s*\/\s*G2\s*\/\s*K2\s*\/\s*P0/giu, 'ensamblaje estructural con geometría reconstruida y secuencia educativa, sin simulación física')
    .replace(/G1\s*\/\s*K2\s*\/\s*P0/giu, 'geometría conceptual y secuencia educativa, sin simulación física')
    .replace(/G2\s*\/\s*K2\s*\/\s*P0/giu, 'geometría estructural reconstruida y secuencia educativa, sin simulación física')
    .replace(/R2\s*\/\s*K2/giu, 'ensamblaje estructural con secuencia educativa')
    .replace(/\bfixture\s+R2\s+estructural\b/giu, 'modelo didáctico con nivel de ensamblaje estructural')
    .replace(/\bfixture\s+R2\b/giu, 'modelo didáctico con nivel de ensamblaje estructural')
    .replace(/\bR2\s+estructural\b/giu, 'nivel de ensamblaje estructural')
    .replace(/\bnivel de ensamblaje estructural\s+estructural\b/giu, 'nivel de ensamblaje estructural')
    .replace(/\bmodelo didáctico nivel de ensamblaje estructural\b/giu, 'modelo didáctico con nivel de ensamblaje estructural')
    .replace(/G\s*\/\s*K\s*\/\s*P/giu, 'ficha técnica de fidelidad')
    .replace(/\bR0\b/gu, 'nivel de referencia documental')
    .replace(/\bR1\b/gu, 'nivel de envolvente oficial')
    .replace(/\bR2\b/gu, 'nivel de ensamblaje estructural')
    .replace(/\bR3\b/gu, 'nivel de reconstrucción visual')
    .replace(/\bR4\b/gu, 'nivel basado en una unidad física medida')
    .replace(/\bG0\b/gu, 'sin geometría representada')
    .replace(/\bG1\b/gu, 'geometría conceptual')
    .replace(/\bG2\b/gu, 'geometría estructural reconstruida')
    .replace(/\bG3\b/gu, 'geometría contrastada con mediciones')
    .replace(/\bK0\b/gu, 'sin cinemática representada')
    .replace(/\bK1\b/gu, 'direcciones de movimiento educativas')
    .replace(/\bK2\b/gu, 'secuencia cinemática educativa')
    .replace(/\bK3\b/gu, 'cinemática contrastada con mediciones')
    .replace(/\bP0\b/gu, 'sin simulación física')
    .replace(/\bP1\b/gu, 'comportamiento físico cualitativo')
    .replace(/\bP2\b/gu, 'comportamiento físico calibrado')
    .replace(/\bP3\b/gu, 'comportamiento físico contrastado con mediciones')
    .replace(/\b[RGKP]\d\b/gu, 'nivel de fidelidad indicado en la ficha técnica')
    .replace(/\bG,\s*K\s*o\s*P\b/gu, 'cada dimensión de fidelidad')
    .replace(/\bfixtures\b/giu, 'modelos didácticos')
    .replace(/\bfixture\b/giu, 'modelo didáctico')
    .replace(/\bruntime\b/giu, 'entorno de práctica')
    .replace(/\bWatchProject\b/gu, 'proyecto técnico')
    .replace(/\bsnapshots\b/giu, 'estados iniciales guardados')
    .replace(/\bsnapshot\b/giu, 'estado inicial guardado')
    .replace(/\bclaims?\b/giu, 'afirmaciones')
    .replace(/\bretained\b/giu, 'consolidado')
    .replace(/\bledger\b/giu, 'registro técnico')
    .replace(/\bremove-before\b/giu, 'retirada previa')
    .replace(/\badd-after\b/giu, 'montaje posterior')
    .replace(/\bpart-of\b/giu, 'pertenencia al conjunto')
    .replace(/\bfastened-by\b/giu, 'unión mediante')
    .replace(/\bunknowns\b/giu, 'datos pendientes')
    .replace(/\bunknown\b/giu, 'dato pendiente')
    .replace(/\bnot-verified\b/giu, 'no verificado')
    .replace(/\bplanned-only\b/giu, 'solo planificado')
    .replace(/\brollbacks?\b/giu, 'reversión segura')
    .replace(/\bstop conditions\b/giu, 'condiciones de parada')
    .replace(/\bstop condition\b/giu, 'condición de parada')
    .replace(/\bsource-needed\b/giu, 'fuente necesaria')
    .replace(/\bsource-limited\b/giu, 'limitado por las fuentes')
    .replace(/\bsource-reviewed\b/giu, 'revisado contra las fuentes')
    .replace(/\bnot-reviewed\b/giu, 'pendiente de revisión')
    .replace(/\bdocumentally-compatible\b/giu, 'compatible documentalmente')
    .replace(/\bdimensionally-defined\b/giu, 'definido dimensionalmente')
    .replace(/\bprimary-source\b/giu, 'fuente primaria')
    .replace(/\bsecondary-reference\b/giu, 'referencia secundaria')
    .replace(/(?<!referencias geométricas \()\bdatums\b/giu, 'referencias geométricas (datums)')
    .replace(/(?<!referencia geométrica \()\bdatum\b/giu, 'referencia geométrica (datum)')
    .replace(/\bsupplier\b/giu, 'proveedor')
    .replace(/\bdrawing\b/giu, 'plano')
    .replace(/\bfits\b/giu, 'ajustes')
    .replace(/\bfit\b/giu, 'ajuste')
    .replace(/\bstack\b/giu, 'apilado')
    .replace(/\bIDs\b/gu, 'identidades de pieza')
    .replace(/\bID\b/gu, 'identidad de pieza')
    .replace(/\bcheckpoints\b/giu, 'puntos de control')
    .replace(/\bcheckpoint\b/giu, 'punto de control')
    .replace(/\bviewport\b/giu, 'vista del modelo')
    .replace(/\boverlays\b/giu, 'capas informativas')
    .replace(/\boverlay\b/giu, 'capa informativa')
    .replace(/\bconceptual[- ]causal\b/giu, 'relaciones de causa y efecto')
    .replace(/\bhorology[- ]foundations\b/giu, 'fundamentos de relojería')
    .replace(/\bmotion[- ]works\b/giu, 'minutería')
    .replace(/\bpower[- ]source\b/giu, 'fuente de energía')
    .replace(/\belectronic[- ]control\b/giu, 'control electrónico')
    .replace(/\bquartz[- ]resonator\b/giu, 'resonador de cuarzo')
    .replace(/\bstepper[- ]rotor\b/giu, 'rotor paso a paso')
    .replace(/\bautomatic[- ]winding\b/giu, 'carga automática')
    .replace(/\bsystem[- ]overview\b/giu, 'visión del sistema completo')
    .replace(/\bfinal[- ]project\b/giu, 'proyecto final')
    .replace(/\bkeyless\b/giu, 'cuerda y puesta en hora')
  return polished.replace(/\uE000(\d+)\uE001/gu, (_match, index) => glossaryTokens[Number(index)] ?? _match)
}

export const LEARNER_FACING_KEYS = new Set([
  'accessibleLabel', 'animations', 'arrows', 'bodyMarkdown', 'cameraIntent', 'causalQuestion', 'colorIndependentCues',
  'content', 'context', 'correctExplanation', 'correction', 'definitionMarkdown', 'deliberatePractice', 'description', 'diagnosis', 'energyFlow',
  'errorSignals', 'evidence', 'feedback', 'forbiddenClaims', 'incorrectDiagnosis', 'instruction', 'instructionMarkdown',
  'keyboardActions', 'label', 'labels', 'limitations', 'markdown', 'method', 'narrative', 'learnerExpression', 'nextObservation',
  'notePrompt', 'observableActions', 'observableResult', 'observableSignals', 'outcome', 'physicalBoundary', 'plainLanguage',
  'objective', 'objectives', 'prompt', 'promptMarkdown', 'promptStarters', 'purpose', 'question', 'readinessCriteria', 'reason', 'restoration', 'revision', 'rotationDirections',
  'simpleDefinition', 'sourceStatement', 'successCriteria', 'successCriterion', 'summary', 'technicalDefinition',
  'supportedClaim', 'synonyms', 'technicalLanguage', 'term', 'terms', 'textualAlternative', 'timelineIntent', 'title', 'transferPrompt', 'unknownData',
  'userInteraction', 'reducedMotionAlternative', 'whyItMatters',
])

export function polishLearnerFacing(value, learnerFacing = false) {
  if (typeof value === 'string') return learnerFacing ? polishStudentCopy(value) : value
  if (Array.isArray(value)) return value.map((item) => polishLearnerFacing(item, learnerFacing))
  if (!value || typeof value !== 'object') return value
  return Object.fromEntries(Object.entries(value).map(([key, item]) => [
    key,
    key === 'en' ? item : polishLearnerFacing(item, learnerFacing || LEARNER_FACING_KEYS.has(key)),
  ]))
}
