const C = (term, definition, en = term) => ({ term, definition, en })
const L = (x) => ({ ...x, sourceIds: x.sources })

export const CRAFT_ROUTES = [
  {
    key: 'cases-water', id: 'route.encyclopedia.cases-water', title: 'Caja, cristales, coronas y estanqueidad',
    purpose: 'Comprender la envolvente como sistema estructural, de uso y sellado, y validar su intervención con pruebas proporcionadas.',
    difficulty: 'intermediate', entryPolicy: 'requires-workshop-tools-materials', lessons: [
      L({ slug: 'arquitectura-de-caja', title: 'Arquitectura de caja y encaje del movimiento', question: '¿Qué interfaces convierten movimiento, esfera, agujas y caja en un reloj utilizable?',
        core: 'Carrura, fondo, bisel, cristal, corona, tubo, juntas, aro y fijaciones sitúan y protegen el movimiento. El encaje depende de diámetro, altura, posición de tija, apoyos, tolerancias y acceso de servicio. Una envolvente visual no demuestra retención, resistencia ni sellado.', subsystem: 'case',
        sources: ['source.private.daniels.casemaking', 'source.official.miyota.2035', 'source.official.miyota.8215'],
        concepts: [C('carrura', 'Cuerpo principal de la caja que integra alojamientos, asas y referencias de ensamblaje.', 'case middle'), C('aro de encaje', 'Componente que posiciona y retiene el movimiento respecto a caja y esfera.', 'movement holder'), C('línea de tija', 'Relación tridimensional entre eje de tija del movimiento, tubo y corona.', 'stem line')],
        sequence: ['definir movimiento y esfera', 'establecer referencias', 'dimensionar encaje', 'alinear tija', 'retener axial y radialmente', 'cerrar caja y verificar'],
        quantities: ['diámetro de encaje', 'altura total', 'posición y altura de tija', 'holgura de agujas', 'espesor de pared'],
        caseStudy: 'Un calibre entra en el diámetro de caja pero la corona fuerza la tija hacia abajo. El problema no se resuelve limando el aro: deben compararse altura de tija, espesor de esfera, apoyo del movimiento, tubo y longitud de corona con una cadena de cotas.',
        failures: ['Declarar compatibilidad por diámetro exterior.', 'Usar la tija como elemento que centra o retiene el movimiento.'], misconception: { expression: 'Si el movimiento cabe dentro, la caja es compatible', correction: 'deben coincidir referencias, tija, alturas, fijación, agujas, esfera, acceso y requisitos de protección.' },
        transfer: 'Construye una interfaz de control para alojar un movimiento adquirido: datos oficiales, cotas por medir, tolerancias funcionales y pruebas físicas.',
      }),
      L({ slug: 'corona-tubo-y-tija', title: 'Corona, tubo, tija y órganos de mando', question: '¿Cómo se transmiten fuerza y selección a través de una abertura que también debe proteger?',
        core: 'La corona proporciona agarre, la tija transmite par y desplazamiento, y el tubo guía y recibe sellado o rosca. Longitud, rosca, concentricidad, recorrido y compresión de junta se condicionan. Una corona roscada protege solo si rosca, asiento, junta y usuario trabajan dentro del diseño.', subsystem: 'case-controls',
        sources: ['source.private.daniels.casemaking', 'source.institutional.awci.standards', 'source.external.watchguy-manuals'],
        concepts: [C('tubo de corona', 'Elemento de caja que guía la tija y ofrece superficie de sellado o roscado.', 'crown tube'), C('longitud funcional de tija', 'Longitud que permite posiciones y engranes correctos sin precarga ni juego excesivo.', 'functional stem length'), C('corona roscada', 'Corona que se fija axialmente por rosca y comprime un sistema de sellado diseñado.', 'screw-down crown')],
        sequence: ['usuario gira o extrae corona', 'corona transmite a tija', 'tubo guía y sella', 'tija selecciona mecanismo', 'junta se comprime al cerrar', 'caja recupera barrera'],
        quantities: ['diámetro y paso de rosca', 'longitud de tija', 'recorrido axial', 'compresión de junta', 'par de cierre'],
        caseStudy: 'Una corona cierra la rosca antes de que su junta contacte. Apretar más solo carga la rosca. Se comparan hombros, longitud de tija, asiento, junta y tubo; el sellado se valida con prueba, no por sensación.',
        failures: ['Cortar tija sin medir todas las posiciones.', 'Aplicar adhesivo a tubo sin estudiar servicio y compatibilidad.'], misconception: { expression: 'Una corona roscada garantiza estanqueidad', correction: 'solo contribuye si geometría, juntas, superficies, montaje y prueba del conjunto son conformes.' },
        transfer: 'Redacta el proceso reversible de ajuste de una tija de práctica con cotas, incrementos, criterio de parada y verificación de posiciones.',
      }),
      L({ slug: 'cristales-y-biseles', title: 'Cristales, biseles, tensiones y adhesivos', question: '¿Cómo se retiene un cristal sin dañarlo y qué cambia entre ajuste, junta y adhesivo?',
        core: 'Cristales minerales, zafiro y polímeros difieren en rigidez, dureza, fractura y expansión. Pueden retenerse por interferencia, junta, bisel, aro o adhesivo. Perfil, limpieza, apoyo, concentricidad y carga de prensa son críticos; una cota nominal aislada no define la interferencia real.', subsystem: 'case-crystal',
        sources: ['source.private.daniels.casemaking', 'source.institutional.awci.standards', 'source.external.ashton-tracy'],
        concepts: [C('ajuste por interferencia', 'Unión donde el elemento insertado supera ligeramente el alojamiento y genera presión de contacto.', 'interference fit'), C('bisel', 'Elemento anular que enmarca o retiene el cristal y puede cumplir funciones de lectura.', 'bezel'), C('tensión residual', 'Esfuerzo interno que permanece tras prensado, mecanizado, curado o cambio térmico.', 'residual stress')],
        sequence: ['identificar material y retención', 'inspeccionar alojamiento', 'medir geometría', 'preparar junta o adhesivo', 'aplicar carga alineada', 'verificar asiento y sellado'],
        quantities: ['diámetros', 'interferencia', 'espesor', 'planitud', 'fuerza de prensado y curado'],
        caseStudy: 'Un zafiro parece asentado pero tiene carga de borde por alojamiento inclinado. Puede sobrevivir al montaje y fracturarse después. Se inspeccionan apoyo, concentricidad, altura uniforme y proceso antes de prueba de presión.',
        failures: ['Prensar usando el centro del cristal como apoyo.', 'Sustituir adhesivo sin controlar espesor y compatibilidad.'], misconception: { expression: 'El zafiro no se raya, así que es el cristal más resistente en todo sentido', correction: 'dureza al rayado no equivale a tenacidad, tolerancia a impacto, flexibilidad ni facilidad de servicio.' },
        transfer: 'Compara acrílico, mineral y zafiro para un reloj de vestir, herramienta y prototipo; separa estética, rayado, impacto, sellado y reparación.',
      }),
      L({ slug: 'juntas-y-sellado', title: 'Juntas, compresión y rutas de fuga', question: '¿Cómo crea una junta una barrera y por qué una junta nueva puede seguir fugando?',
        core: 'Una junta funciona al deformarse contra superficies compatibles y mantener presión de contacto frente a tolerancias, presión, temperatura y movimiento. Sección, material, dureza, compresión, acabado, ranura y lubricación de montaje interactúan. Cada abertura crea una ruta de fuga independiente.', subsystem: 'water-resistance',
        sources: ['source.institutional.awci.standards', 'source.external.dean-dk', 'source.encyclopedia.original-synthesis'],
        concepts: [C('compresión de junta', 'Reducción controlada de la sección del elastómero al cerrar la interfaz.', 'gasket compression'), C('ruta de fuga', 'Camino continuo por el que un fluido puede atravesar una barrera.', 'leak path'), C('set de compresión', 'Deformación permanente que reduce recuperación del elastómero tras carga prolongada.', 'compression set')],
        sequence: ['presión actúa', 'fluido busca discontinuidad', 'junta mantiene contacto', 'superficie y ranura distribuyen carga', 'material recupera', 'barrera se conserva o fuga'],
        quantities: ['sección de junta', 'porcentaje de compresión', 'dureza', 'rugosidad de asiento', 'diferencia de presión'],
        caseStudy: 'Se cambia la junta de fondo y el reloj falla. Las causas incluyen sección incorrecta, torsión, pelo, corrosión del asiento, deformación de fondo o fuga por corona/cristal. Una pieza nueva no identifica la ruta.',
        failures: ['Estirar una junta sin comprobar sección final.', 'Aplicar grasa para rellenar daño geométrico.'], misconception: { expression: 'Cambiar todas las juntas devuelve automáticamente la estanqueidad original', correction: 'el resultado depende de materiales, superficies, geometría, montaje y prueba de cada ruta.' },
        transfer: 'Dibuja todas las rutas de fuga de una caja y asigna inspección, componente, modo de fallo y prueba discriminante.',
      }),
      L({ slug: 'pruebas-de-presion', title: 'Pruebas de presión, condensación y límites de seguridad', question: '¿Qué demuestra cada prueba de estanqueidad y cuándo no debe realizarse?',
        core: 'Pruebas secas detectan deformación o flujo sin mojar; pruebas húmedas pueden localizar burbujas bajo protocolos seguros; condensación explora ingreso o humedad con límites. Presión positiva, vacío, duración y temperatura someten interfaces de modo distinto. Ninguna prueba convierte un reloj envejecido en apto para buceo sin criterio.', subsystem: 'water-resistance-validation',
        sources: ['source.institutional.awci.standards', 'source.external.dean-dk', 'source.encyclopedia.original-synthesis'],
        concepts: [C('prueba seca', 'Ensayo de hermeticidad sin inmersión que infiere fuga mediante deformación o flujo.', 'dry pressure test'), C('presión diferencial', 'Diferencia entre presión exterior e interior que carga la caja y sus sellos.', 'differential pressure'), C('criterio de prueba', 'Nivel, duración, secuencia y aceptación definidos según diseño y riesgo.', 'test criterion')],
        sequence: ['evaluar aptitud', 'definir presión y método', 'inspeccionar y cerrar', 'aplicar carga gradual', 'observar respuesta', 'despresurizar y documentar'],
        quantities: ['bar o pascal', 'vacío', 'tiempo', 'deformación', 'tasa de fuga'],
        caseStudy: 'Una caja vintage con cristal agrietado no se presuriza para “ver qué pasa”. La inspección ya indica incapacidad y la prueba puede agravar daño. El criterio de no prueba es un resultado técnico, no una omisión.',
        failures: ['Abrir cámara o sumergir con presión interna incontrolada.', 'Aplicar presión nominal histórica sin conocer estado actual.'], misconception: { expression: 'Pasar una prueba puntual garantiza uso acuático indefinido', correction: 'la conformidad corresponde a método, presión, estado y momento declarados; envejecimiento y uso cambian el sistema.' },
        transfer: 'Define protocolos diferentes para reloj moderno mantenido, prototipo y pieza histórica, incluyendo cuándo detenerse y qué afirmación final es lícita.',
      }),
      L({ slug: 'brazaletes-y-restauracion-de-caja', title: 'Brazaletes, cierres y restauración responsable de caja', question: '¿Cómo se restaura función y apariencia sin borrar geometría, identidad o historia?',
        core: 'Asas, pasadores, eslabones y cierre transmiten cargas repetidas y deben inspeccionarse como sistema de seguridad. En caja, pulido y relleno eliminan material y alteran aristas, planos, grabados y tolerancias. La intervención se decide entre conservación, estabilización, reparación funcional y restauración estética.', subsystem: 'case-restoration',
        sources: ['source.external.ashton-tracy', 'source.external.naked-watchmaker', 'source.private.daniels.finishing-metals'],
        concepts: [C('conservación', 'Intervención mínima destinada a estabilizar y preservar material e información existentes.', 'conservation'), C('geometría de arista', 'Relación de planos, radios y líneas que define forma y lectura visual de la caja.', 'edge geometry'), C('pasador de seguridad', 'Elemento de unión cuya integridad evita separación de correa o brazalete.', 'security spring bar')],
        sequence: ['documentar geometría', 'evaluar carga y desgaste', 'definir objetivo', 'proteger referencias', 'intervenir mínimamente', 'verificar cierre y registrar pérdida'],
        quantities: ['espesor remanente', 'holgura de eslabón', 'diámetro de pasador', 'profundidad de daño', 'radio de arista'],
        caseStudy: 'Una caja muy pulida brilla pero sus asas son asimétricas y el fondo ya no apoya igual. Una nueva restauración no puede recuperar material sin un plan aditivo y referencias fiables; quizá la decisión correcta sea conservar y estabilizar.',
        failures: ['Pulir hasta eliminar el arañazo más profundo.', 'Reutilizar pasadores deformados por apariencia aceptable.'], misconception: { expression: 'Restaurar significa dejar la caja como nueva', correction: 'puede significar preservar, estabilizar o recuperar función; borrar material e historia no es neutral ni reversible.' },
        transfer: 'Redacta tres propuestas para la misma caja —conservación, servicio y restauración— con pérdidas, riesgos, pruebas y consentimiento necesarios.',
      }),
    ],
  },
  {
    key: 'micromechanics', id: 'route.encyclopedia.micromechanics', title: 'Micromecánica y fabricación de componentes',
    purpose: 'Desarrollar desde medición y sujeción hasta ejes, ruedas, tornillos, muelles, platinas y rubíes con procesos verificables.',
    difficulty: 'advanced', entryPolicy: 'requires-math-physics-metrology-and-tools', lessons: [
      L({ slug: 'trazado-medicion-y-sujecion', title: 'Trazado, referencias, medición y sujeción', question: '¿Cómo se conserva una referencia geométrica a través de varias operaciones microscópicas?',
        core: 'Fabricar comienza eligiendo datums y orden de operaciones. Trazado, taladro, torneado y fresado deben referirse a superficies controladas. La sujeción aporta rigidez pero puede deformar o marcar. Medir entre operaciones crea realimentación y reserva material para acabado.', subsystem: 'manufacturing-planning',
        sources: ['source.private.daniels.workshop-equipment', 'source.private.daniels.turning', 'source.private.vba-uhrentechnik'],
        concepts: [C('datum', 'Referencia geométrica adoptada para ubicar y orientar otras características.', 'datum'), C('cadena de proceso', 'Secuencia de operaciones, referencias y controles que transforma materia en pieza.', 'process chain'), C('sobrematerial', 'Material deliberadamente conservado para corregir forma y alcanzar acabado final.', 'machining allowance')],
        sequence: ['definir función y datum', 'preparar material', 'sujetar sin deformar', 'generar referencia', 'mecanizar dejando sobrematerial', 'medir y acabar'],
        quantities: ['concentricidad', 'planitud', 'paralelismo', 'sobrematerial', 'fuerza de sujeción'],
        caseStudy: 'Una placa se taladra desde bordes sin escuadrar y los centros cumplen entre sí pero no con el contorno final. El fallo nació al elegir referencias inestables, no al taladrar. Reordenar el proceso crea datums antes de características críticas.',
        failures: ['Cambiar de sujeción sin registrar referencia.', 'Apretar una pieza delgada hasta deformarla durante la medida.'], misconception: { expression: 'Una buena máquina corrige un mal plan de proceso', correction: 'sin referencias, orden, sujeción y controles coherentes la precisión de la máquina no llega a la pieza.' },
        transfer: 'Crea un traveler para una platina de práctica con datum, montaje, herramienta, sobrematerial, medida y criterio de cada operación.',
      }),
      L({ slug: 'torno-y-trabajo-entre-puntos', title: 'Torno relojero, pinzas y trabajo entre puntos', question: '¿Cuándo conviene sujetar en pinza, plato, mandril o entre puntos y qué error domina?',
        core: 'El torno genera superficies de revolución respecto al eje real de montaje. Pinza ofrece repetibilidad si material y pinza son adecuados; entre puntos conserva un eje común al voltear; mandriles soportan anillos. Excentricidad, flexión, herramienta, velocidad y rebaba compiten en cada corte.', subsystem: 'turning',
        sources: ['source.private.daniels.turning', 'source.private.daniels.hand-tools', 'source.institutional.wostep.watchmaker'],
        concepts: [C('trabajo entre puntos', 'Mecanizado de una pieza apoyada en centros que conservan su eje al invertirla.', 'turning between centers'), C('excentricidad', 'Separación entre el eje geométrico de una característica y el eje de rotación de referencia.', 'runout'), C('buril', 'Herramienta de corte de una punta cuya geometría y apoyo controlan la viruta.', 'graver')],
        sequence: ['preparar centros o superficie', 'elegir sujeción', 'alinear apoyo y buril', 'desbastar', 'medir sin retirar referencia', 'acabar y verificar al invertir'],
        quantities: ['descentramiento', 'diámetro', 'velocidad superficial', 'profundidad de corte', 'conicidad'],
        caseStudy: 'Un eje queda perfecto en una sujeción y excéntrico tras voltearlo. La pinza, rebaba o superficie de agarre cambió el eje de referencia. Trabajar entre centros o preparar una referencia común evita acumular el error.',
        failures: ['Acercar dedos o ropa a una pieza giratoria.', 'Medir una pieza flexible con presión que la dobla.'], misconception: { expression: 'Si la lectura de diámetro es correcta, el eje está bien torneado', correction: 'también importan cilindricidad, conicidad, acabado, concentricidad y relación entre características.' },
        transfer: 'Selecciona método de sujeción para eje, rueda, anillo y tornillo; justifica datum, riesgo de deformación y verificación al volver a montar.',
      }),
      L({ slug: 'ejes-pivotes-y-reparacion', title: 'Ejes, pivotes, hombros y sustitución de staffs', question: '¿Cómo se fabrica un eje capaz de girar, apoyar y sobrevivir sin introducir concentraciones de tensión?',
        core: 'Un staff integra asientos, hombros, pivotes, roscas o remaches en un eje común. Secuencia, tratamiento térmico y acabado deben conservar concentricidad. El pivote necesita forma y superficie funcional; el hombro fija posición y el radio reduce tensión sin invadir el apoyo.', subsystem: 'staff-making',
        sources: ['source.private.daniels.turning', 'source.private.daniels.small-components', 'source.external.bobinchak-school'],
        concepts: [C('pivote', 'Extremo cilíndrico o conformado de un eje que gira o apoya en un cojinete.', 'pivot'), C('hombro', 'Cambio de diámetro que posiciona axialmente y transmite carga entre secciones.', 'shoulder'), C('bruñido', 'Acabado por deformación y alisado controlados que mejora forma y superficie del pivote.', 'burnishing')],
        sequence: ['documentar pieza original', 'establecer centros', 'tornear cuerpos y hombros', 'tratar térmicamente', 'rectificar y bruñir pivotes', 'probar juegos y montaje'],
        quantities: ['diámetro de pivote', 'longitud entre hombros', 'radio', 'conicidad', 'rugosidad y dureza'],
        caseStudy: 'Un pivote nuevo entra en el rubí pero el volante queda sin juego axial. El diámetro era solo una de varias características: distancia entre hombros, asiento del platillo y altura del volante determinan el conjunto.',
        failures: ['Copiar una pieza desgastada como si conservara cotas originales.', 'Crear hombro agudo o pulir hasta reducir diámetro funcional.'], misconception: { expression: 'Hacer un staff consiste en copiar sus diámetros', correction: 'la función depende además de longitudes, centros, hombros, radios, dureza, acabado, montaje y juegos.' },
        transfer: 'Prepara un plano de proceso de un eje de práctica y distingue cotas copiadas, inferidas por conjunto y calculadas por función.',
      }),
      L({ slug: 'ruedas-y-pinones', title: 'Fabricación de ruedas, piñones y cortadores', question: '¿Cómo se transforma una relación cinemática en dientes fabricables y verificables?',
        core: 'Diseñar dentado requiere sistema de perfil, módulo o paso, dientes, correcciones y distancia entre centros. Fabricar añade cortador, división, concentricidad, espesor y acabado. En piñones pequeños, hojas y huecos exigen geometría especializada; la prueba de engrane completa la inspección dimensional.', subsystem: 'wheel-making',
        sources: ['source.private.daniels.wheels-pinions', 'source.private.vba-uhrentechnik', 'source.private.daniels.movement-design'],
        concepts: [C('fresa de módulo', 'Cortador perfilado para generar espacios de diente dentro de un sistema y rango definidos.', 'module cutter'), C('división angular', 'Indexado del blank en incrementos iguales para producir el número de dientes.', 'angular indexing'), C('piñón de hojas', 'Piñón relojero de pocos dientes con perfiles adaptados al engrane con rueda.', 'pinion leaves')],
        sequence: ['definir relación y centros', 'calcular blank y perfil', 'fabricar o elegir cortador', 'centrar y dividir', 'cortar y desbarbar', 'medir y probar engrane'],
        quantities: ['número de dientes', 'módulo/paso', 'diámetros', 'espesor', 'excentricidad e índice'],
        caseStudy: 'Una rueda tiene todos sus dientes pero pulsa una vez por vuelta. Una desviación de centrado del blank o del montaje puede dominar aunque el cortador sea correcto. Se separa error periódico del perfil local.',
        failures: ['Usar un perfil genérico para cualquier número de hojas.', 'Desbarbar cambiando el espesor funcional del diente.'], misconception: { expression: 'Contar bien las divisiones garantiza una rueda buena', correction: 'también deben ser correctos centro, perfil, profundidad, espesor, material, acabado y compatibilidad con su piñón.' },
        transfer: 'Elige un par rueda-piñón de práctica y produce una hoja de cálculo verificable con unidades, relación, blank, cortador, indexado y pruebas.',
      }),
      L({ slug: 'tornillos-muelles-y-pequenas-piezas', title: 'Tornillos, pasadores, muelles y piezas pequeñas', question: '¿Cómo se fabrican elementos diminutos que deben fijar, flexar o localizar sin fallar durante el servicio?',
        core: 'Un tornillo combina rosca, vástago, hombro, cabeza y ranura; un muelle combina material, forma, apoyo y deflexión. El orden de torneado, roscado, temple, revenido y acabado controla fragilidad y precisión. La herramienta de servicio forma parte del diseño de la interfaz.', subsystem: 'small-parts',
        sources: ['source.private.daniels.small-components', 'source.private.daniels.finishing-metals', 'source.private.daniels.hand-tools'],
        concepts: [C('rosca funcional', 'Perfil helicoidal con diámetro, paso, forma y ajuste que convierte giro en retención o desplazamiento.', 'functional thread'), C('muelle de lámina', 'Elemento elástico plano que almacena energía al flexionarse dentro de un rango.', 'leaf spring'), C('concentración de tensiones', 'Aumento local de esfuerzo causado por entalla, cambio de sección o defecto.', 'stress concentration')],
        sequence: ['definir carga e interfaz', 'elegir material', 'formar geometría dejando apoyo', 'generar rosca o flexión', 'tratar térmicamente', 'acabar y probar ciclos'],
        quantities: ['paso y diámetro', 'profundidad de ranura', 'espesor de muelle', 'deflexión', 'tensión y ciclos'],
        caseStudy: 'Un clic casero funciona una vez y se rompe después. La forma puede concentrar tensión, el temple ser excesivo o la deflexión superar rango. Una prueba estática no demuestra vida cíclica.',
        failures: ['Ranurar una cabeza hasta debilitarla.', 'Doblar un muelle endurecido sin control de radio y estado.'], misconception: { expression: 'Si una pieza pequeña encaja, su fabricación está terminada', correction: 'retención, elasticidad, fatiga, acabado, servicio y seguridad se validan en condiciones funcionales.' },
        transfer: 'Diseña un clic de práctica mediante función, diagrama de carga, material, proceso, tratamiento y ensayo incremental hasta fallo seguro.',
      }),
      L({ slug: 'platinas-puentes-y-jewelling', title: 'Platinas, puentes, taladros, escariado y colocación de rubíes', question: '¿Cómo se crea una estructura que alinee centros y permita montar, ajustar y reparar?',
        core: 'La platina define referencias; puentes cierran apoyos y fijan alturas. Taladrar, mandrinar y escariar producen funciones diferentes. Los rubíes a presión necesitan alojamiento, interferencia, perpendicularidad y altura controlados. Un error de centro puede no corregirse agrandando el agujero.', subsystem: 'plate-making',
        sources: ['source.private.daniels.movement-design', 'source.private.daniels.jewelling', 'source.private.daniels.workshop-equipment'],
        concepts: [C('coordenada de centro', 'Posición nominal de un eje respecto a datums de la platina.', 'center coordinate'), C('escariado', 'Acabado dimensionado de un agujero preexistente mediante herramienta guiada.', 'reaming'), C('interferencia de rubí', 'Diferencia controlada entre alojamiento y diámetro exterior de piedra para retención a presión.', 'jewel interference')],
        sequence: ['definir datums y tren', 'localizar centros', 'taladrar con sobrematerial', 'mandrinar/escariar', 'instalar rubíes a altura', 'cerrar puentes y verificar depthing'],
        quantities: ['coordenadas', 'distancia entre centros', 'diámetro de alojamiento', 'interferencia', 'altura y perpendicularidad'],
        caseStudy: 'Después de prensar un rubí, el tren se endurece. Puede haberse cerrado el agujero, inclinado la piedra o cambiado altura; también existir rebaba bajo el puente. Se mide antes de corregir y se conserva el centro original.',
        failures: ['Prensar apoyando sobre la zona frágil de la piedra.', 'Usar el rubí como guía para corregir un centro mal ubicado.'], misconception: { expression: 'Colocar rubíes es una operación puramente decorativa o de presión', correction: 'define centro, juego, altura, aceite y estabilidad estructural, con tolerancias funcionales.' },
        transfer: 'Planifica una placa de prueba con dos centros y rubíes: datums, máquinas, útiles, medición, interferencia y prueba de libertad.',
      }),
    ],
  },
  {
    key: 'dials-hands-finishing', id: 'route.encyclopedia.dials-hands-finishing', title: 'Esferas, agujas y acabados',
    purpose: 'Integrar legibilidad, fabricación, ajuste y decoración sin sacrificar función ni geometría.',
    difficulty: 'advanced', entryPolicy: 'requires-cases-and-micromechanics', lessons: [
      L({ slug: 'arquitectura-de-esfera', title: 'Arquitectura de esfera, pies, aberturas e interfaces', question: '¿Cómo se diseña una esfera que se posicione, no roce y comunique una jerarquía legible?',
        core: 'La esfera es componente estructural y gráfico. Diámetro, espesor, pies, asiento, abertura central, ventanas, altura de índices y acabado deben convivir con movimiento, calendario, agujas y caja. Las referencias del diseño visual deben partir de centros e interfaces reales.', subsystem: 'dial',
        sources: ['source.private.daniels.engine-turning', 'source.private.daniels.casemaking', 'source.official.miyota.8215'],
        concepts: [C('pie de esfera', 'Elemento de posicionamiento y fijación que relaciona esfera y movimiento.', 'dial foot'), C('plano de esfera', 'Superficie geométrica de referencia desde la que se controlan alturas de indicación.', 'dial plane'), C('jerarquía de lectura', 'Orden visual con que marcas y contrastes comunican información temporal.', 'reading hierarchy')],
        sequence: ['fijar centros y diámetro', 'definir plano y fijación', 'situar aberturas', 'reservar alturas', 'aplicar gráfica y acabado', 'montar y probar lectura'],
        quantities: ['diámetro y espesor', 'coordenadas de pies', 'ventana', 'altura de índices', 'contraste'],
        caseStudy: 'Una esfera nueva encaja en caja, pero la ventana de fecha queda desplazada. El diámetro exterior no referencia el disco; deben partirse coordenadas del eje y arquitectura del calibre, además de tolerancia del asiento.',
        failures: ['Pegar una esfera sin plan de reversibilidad y altura.', 'Añadir índices que invaden el barrido de agujas.'], misconception: { expression: 'La esfera es una imagen plana que se escala al diámetro de caja', correction: 'es una pieza tridimensional con centros, fijaciones, ventanas, tolerancias y jerarquía de lectura.' },
        transfer: 'Crea una ficha de interfaz de esfera para un movimiento adquirido: datos oficiales, mediciones, gráficos, tolerancias y prueba en dummy.',
      }),
      L({ slug: 'impresion-indices-y-lume', title: 'Impresión, índices aplicados y material luminoso', question: '¿Cómo se producen marcas legibles y duraderas sin añadir altura o masa incontroladas?',
        core: 'Tampografía, transferencia, grabado, índices aplicados y rellenos luminosos tienen procesos y tolerancias diferentes. Tinta, superficie, curado, adhesión, posición y espesor condicionan borde y duración. Material luminoso añade partículas, aglutinante, masa, seguridad y envejecimiento.', subsystem: 'dial-decoration',
        sources: ['source.private.daniels.engine-turning', 'source.external.ashton-tracy', 'source.encyclopedia.original-synthesis'],
        concepts: [C('tampografía', 'Transferencia indirecta de tinta desde cliché mediante tampón deformable.', 'pad printing'), C('registro gráfico', 'Alineación entre capas, centros y elementos impresos o aplicados.', 'print registration'), C('luminiscencia', 'Emisión de luz posterior a excitación, dependiente de material, carga y percepción.', 'luminescence')],
        sequence: ['preparar superficie', 'definir cliché o posición', 'depositar tinta/índice', 'controlar espesor', 'curar o fijar', 'inspeccionar registro y legibilidad'],
        quantities: ['espesor de capa', 'desviación de registro', 'altura de índice', 'tiempo de curado', 'luminancia y decaimiento'],
        caseStudy: 'Un lume muy grueso brilla al inicio pero desequilibra la aguja o roza. El desempeño exige distribución, adhesión, masa, altura y curva de decaimiento, no solo fotografía de máxima carga.',
        failures: ['Manipular material histórico luminoso sin identificar riesgo.', 'Evaluar registro solo desde un ángulo oblicuo.'], misconception: { expression: 'Más material luminoso siempre mejora la legibilidad', correction: 'masa, altura, uniformidad, aglutinante, geometría y decaimiento pueden empeorar función o seguridad.' },
        transfer: 'Diseña una muestra de proceso con varias cargas y mide registro, espesor, masa, decaimiento y roce antes de aplicar a una esfera real.',
      }),
      L({ slug: 'agujas-geometria-y-ajuste', title: 'Agujas: geometría, masa, tubo, ajuste y alturas', question: '¿Cómo transmite una aguja movimiento y mantiene lectura sin rozar ni soltarse?',
        core: 'La aguja combina cuerpo legible y tubo ajustado al órgano de indicación. Interferencia, concentricidad, perpendicularidad, masa y momento de inercia afectan montaje y carga. Las alturas forman una cadena entre esfera, horaria, minutera, segundero y cristal.', subsystem: 'hands',
        sources: ['source.private.daniels.small-components', 'source.official.miyota.2035', 'source.official.miyota.8215'],
        concepts: [C('tubo de aguja', 'Casquillo que proporciona ajuste y orientación entre aguja y eje.', 'hand tube'), C('ajuste de agujas', 'Interferencia funcional que retiene la aguja permitiendo montaje controlado.', 'hand fit'), C('paralelismo de agujas', 'Relación de planos que conserva separación durante todo el giro.', 'hand parallelism')],
        sequence: ['verificar diámetros y alturas', 'sujetar movimiento y esfera', 'orientar y prensar axialmente', 'comprobar ajuste', 'girar ciclo completo', 'verificar bajo cristal'],
        quantities: ['diámetro de tubo/eje', 'interferencia', 'altura', 'descentramiento', 'masa y momento'],
        caseStudy: 'Las agujas no rozan a las doce pero lo hacen a las seis. Eso sugiere inclinación, deformación o descentramiento, no solo altura media. Se gira el ciclo con luz lateral y se corrige la causa sin doblar a ciegas.',
        failures: ['Prensar apoyando sobre pivote sin soporte.', 'Reutilizar una aguja floja cerrando el tubo sin medir.'], misconception: { expression: 'Si las agujas quedan separadas al montarlas, no rozarán', correction: 'deben mantener concentricidad, planitud y separación durante todo el giro y bajo cargas de uso.' },
        transfer: 'Construye una cadena de alturas desde platina a cristal y define galgas y pruebas para cada interfaz.',
      }),
      L({ slug: 'pulido-satinado-y-cepillado', title: 'Pulido, satinado, cepillado y geometría', question: '¿Cómo se crea una textura controlada sin perder forma ni referencias?',
        core: 'El pulido reduce dispersión y marcas; satinado y cepillado crean dirección mediante abrasión controlada. Secuencia de granos, soporte, presión, velocidad, limpieza y enmascarado determinan superficie. La prioridad es conservar planos, aristas, espesores y función antes que maximizar brillo.', subsystem: 'finishing',
        sources: ['source.private.daniels.finishing-metals', 'source.external.ashton-tracy', 'source.external.naked-watchmaker'],
        concepts: [C('secuencia abrasiva', 'Progresión de tamaños y soportes que elimina la huella anterior sin saltos incontrolados.', 'abrasive sequence'), C('dirección de grano', 'Orientación dominante de las trazas que define el aspecto satinado.', 'grain direction'), C('protección de arista', 'Método de soporte o máscara para evitar redondeo de límites geométricos.', 'edge protection')],
        sequence: ['documentar forma', 'nivelar solo si está autorizado', 'progresar abrasivos', 'limpiar entre granos', 'generar textura final', 'inspeccionar bajo luces múltiples'],
        quantities: ['tamaño de abrasivo', 'material removido', 'planitud', 'radio de arista', 'dirección y uniformidad'],
        caseStudy: 'Una marca profunda cruza una asa. Eliminarla exigiría bajar todo el plano y alterar arista. La decisión puede ser reducir visualmente, no borrar, conservando simetría y espesor.',
        failures: ['Perseguir cada marca profunda hasta perder volumen.', 'Contaminar un abrasivo fino con partículas gruesas.'], misconception: { expression: 'El acabado se evalúa solo por brillo uniforme', correction: 'debe conservar geometría, dirección, transición, limpieza, espesor y función además de apariencia.' },
        transfer: 'Prepara cupones de latón y acero con tres secuencias; registra abrasivo, soporte, dirección, tiempo, pérdida y luz de inspección.',
      }),
      L({ slug: 'decoracion-del-movimiento', title: 'Anglage, perlage, Côtes y pulido negro', question: '¿Qué geometría y reflexión produce cada decoración y dónde termina la estética y empieza la función?',
        core: 'Anglage crea un bisel regular que define aristas; perlage superpone círculos; Côtes genera bandas abrasivas; pulido negro produce una superficie tan plana que refleja de forma direccional. Cada técnica exige preparación, secuencia y referencias. No debe invadir asientos, roscas, muelles ni superficies de contacto.', subsystem: 'movement-finishing',
        sources: ['source.private.daniels.finishing-metals', 'source.external.naked-watchmaker', 'source.external.ashton-tracy'],
        concepts: [C('anglage', 'Bisel pulido de anchura y continuidad controladas en el borde de una pieza.', 'bevelling'), C('perlage', 'Decoración de círculos parcialmente solapados aplicada de forma ordenada.', 'perlage'), C('pulido negro', 'Lapeado extremo de una superficie plana que aparece negra en determinados ángulos por reflexión especular.', 'black polishing')],
        sequence: ['proteger superficies funcionales', 'preparar plano o borde', 'crear geometría', 'refinar abrasivos', 'limpiar', 'evaluar continuidad y reflexión'],
        quantities: ['ancho de bisel', 'paso de solape', 'planitud', 'rugosidad', 'material removido'],
        caseStudy: 'Una cabeza de tornillo brilla pero sus cantos están redondeados y ranura deformada. La decoración falló porque destruyó interfaz de herramienta y geometría, aunque la reflexión sea intensa.',
        failures: ['Decorar después de ajustar sin proteger dimensiones.', 'Usar pulido para ocultar picaduras profundas.'], misconception: { expression: 'La alta relojería se reconoce por cuantas más decoraciones, mejor', correction: 'calidad exige geometría, regularidad, coherencia, función y ejecución, no acumulación de patrones.' },
        transfer: 'Evalúa una pieza decorada con rúbrica de geometría, repetición, transición, superficie funcional, reversibilidad y evidencia de proceso.',
      }),
      L({ slug: 'guilloche-y-motores-de-rosas', title: 'Guilloché, motor de línea recta y motor de rosas', question: '¿Cómo se genera un patrón mediante movimiento guiado y qué diferencia corte real de imitación visual?',
        core: 'El guilloché tradicional corta líneas mediante relación mecánica entre roseta o guía, pieza y herramienta. Frecuencia del patrón, amplitud, indexado, avance, profundidad y fase determinan continuidad. Estampado, grabado CNC y texturas impresas pueden producir apariencia parecida con procesos y señales distintas.', subsystem: 'engine-turning',
        sources: ['source.private.daniels.engine-turning', 'source.external.naked-watchmaker', 'source.institutional.wostep.watchmaker'],
        concepts: [C('motor de rosas', 'Máquina cuyo cabezal oscila siguiendo rosetas para cortar patrones sobre una pieza giratoria.', 'rose engine'), C('indexado', 'Posicionamiento angular discreto y repetible entre pasadas.', 'indexing'), C('fase de patrón', 'Relación de alineación entre ciclos de líneas adyacentes o superpuestas.', 'pattern phase')],
        sequence: ['preparar blank', 'elegir roseta/guía', 'ajustar amplitud y herramienta', 'indexar', 'cortar pasadas', 'inspeccionar continuidad y acabado'],
        quantities: ['divisiones', 'amplitud', 'paso', 'profundidad', 'avance y fase'],
        caseStudy: 'Un patrón cierra casi bien pero deja discontinuidad al final. El error puede provenir de división, holgura, fase o acumulación de paso. Corregir una línea individual no repara la periodicidad del sistema.',
        failures: ['Cortar una esfera final sin cupones de material y acabado.', 'Confundir patrón prensado con corte manual al documentar procedencia.'], misconception: { expression: 'Guilloché describe cualquier dibujo geométrico repetido', correction: 'el término técnico debe acompañarse del proceso real; apariencias semejantes pueden proceder de corte, estampado, fresado o impresión.' },
        transfer: 'Diseña un patrón de prueba con variables de indexado, amplitud y fase, y documenta cómo distinguirías procesos por huellas sin afirmar autoría.',
      }),
    ],
  },
]
