import { createHash } from 'node:crypto'
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { join, relative, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import {
  ACADEMY_MIYOTA_8215_PARTS_LIST_DRIFT_014J, ACADEMY_MIYOTA_8215_PRODUCT_PAGE_DRIFT_014J,
  ACADEMY_MIYOTA_8215_SOURCE_ALIASES_014J, ACADEMY_MIYOTA_8215_SOURCE_SNAPSHOT_014J,
  ACADEMY_PERSONAL_REVIEW_QUEUE_014J, ACADEMY_READER_CURATION_PHASES, ACADEMY_PERSONAL_CURATION_PHASES,
  ACADEMY_STAGE_3_ACTIVE_TECHNICAL_STATUS_014J, ACADEMY_STAGE_4_3D_AUDIT, ACADEMY_STAGE_4_ACTIVITY_PRESENTATIONS,
  ACADEMY_STAGE_4_ANCHOR_IDS, ACADEMY_STAGE_4_CATALOG, ACADEMY_STAGE_4_CHAPTER_SEQUENCE, ACADEMY_STAGE_4_CLAIMS,
  ACADEMY_STAGE_4_FINAL_CHECKPOINT, ACADEMY_STAGE_4_OPTIONAL_IDS, ACADEMY_STAGE_4_PART_MAPPINGS, ACADEMY_STAGE_4_PERSONAL_PRACTICES,
  ACADEMY_STAGE_4_PHOTO_BRIEFS, ACADEMY_STAGE_4_PREREQUISITE_OVERRIDES, ACADEMY_STAGE_4_REUSED_VISUALS,
  ACADEMY_STAGE_4_SAFETY_AUDITS, ACADEMY_STAGE_4_SAFETY_POLICY, ACADEMY_STAGE_4_SELECTOR_MAPPINGS, ACADEMY_STAGE_4_SIMULATION_BOUNDARY,
  ACADEMY_STAGE_4_SUPPORT_IDS, ACADEMY_STAGE_4_TRANSITIONS, ACADEMY_STAGE_4_VISUAL_DESIGNS, ACADEMY_STAGE_4_VISUAL_QUESTION_COVERAGE,
  academy014JContentPreservation,
} from '../src/learning/academy/reader/academyPersonalCurriculum'
import { buildAcademyReaderDocument, validateAcademyReaderDocument } from '../src/learning/academy/reader/academyReaderDocument'
import type { AcademyReaderBuildInput, AcademyReaderDocument } from '../src/learning/academy/reader/academyReaderModel'
import type { LearningPack } from '../src/learning/content/learningPack'
import { createLearningProductIndex, mergeLearningProductIndexes } from '../src/learning/product/demoPackage'
import { loadAcademyCorpus } from './academy-audit/corpus'
import { ACADEMY_014J_QA_CASES, ACADEMY_014J_QA_MATRIX } from './academy-audit/academy-014j-qa-snapshot'

export const ACADEMY_014J_OUTPUT_FILES = [
  'ACADEMY-0.14J-SUMMARY.md',
  'ACADEMY-ACTIVE-TECHNICAL-STATUS-0.14J.md','ACADEMY-ACTIVE-TECHNICAL-STATUS-0.14J.json',
  'ACADEMY-SOURCE-PRESERVATION-INTEGRITY-0.14J.md','ACADEMY-SOURCE-PRESERVATION-INTEGRITY-0.14J.json',
  'ACADEMY-MIYOTA8215-OFFICIAL-SOURCE-SNAPSHOT-0.14J.md','ACADEMY-MIYOTA8215-OFFICIAL-SOURCE-SNAPSHOT-0.14J.json',
  'ACADEMY-MIYOTA8215-SOURCE-DRIFT-0.14J.md','ACADEMY-MIYOTA8215-SOURCE-DRIFT-0.14J.json',
  'ACADEMY-STAGE-4-CURATION-0.14J.md','ACADEMY-STAGE-4-CURATION-0.14J.json',
  'ACADEMY-STAGE-4-SECTION-DISPOSITION-0.14J.md','ACADEMY-STAGE-4-SECTION-DISPOSITION-0.14J.json',
  'ACADEMY-STAGE-4-CONTENT-PRESERVATION-0.14J.md','ACADEMY-STAGE-4-CONTENT-PRESERVATION-0.14J.json',
  'ACADEMY-STAGE-4-PREREQUISITES-0.14J.md','ACADEMY-STAGE-4-PREREQUISITES-0.14J.json',
  'ACADEMY-STAGE-4-ACTIVITIES-0.14J.md','ACADEMY-STAGE-4-ACTIVITIES-0.14J.json',
  'ACADEMY-STAGE-4-PRACTICES-0.14J.md','ACADEMY-STAGE-4-PRACTICES-0.14J.json',
  'ACADEMY-STAGE-4-CLAIMS-0.14J.md','ACADEMY-STAGE-4-CLAIMS-0.14J.json',
  'ACADEMY-STAGE-4-VISUALS-0.14J.md','ACADEMY-STAGE-4-VISUALS-0.14J.json',
  'ACADEMY-STAGE-4-3D-0.14J.md','ACADEMY-STAGE-4-3D-0.14J.json',
  'ACADEMY-STAGE-4-SIMULATION-BOUNDARY-0.14J.md','ACADEMY-STAGE-4-SIMULATION-BOUNDARY-0.14J.json',
  'ACADEMY-PERSONAL-REVIEW-QUEUE-0.14J.md','ACADEMY-PERSONAL-REVIEW-QUEUE-0.14J.json',
  'ACADEMY-UX-QA-0.14J.md','ACADEMY-SCREENSHOT-INDEX-0.14J.md',
] as const

export const ACADEMY_014J_BASELINE = {
  initialCommit: '200b4fc8101c8f1da45a62bcf39204d5223a21bb',
  corpusCounts: { packages: 8, routes: 24, modules: 217, lessons: 222, activities: 289 }, corpusDigest: '1d209ac9608ca8040222e741401778affac03770b4a51b28ff6e0e2fc44cfd1e',
  protected: { learningContent: { count: 4012, digest: '16291f86a7cb082d47fa65016d838b72e19cf3701afe33bc27ad226cf41af1d4' }, originals: { count: 7, digest: '633edd7f7027a61587b1b944b0b3bf8562819697144b449e4dc9aed1db4ab6b7' }, historicalReports: { count: 166, digest: 'db499204c626f6d0ede6822b618fa876b312b14ddaf02fa3c8e228d892eefc87' } },
} as const

const sha256 = (value: string | Uint8Array) => createHash('sha256').update(value).digest('hex')
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`
const md = (value: string) => `${value.trim()}\n`
const pipe = (value: unknown) => String(value ?? '—').replaceAll('|','\\|').replaceAll('\n','<br>')
const table = (headers: readonly string[], rows: readonly (readonly unknown[])[]) => [
  `| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`, ...rows.map((row) => `| ${row.map(pipe).join(' | ')} |`),
].join('\n')

async function walk(root: string): Promise<string[]> { const result: string[] = []; for (const name of (await readdir(root)).sort()) { const path = join(root,name); const info = await stat(path); if (info.isDirectory()) result.push(...await walk(path)); else result.push(path) } return result }
async function treeSnapshot(root: string) { const files = await walk(root); const rows = await Promise.all(files.map(async (file) => `${relative(root,file).replaceAll('\\','/')}:${sha256(await readFile(file))}`)); return { count: files.length, digest: sha256(rows.join('\n')) } }
async function historicalSnapshot(repositoryRoot: string) { const root = join(repositoryRoot,'docs','generated'); const names = (await readdir(root)).filter((name) => !name.startsWith('APRENDER-') && !/0\.14[J-Z]/i.test(name)).sort(); const rows = await Promise.all(names.map(async (name) => `${name}:${sha256(await readFile(join(root,name)))}`)); return { count: names.length, digest: sha256(rows.join('\n')) } }
async function screenshotRows(repositoryRoot: string) { const root = join(repositoryRoot,'docs','academy-ux','screenshots','0.14J'); const names = await readdir(root).catch(() => []); return Promise.all(names.filter((name) => name.endsWith('.png')).sort().map(async (fileName) => { const content = await readFile(join(root,fileName)); const qa = ACADEMY_014J_QA_CASES.find((item) => item.fileName === fileName); return { fileName, bytes: content.byteLength, sha256: sha256(content), viewport: qa?.viewport ?? 'unknown', lessonId: qa?.lessonId ?? 'unknown', mode: qa?.mode ?? 'unknown', subject: qa?.subject ?? 'unknown' } })) }

function materialFor(pack: LearningPack, lessonId: string, product: ReturnType<typeof mergeLearningProductIndexes>): AcademyReaderBuildInput['material'] { const lesson = pack.lessons.find(({id}) => id === lessonId); const descriptor = product.lessons.find(({id}) => id === lessonId); if (!lesson || !descriptor) throw new Error(`Lección ausente: ${lessonId}`); const blocks = pack.blocks.filter(({id}) => lesson.blockIds.includes(id)); const markdown = blocks.map(({bodyMarkdown}) => bodyMarkdown).join('\n'); const sourceIds = new Set([...(lesson.authoring?.sourceIds ?? []), ...blocks.flatMap(({claims}) => claims.flatMap(({sources}) => sources.map(({id}) => id)))]); return { packageId: pack.manifest.id, packageVersion: pack.manifest.packageVersion, pack, lesson, blocks, activities: descriptor.activityIds.flatMap((activityId) => product.activities.filter(({id}) => id === activityId)), sources: pack.sources.filter(({id}) => sourceIds.has(id)), glossary: pack.glossary.filter(({id}) => markdown.includes(`{{term:${id}}}`)) } }
function documentFor(product: ReturnType<typeof mergeLearningProductIndexes>, pack: LearningPack, lessonId: string, phase: '0.14D' | '0.14J'): AcademyReaderDocument { const descriptor = product.lessons.find(({id}) => id === lessonId)!; return buildAcademyReaderDocument({ material: materialFor(pack,lessonId,product), title: descriptor.title.es, purpose: descriptor.purpose.es, locale: 'es-ES', requiredActivityIds: descriptor.studyContract?.labActivityIds }, { curationPhase: phase }) }

export async function buildAcademy014JOutputs(repositoryRoot: string): Promise<Map<string,string>> {
  const corpus = await loadAcademyCorpus(repositoryRoot); const product = mergeLearningProductIndexes(corpus.packs.map(({pack}) => createLearningProductIndex(pack))); const packByLesson = new Map(corpus.packs.flatMap(({pack}) => pack.lessons.map(({id}) => [id,pack] as const)))
  const learningContent = await treeSnapshot(join(repositoryRoot,'learning-content')); const originals = await treeSnapshot(join(repositoryRoot,'reference-library','originals')); const historical = await historicalSnapshot(repositoryRoot); const screenshots = await screenshotRows(repositoryRoot)
  if (!ACADEMY_READER_CURATION_PHASES.includes('0.14J')) throw new Error('0.14J no está registrada en la composición acumulativa.'); if (Object.entries(ACADEMY_014J_BASELINE.corpusCounts).some(([key,value]) => corpus.counts[key as keyof typeof corpus.counts] !== value) || corpus.digest !== ACADEMY_014J_BASELINE.corpusDigest) throw new Error('El corpus cambió.'); if (JSON.stringify(learningContent) !== JSON.stringify(ACADEMY_014J_BASELINE.protected.learningContent)) throw new Error('learning-content cambió.'); if (JSON.stringify(originals) !== JSON.stringify(ACADEMY_014J_BASELINE.protected.originals)) throw new Error('originals cambió.'); if (JSON.stringify(historical) !== JSON.stringify(ACADEMY_014J_BASELINE.protected.historicalReports)) throw new Error('Los informes 0.14A–0.14I cambiaron.')
  const documents = ACADEMY_STAGE_4_CATALOG.map((item) => { const pack = packByLesson.get(item.lessonId); if (!pack) throw new Error(`Paquete ausente: ${item.lessonId}`); const authored = documentFor(product,pack,item.lessonId,'0.14D'); const visible = documentFor(product,pack,item.lessonId,'0.14J'); const preservation = academy014JContentPreservation(item.lessonId,authored.sections,visible.sections); const validationIssues = validateAcademyReaderDocument(visible); return { item,authored,visible,preservation,validationIssues } })
  if (documents.some(({validationIssues}) => validationIssues.length)) throw new Error('La documentación de etapa 4 no valida.'); if (documents.some(({preservation}) => preservation.row.substantiveCoverage !== 1)) throw new Error('La cobertura sustantiva no alcanza 100 %.')
  const dispositions = documents.flatMap(({preservation}) => preservation.dispositions); const preservationRows = documents.map(({preservation}) => preservation.row); const visibleSectionIds = new Set(documents.flatMap(({visible}) => visible.sections.map(({sectionId}) => sectionId))); if (ACADEMY_STAGE_4_CLAIMS.some(({sectionId}) => !visibleSectionIds.has(sectionId))) throw new Error('Existe un claim sin sección visible.')
  const stage4Statuses = documents.map(({item}) => ({ lessonId: item.lessonId, technicalStatus: ACADEMY_PERSONAL_REVIEW_QUEUE_014J.find(({lessonId}) => lessonId === item.lessonId)?.technicalStatus, decisiveClaimIds: ACADEMY_STAGE_4_CLAIMS.filter(({lessonId,central}) => lessonId === item.lessonId && central).map(({claimId}) => claimId) })); const statusRows = [...ACADEMY_STAGE_3_ACTIVE_TECHNICAL_STATUS_014J.map(({lessonId,technicalStatus,decisiveEvidenceIds}) => ({lessonId,technicalStatus,decisiveEvidenceIds})), ...stage4Statuses]
  const outputs = new Map<string,string>()
  const addPair = (base: string, payload: unknown, title: string, body: string) => { outputs.set(`${base}.json`,json(payload)); outputs.set(`${base}.md`,md(`# ${title}\n\n${body}`)) }

  addPair('ACADEMY-ACTIVE-TECHNICAL-STATUS-0.14J',{schema:'wplab-active-technical-status-v1',phase:'0.14J',precedence:['technical-conflict','source-needed','source-limited','source-reviewed'],counts:Object.fromEntries(['technical-conflict','source-needed','source-limited','source-reviewed'].map((status) => [status,statusRows.filter((row) => row.technicalStatus === status).length])),stage3:ACADEMY_STAGE_3_ACTIVE_TECHNICAL_STATUS_014J,stage4:stage4Statuses},'Estado técnico activo · 0.14J',table(['Lección','Estado','Evidencia decisiva'],statusRows.map((row) => [row.lessonId,row.technicalStatus,'decisiveEvidenceIds' in row ? row.decisiveEvidenceIds.join(', ') : row.decisiveClaimIds.join(', ')])))
  addPair('ACADEMY-SOURCE-PRESERVATION-INTEGRITY-0.14J',{schema:'wplab-source-preservation-integrity-v1',phase:'0.14J',validation:{visibleTargetsRequired:true,nonEmptyTargetsRequired:true,substantiveRemovalReasonRequired:true},counts:{lessons:16,sourceSections:preservationRows.reduce((s,r) => s+r.sourceSectionCount,0),dispositions:dispositions.length,coverage:Math.min(...preservationRows.map((r) => r.substantiveCoverage))},lessons:preservationRows},'Integridad de preservación de fuente · 0.14J',`La validación exige targets visibles y no vacíos para retained, merged y replaced-equivalent.\n\nCobertura sustantiva de etapa 4: **100 %**.`)
  addPair('ACADEMY-MIYOTA8215-OFFICIAL-SOURCE-SNAPSHOT-0.14J',{schema:'wplab-miyota8215-source-snapshot-v1',phase:'0.14J',runtimeNetworkRequired:false,records:ACADEMY_MIYOTA_8215_SOURCE_SNAPSHOT_014J,aliases:ACADEMY_MIYOTA_8215_SOURCE_ALIASES_014J},'Snapshot oficial MIYOTA 8215 · 0.14J',table(['Documento','Estado','SHA-256','Páginas','Consulta'],ACADEMY_MIYOTA_8215_SOURCE_SNAPSHOT_014J.map((r) => [r.title,r.status,r.currentSha256,r.pages,r.checkedAt])))
  addPair('ACADEMY-MIYOTA8215-SOURCE-DRIFT-0.14J',{schema:'wplab-miyota8215-source-drift-v1',phase:'0.14J',partsList:ACADEMY_MIYOTA_8215_PARTS_LIST_DRIFT_014J,productPage:ACADEMY_MIYOTA_8215_PRODUCT_PAGE_DRIFT_014J},'Drift de fuentes MIYOTA 8215 · 0.14J',`La parts list cambia de URL y hash. La comparación registra **3 cambios terminológicos**, **1 cambio de maquetación**, **0 piezas añadidas**, **0 eliminadas** y **0 referencias cambiadas**.\n\n${table(['Anterior','Actual','Referencia','Clase'],ACADEMY_MIYOTA_8215_PARTS_LIST_DRIFT_014J.differences.map((d) => [d.previous,d.current,d.partReference,d.classification]))}`)
  addPair('ACADEMY-STAGE-4-CURATION-0.14J',{schema:'wplab-stage4-curation-v1',phase:'0.14J',readerPhases:ACADEMY_READER_CURATION_PHASES.filter((phase) => phase !== '0.14K'),personalPhases:ACADEMY_PERSONAL_CURATION_PHASES.filter((phase) => phase !== '0.14K'),counts:{chapters:ACADEMY_STAGE_4_CHAPTER_SEQUENCE.length,lessons:16,anchors:ACADEMY_STAGE_4_ANCHOR_IDS.length,supports:ACADEMY_STAGE_4_SUPPORT_IDS.length,optionalBranches:ACADEMY_STAGE_4_OPTIONAL_IDS.length,visibleSections:documents.reduce((s,d) => s+d.visible.sections.length,0)},lessons:documents.map(({item,visible}) => ({...item,visibleSectionCount:visible.sections.length,contentHash:visible.contentHash})),checkpoint:ACADEMY_STAGE_4_FINAL_CHECKPOINT},'Curación completa de etapa 4 · 0.14J',table(['Capítulo','Lección','Rol','Arquetipo','Estado'],documents.map(({item}) => [item.chapterId,item.lessonId,item.pathRole,item.editorialArchetype,stage4Statuses.find(({lessonId}) => lessonId === item.lessonId)?.technicalStatus])))
  addPair('ACADEMY-STAGE-4-SECTION-DISPOSITION-0.14J',{schema:'wplab-stage4-section-disposition-v1',phase:'0.14J',counts:{total:dispositions.length,retained:dispositions.filter(({action}) => action === 'retained').length},dispositions},'Disposición de secciones fuente · etapa 4 · 0.14J',table(['Lección','Sección fuente','Acción','Targets'],dispositions.map((d) => [d.lessonId,d.sourceSectionId,d.action,d.targetSectionIds.join(', ')])))
  addPair('ACADEMY-STAGE-4-CONTENT-PRESERVATION-0.14J',{schema:'wplab-stage4-content-preservation-v1',phase:'0.14J',counts:{lessons:16,sourceSections:preservationRows.reduce((s,r) => s+r.sourceSectionCount,0),sourceWords:preservationRows.reduce((s,r) => s+r.sourceSubstantiveWords,0),visibleWords:preservationRows.reduce((s,r) => s+r.visibleWords,0),substantiveCoverage:Math.min(...preservationRows.map((r) => r.substantiveCoverage))},lessons:preservationRows},'Preservación de contenido · etapa 4 · 0.14J',table(['Lección','Secciones fuente','Palabras fuente','Palabras visibles','Cobertura'],preservationRows.map((r) => [r.lessonId,r.sourceSectionCount,r.sourceSubstantiveWords,r.visibleWords,`${(r.substantiveCoverage*100).toFixed(0)} %`])))
  addPair('ACADEMY-STAGE-4-PREREQUISITES-0.14J',{schema:'wplab-stage4-prerequisites-v1',phase:'0.14J',chapterSequence:ACADEMY_STAGE_4_CHAPTER_SEQUENCE,transitions:ACADEMY_STAGE_4_TRANSITIONS,overrides:ACADEMY_STAGE_4_PREREQUISITE_OVERRIDES},'Prerrequisitos · etapa 4 · 0.14J',`Secuencia: **4.1 → 4.2 → 4.3 → 4.4 → 4.5**. El calendario es support no bloqueante y advanced service-disassembly permanece opcional. 4.5 abre 5.1 sin acreditar servicio.`)
  const curriculumActivityIds = new Set(corpus.packs.flatMap(({pack}) => pack.activities.map(({id}) => id))); addPair('ACADEMY-STAGE-4-ACTIVITIES-0.14J',{schema:'wplab-stage4-activities-v1',phase:'0.14J',counts:{presentations:ACADEMY_STAGE_4_ACTIVITY_PRESENTATIONS.length,presentInCorpus:ACADEMY_STAGE_4_ACTIVITY_PRESENTATIONS.filter(({activityId}) => curriculumActivityIds.has(activityId)).length,physicalEvidenceClaims:0},presentations:ACADEMY_STAGE_4_ACTIVITY_PRESENTATIONS},'Actividades curriculares · etapa 4 · 0.14J',table(['Actividad','Lección','Modalidades','P'],ACADEMY_STAGE_4_ACTIVITY_PRESENTATIONS.map((a) => [a.activityId,a.lessonId,a.evidenceProfile.modalities.join('+'),a.evidenceProfile.physicalExecutionRequired])))
  addPair('ACADEMY-STAGE-4-PRACTICES-0.14J',{schema:'wplab-stage4-practices-v1',phase:'0.14J',counts:{practices:ACADEMY_STAGE_4_PERSONAL_PRACTICES.length,affectsProgress:0,createsMastery:0,completesLesson:0},practices:ACADEMY_STAGE_4_PERSONAL_PRACTICES},'Prácticas personales · etapa 4 · 0.14J',table(['Práctica','Lecciones','Progreso'],ACADEMY_STAGE_4_PERSONAL_PRACTICES.map((p) => [p.personalPracticeId,p.lessonIds.join(', '),'no'])))
  addPair('ACADEMY-STAGE-4-CLAIMS-0.14J',{schema:'wplab-stage4-claims-v1',phase:'0.14J',counts:{claims:ACADEMY_STAGE_4_CLAIMS.length,numericClaims:ACADEMY_STAGE_4_CLAIMS.filter(({numericValues}) => numericValues.length).length,partClaims:ACADEMY_STAGE_4_CLAIMS.filter(({partReference}) => partReference).length,sourceNeeded:ACADEMY_STAGE_4_CLAIMS.filter(({technicalStatus}) => technicalStatus === 'source-needed').length,orphaned:0},claims:ACADEMY_STAGE_4_CLAIMS},'Claims · etapa 4 · 0.14J',table(['Claim','Lección','Estado','Snapshot'],ACADEMY_STAGE_4_CLAIMS.map((c) => [c.claimId,c.lessonId,c.technicalStatus,c.snapshotIds.join(', ')])))
  addPair('ACADEMY-STAGE-4-VISUALS-0.14J',{schema:'wplab-stage4-visuals-v1',phase:'0.14J',counts:{reused:ACADEMY_STAGE_4_REUSED_VISUALS.length,new:ACADEMY_STAGE_4_VISUAL_DESIGNS.length,questionsCovered:ACADEMY_STAGE_4_VISUAL_QUESTION_COVERAGE.length,photoBriefs:ACADEMY_STAGE_4_PHOTO_BRIEFS.length},reusedVisualIds:ACADEMY_STAGE_4_REUSED_VISUALS,newDesigns:ACADEMY_STAGE_4_VISUAL_DESIGNS,questionCoverage:ACADEMY_STAGE_4_VISUAL_QUESTION_COVERAGE,photoBriefs:ACADEMY_STAGE_4_PHOTO_BRIEFS},'Visuales · etapa 4 · 0.14J',`Se reutilizan **${ACADEMY_STAGE_4_REUSED_VISUALS.length}** visuales y se añaden **${ACADEMY_STAGE_4_VISUAL_DESIGNS.length}** diagramas semánticos. Los ${ACADEMY_STAGE_4_PHOTO_BRIEFS.length} briefs exigen fotografía real futura y no cuentan como visuales.`)
  addPair('ACADEMY-STAGE-4-3D-0.14J',{schema:'wplab-stage4-3d-v1',phase:'0.14J',counts:{states:ACADEMY_STAGE_4_3D_AUDIT.length,partMappings:ACADEMY_STAGE_4_PART_MAPPINGS.length,selectorMappings:ACADEMY_STAGE_4_SELECTOR_MAPPINGS.length,sourceNeeded:ACADEMY_STAGE_4_3D_AUDIT.filter(({technicalStatus}) => technicalStatus === 'source-needed').length},states:ACADEMY_STAGE_4_3D_AUDIT,partMappings:ACADEMY_STAGE_4_PART_MAPPINGS,selectorMappings:ACADEMY_STAGE_4_SELECTOR_MAPPINGS},'Auditoría 3D · etapa 4 · 0.14J',table(['Estado','Decisión','Estado técnico','Motivo'],ACADEMY_STAGE_4_3D_AUDIT.map((s) => [s.visualStateId,s.decision,s.technicalStatus,s.reason])))
  addPair('ACADEMY-STAGE-4-SIMULATION-BOUNDARY-0.14J',{schema:'wplab-stage4-simulation-boundary-v1',phase:'0.14J',boundary:ACADEMY_STAGE_4_SIMULATION_BOUNDARY,safetyPolicy:ACADEMY_STAGE_4_SAFETY_POLICY,safetyAudits:ACADEMY_STAGE_4_SAFETY_AUDITS},'Frontera simulación/físico · etapa 4 · 0.14J','La vista explosionada y el 3D enseñan identidad, capas y dependencias. No son una secuencia de servicio, no acreditan P y no prescriben lubricación, fuerza, ajuste, par o aceptación física.')
  addPair('ACADEMY-PERSONAL-REVIEW-QUEUE-0.14J',{schema:'wplab-personal-review-queue-v4',phase:'0.14J',counts:{unique:ACADEMY_PERSONAL_REVIEW_QUEUE_014J.length,stage4:ACADEMY_STAGE_4_CATALOG.filter(({lessonId}) => ACADEMY_PERSONAL_REVIEW_QUEUE_014J.some((q) => q.lessonId === lessonId)).length,notReviewed:ACADEMY_PERSONAL_REVIEW_QUEUE_014J.filter(({personalStatus}) => personalStatus === 'not-reviewed').length},queue:ACADEMY_PERSONAL_REVIEW_QUEUE_014J},'Cola de revisión personal · 0.14J',`Entradas únicas: **${ACADEMY_PERSONAL_REVIEW_QUEUE_014J.length}**. Origin phase y personal status se conservan al recalcular el estado técnico.`)
  outputs.set('ACADEMY-UX-QA-0.14J.md',md(`# QA de experiencia · 0.14J\n\nPerfiles: ${ACADEMY_014J_QA_MATRIX.viewports.join(', ')}. Se inspeccionan tema claro/oscuro, movimiento reducido, teclado, foco y fallback sin WebGL. Este QA técnico no declara claridad humana demostrada.\n\nCapturas previstas: ${ACADEMY_014J_QA_CASES.length}; encontradas: ${screenshots.length}.`))
  outputs.set('ACADEMY-SCREENSHOT-INDEX-0.14J.md',md(`# Índice de capturas · 0.14J\n\nDirectorio: \`docs/academy-ux/screenshots/0.14J/\`.\n\n${table(['Archivo','Viewport','Lección','Modo','Asunto','SHA-256'],ACADEMY_014J_QA_CASES.map((q) => { const shot = screenshots.find(({fileName}) => fileName === q.fileName); return [q.fileName,q.viewport,q.lessonId,q.mode,q.subject,shot?.sha256 ?? 'pendiente'] }))}`))
  outputs.set('ACADEMY-0.14J-SUMMARY.md',md(`# Watch Prototype Lab 0.14J · resumen\n\n- Corpus: 8 paquetes, 24 rutas, 217 módulos, 222 lecciones y 289 actividades.\n- Etapa 4: ${ACADEMY_STAGE_4_ANCHOR_IDS.length} anchors, ${ACADEMY_STAGE_4_SUPPORT_IDS.length} support, ${ACADEMY_STAGE_4_OPTIONAL_IDS.length} rama opcional y 100 % de cobertura sustantiva.\n- Snapshot: página, specification, drawing, manual, parts list y dos dial drawings verificados; runtime sin red.\n- Drift: 3 cambios terminológicos, 1 de maquetación, 0 piezas y 0 referencias cambiadas.\n- Evidencia: K/V/R combinables; ninguna actividad virtual produce P.\n\n0.14J endurece el estado técnico y la preservación real, y cierra la etapa 4 completa sin iniciar la construcción del reloj de etapa 5.`))
  if (outputs.size !== ACADEMY_014J_OUTPUT_FILES.length || [...outputs.keys()].some((name) => !ACADEMY_014J_OUTPUT_FILES.includes(name as typeof ACADEMY_014J_OUTPUT_FILES[number]))) throw new Error(`El contrato exige ${ACADEMY_014J_OUTPUT_FILES.length} salidas.`)
  return outputs
}

async function main() { const repositoryRoot = resolve(process.cwd()); const outputs = await buildAcademy014JOutputs(repositoryRoot); const generatedRoot = join(repositoryRoot,'docs','generated'); const check = process.argv.includes('--check'); if (!check) { await mkdir(generatedRoot,{recursive:true}); await Promise.all([...outputs].map(([name,content]) => writeFile(join(generatedRoot,name),content,'utf8'))); console.log(`Academia 0.14J: ${outputs.size} informes generados.`); return } const mismatches: string[] = []; for (const [name,content] of outputs) { const existing = await readFile(join(generatedRoot,name),'utf8').catch(() => null); if (existing !== content) mismatches.push(name) } if (mismatches.length) throw new Error(`Salidas 0.14J desactualizadas: ${mismatches.join(', ')}`); console.log(`Academia 0.14J: ${outputs.size} informes verificados.`) }

const invoked = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : ''; if (import.meta.url === invoked) main().catch((error) => { console.error(error); process.exitCode = 1 })
