import { createHash } from 'node:crypto'
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { join, relative, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import {
  ACADEMY_PERSONAL_CURATION_PHASES, ACADEMY_PERSONAL_REVIEW_QUEUE_014K, ACADEMY_READER_CURATION_PHASES,
  ACADEMY_STAGE_5_3D_POLICY, ACADEMY_STAGE_5_3D_STATES, ACADEMY_STAGE_5_ACTIVITY_PRESENTATIONS,
  ACADEMY_STAGE_5_ANCHOR_IDS, ACADEMY_STAGE_5_ASSEMBLY_PLAN, ACADEMY_STAGE_5_CATALOG,
  ACADEMY_STAGE_5_CHAIN_TEMPLATES, ACADEMY_STAGE_5_CLAIMS, ACADEMY_STAGE_5_DOCUMENT_AUTHORITY,
  ACADEMY_STAGE_5_DOSSIER_SECTIONS, ACADEMY_STAGE_5_FINAL_CHECKPOINT, ACADEMY_STAGE_5_FORMULAS,
  ACADEMY_STAGE_5_INTEGRATION_REFS, ACADEMY_STAGE_5_INTERFACE_SEEDS, ACADEMY_STAGE_5_INTERFERENCE_TEMPLATES,
  ACADEMY_STAGE_5_METHOD_SELF_REVIEW, ACADEMY_STAGE_5_PARTIAL_RESOLUTIONS, ACADEMY_STAGE_5_PERSONAL_PRACTICES,
  ACADEMY_STAGE_5_PHOTO_BRIEFS, ACADEMY_STAGE_5_PREREQUISITE_OVERRIDES, ACADEMY_STAGE_5_REUSED_VISUALS,
  ACADEMY_STAGE_5_SUPPORT_IDS, ACADEMY_STAGE_5_TRANSITIONS, ACADEMY_STAGE_5_VISUAL_DESIGNS,
  ACADEMY_STAGE_5_VISUAL_QUESTION_COVERAGE, CURRENT_ACADEMY_CURATION_PHASE,
  academy014KContentPreservation, buildIntegrationDossier, createIntegrationProject,
} from '../src/learning/academy/reader/academyPersonalCurriculum'
import { buildAcademyReaderDocument, validateAcademyReaderDocument } from '../src/learning/academy/reader/academyReaderDocument'
import type { AcademyReaderBuildInput, AcademyReaderCurationPhase } from '../src/learning/academy/reader/academyReaderModel'
import type { LearningPack } from '../src/learning/content/learningPack'
import { createLearningProductIndex, mergeLearningProductIndexes } from '../src/learning/product/demoPackage'
import { ACADEMY_LEARNER_PATH, ACADEMY_PLANNED_CONTENT, ACADEMY_STAGE_5_PLANNED_REFS } from '../src/learning/academy/path/academyLearnerPath'
import { loadAcademyCorpus } from './academy-audit/corpus'
import { ACADEMY_014K_QA_CASES, ACADEMY_014K_QA_VIEWPORTS } from './academy-audit/academy-014k-qa-snapshot'

export const ACADEMY_014K_OUTPUT_FILES = [
  'ACADEMY-0.14K-SUMMARY.md',
  'ACADEMY-STAGE-5-CURATION-0.14K.md','ACADEMY-STAGE-5-CURATION-0.14K.json',
  'ACADEMY-STAGE-5-CONTENT-PRESERVATION-0.14K.md','ACADEMY-STAGE-5-CONTENT-PRESERVATION-0.14K.json',
  'ACADEMY-STAGE-5-SECTION-DISPOSITION-0.14K.md','ACADEMY-STAGE-5-SECTION-DISPOSITION-0.14K.json',
  'ACADEMY-STAGE-5-PLANNED-REF-RESOLUTION-0.14K.md','ACADEMY-STAGE-5-PLANNED-REF-RESOLUTION-0.14K.json',
  'ACADEMY-STAGE-5-PARTIAL-RESOLUTION-0.14K.md','ACADEMY-STAGE-5-PARTIAL-RESOLUTION-0.14K.json',
  'ACADEMY-STAGE-5-INTEGRATION-PROJECT-0.14K.md','ACADEMY-STAGE-5-INTEGRATION-PROJECT-0.14K.json',
  'ACADEMY-STAGE-5-DOCUMENT-AUTHORITY-0.14K.md','ACADEMY-STAGE-5-DOCUMENT-AUTHORITY-0.14K.json',
  'ACADEMY-STAGE-5-COMPATIBILITY-MATRIX-0.14K.md','ACADEMY-STAGE-5-COMPATIBILITY-MATRIX-0.14K.json',
  'ACADEMY-STAGE-5-DIMENSIONAL-CHAINS-0.14K.md','ACADEMY-STAGE-5-DIMENSIONAL-CHAINS-0.14K.json',
  'ACADEMY-STAGE-5-INTERFERENCES-0.14K.md','ACADEMY-STAGE-5-INTERFERENCES-0.14K.json',
  'ACADEMY-STAGE-5-ASSEMBLY-PLAN-0.14K.md','ACADEMY-STAGE-5-ASSEMBLY-PLAN-0.14K.json',
  'ACADEMY-STAGE-5-VISUALS-0.14K.md','ACADEMY-STAGE-5-VISUALS-0.14K.json',
  'ACADEMY-STAGE-5-3D-STATES-0.14K.md','ACADEMY-STAGE-5-3D-STATES-0.14K.json',
  'ACADEMY-STAGE-5-ACTIVITIES-0.14K.md','ACADEMY-STAGE-5-ACTIVITIES-0.14K.json',
  'ACADEMY-STAGE-5-PRACTICES-0.14K.md','ACADEMY-STAGE-5-PRACTICES-0.14K.json',
  'ACADEMY-STAGE-5-CLAIMS-0.14K.md','ACADEMY-STAGE-5-CLAIMS-0.14K.json',
  'ACADEMY-PERSONAL-REVIEW-QUEUE-0.14K.md','ACADEMY-PERSONAL-REVIEW-QUEUE-0.14K.json',
  'ACADEMY-UX-QA-0.14K.md','ACADEMY-SCREENSHOT-INDEX-0.14K.md',
] as const

export const ACADEMY_014K_BASELINE = {
  initialCommit:'137e47b390cd57696f68a12a5c3f18b0641afe76',
  corpusCounts:{packages:8,routes:24,modules:217,lessons:222,activities:289},corpusDigest:'5098aef19660130a4ee6a08749e5aedcf99ecb3ad15f9acffe7bdb034a4eae7f',
  protected:{learningContent:{count:4012,digest:'22e0330de012ea3ef53cd39beb104b4d5fcb9c78ae48763b11cf7639cce7888d'},originals:{count:7,digest:'633edd7f7027a61587b1b944b0b3bf8562819697144b449e4dc9aed1db4ab6b7'},historicalReports:{count:199,digest:'45865c5b5e84c4cee9d6ff9167da9bf608ca7c0b9c460a8241e39e6a85d2a156'}},
} as const

const sha256=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex')
const json=(value:unknown)=>`${JSON.stringify(value,null,2)}\n`
const md=(value:string)=>`${value.trim().replace(/[ \t]+$/gmu,'')}\n`
const pipe=(value:unknown)=>String(value??'—').replaceAll('|','\\|').replaceAll('\n','<br>')
const table=(headers:readonly string[],rows:readonly (readonly unknown[])[])=>[`| ${headers.join(' | ')} |`,`| ${headers.map(()=> '---').join(' | ')} |`,...rows.map((row)=>`| ${row.map(pipe).join(' | ')} |`)].join('\n')
async function walk(root:string):Promise<string[]>{const result:string[]=[];for(const name of(await readdir(root)).sort()){const path=join(root,name);const info=await stat(path);if(info.isDirectory())result.push(...await walk(path));else result.push(path)}return result}
async function treeSnapshot(root:string){const files=await walk(root);const rows=await Promise.all(files.map(async(file)=>`${relative(root,file).replaceAll('\\','/')}:${sha256(await readFile(file))}`));return{count:files.length,digest:sha256(rows.join('\n'))}}
async function historicalSnapshot(repositoryRoot:string){const root=join(repositoryRoot,'docs','generated');const names=(await readdir(root)).filter((name)=>!name.startsWith('APRENDER-')&&!/0\.14[K-Z]/i.test(name)).sort();const rows=await Promise.all(names.map(async(name)=>`${name}:${sha256(await readFile(join(root,name)))}`));return{count:names.length,digest:sha256(rows.join('\n'))}}
async function screenshotRows(repositoryRoot:string){const root=join(repositoryRoot,'docs','academy-ux','screenshots','0.14K');const names=await readdir(root).catch(()=>[]);return Promise.all(names.filter((name)=>name.endsWith('.png')).sort().map(async(fileName)=>{const content=await readFile(join(root,fileName));const qa=ACADEMY_014K_QA_CASES.find((item)=>item.fileName===fileName);return{fileName,bytes:content.byteLength,sha256:sha256(content),viewport:qa?.viewport??'unknown',panel:qa?.panel??'unknown',subject:qa?.subject??'unknown',fixture:true}}))}
function materialFor(pack:LearningPack,lessonId:string,product:ReturnType<typeof mergeLearningProductIndexes>):AcademyReaderBuildInput['material']{const lesson=pack.lessons.find(({id})=>id===lessonId);const descriptor=product.lessons.find(({id})=>id===lessonId);if(!lesson||!descriptor)throw new Error(`Lección ausente: ${lessonId}`);const blocks=pack.blocks.filter(({id})=>lesson.blockIds.includes(id));const markdown=blocks.map(({bodyMarkdown})=>bodyMarkdown).join('\n');const sourceIds=new Set([...(lesson.authoring?.sourceIds??[]),...blocks.flatMap(({claims})=>claims.flatMap(({sources})=>sources.map(({id})=>id)))]);return{packageId:pack.manifest.id,packageVersion:pack.manifest.packageVersion,pack,lesson,blocks,activities:descriptor.activityIds.flatMap((activityId)=>product.activities.filter(({id})=>id===activityId)),sources:pack.sources.filter(({id})=>sourceIds.has(id)),glossary:pack.glossary.filter(({id})=>markdown.includes(`{{term:${id}}}`))}}
function documentFor(product:ReturnType<typeof mergeLearningProductIndexes>,pack:LearningPack,lessonId:string,phase:AcademyReaderCurationPhase){const descriptor=product.lessons.find(({id})=>id===lessonId)!;return buildAcademyReaderDocument({material:materialFor(pack,lessonId,product),title:descriptor.title.es,purpose:descriptor.purpose.es,locale:'es-ES',requiredActivityIds:descriptor.studyContract?.labActivityIds},{curationPhase:phase})}

export async function buildAcademy014KOutputs(repositoryRoot:string):Promise<Map<string,string>>{
  const corpus=await loadAcademyCorpus(repositoryRoot);const product=mergeLearningProductIndexes(corpus.packs.map(({pack})=>createLearningProductIndex(pack)));const packByLesson=new Map(corpus.packs.flatMap(({pack})=>pack.lessons.map(({id})=>[id,pack]as const)))
  const learningContent=await treeSnapshot(join(repositoryRoot,'learning-content'));const originals=await treeSnapshot(join(repositoryRoot,'reference-library','originals'));const historical=await historicalSnapshot(repositoryRoot);const screenshots=await screenshotRows(repositoryRoot)
  if(CURRENT_ACADEMY_CURATION_PHASE!=='0.14K')throw new Error('0.14K no es la fase activa.')
  if(Object.entries(ACADEMY_014K_BASELINE.corpusCounts).some(([key,value])=>corpus.counts[key as keyof typeof corpus.counts]!==value)||corpus.digest!==ACADEMY_014K_BASELINE.corpusDigest)throw new Error('El corpus cambió.')
  if(JSON.stringify(learningContent)!==JSON.stringify(ACADEMY_014K_BASELINE.protected.learningContent))throw new Error('learning-content cambió.')
  if(JSON.stringify(originals)!==JSON.stringify(ACADEMY_014K_BASELINE.protected.originals))throw new Error('originals cambió.')
  if(JSON.stringify(historical)!==JSON.stringify(ACADEMY_014K_BASELINE.protected.historicalReports))throw new Error('Los informes 0.14A–0.14J cambiaron.')
  const documents=ACADEMY_STAGE_5_CATALOG.map((item)=>{const pack=packByLesson.get(item.lessonId);if(!pack)throw new Error(`Paquete ausente: ${item.lessonId}`);const authored=documentFor(product,pack,item.lessonId,'0.14D');const visible=documentFor(product,pack,item.lessonId,'0.14K');const preservation=academy014KContentPreservation(item.lessonId,authored.sections,visible.sections);return{item,authored,visible,preservation,validationIssues:validateAcademyReaderDocument(visible)}})
  if(documents.some(({validationIssues})=>validationIssues.length))throw new Error(`La documentación de etapa 5 no valida: ${documents.flatMap(({validationIssues})=>validationIssues).join('; ')}`)
  if(documents.some(({preservation})=>preservation.row.substantiveCoverage!==1))throw new Error('La cobertura sustantiva de etapa 5 no alcanza 100 %.')
  const dispositions=documents.flatMap(({preservation})=>preservation.dispositions);const preservationRows=documents.map(({preservation})=>preservation.row)
  const fixture=createIntegrationProject('profile.report-fixture','2026-08-16T12:00:00.000Z','fixture.report.stage5');const dossier=buildIntegrationDossier(fixture)
  const outputs=new Map<string,string>();const addPair=(base:string,payload:unknown,title:string,body:string)=>{outputs.set(`${base}.json`,json(payload));outputs.set(`${base}.md`,md(`# ${title}\n\n${body}`))}
  addPair('ACADEMY-STAGE-5-CURATION-0.14K',{schema:'wplab-stage5-curation-v1',phase:'0.14K',curriculumStatus:'complete-method',readerPhases:ACADEMY_READER_CURATION_PHASES,personalPhases:ACADEMY_PERSONAL_CURATION_PHASES,counts:{chapters:5,lessons:16,anchors:ACADEMY_STAGE_5_ANCHOR_IDS.length,supports:ACADEMY_STAGE_5_SUPPORT_IDS.length,visibleSections:documents.reduce((sum,{visible})=>sum+visible.sections.length,0)},pathStage:ACADEMY_LEARNER_PATH.stages.find(({stageId})=>stageId==='stage.5'),transitions:ACADEMY_STAGE_5_TRANSITIONS,prerequisites:ACADEMY_STAGE_5_PREREQUISITE_OVERRIDES,checkpoint:ACADEMY_STAGE_5_FINAL_CHECKPOINT,lessons:documents.map(({item,visible})=>({...item,visibleSectionCount:visible.sections.length,contentHash:visible.contentHash}))},'Curación completa de etapa 5 · 0.14K',table(['Capítulo','Lección','Rol','Método'],ACADEMY_STAGE_5_CATALOG.map((item)=>[item.chapterId,item.lessonId,item.pathRole,'complete-method'])))
  addPair('ACADEMY-STAGE-5-CONTENT-PRESERVATION-0.14K',{schema:'wplab-stage5-preservation-v1',phase:'0.14K',counts:{lessons:16,sourceSections:preservationRows.reduce((sum,row)=>sum+row.sourceSectionCount,0),sourceWords:preservationRows.reduce((sum,row)=>sum+row.sourceSubstantiveWords,0),visibleWords:preservationRows.reduce((sum,row)=>sum+row.visibleWords,0),substantiveCoverage:Math.min(...preservationRows.map(({substantiveCoverage})=>substantiveCoverage))},lessons:preservationRows},'Preservación de contenido · etapa 5 · 0.14K',table(['Lección','Secciones fuente','Palabras fuente','Palabras visibles','Cobertura'],preservationRows.map((row)=>[row.lessonId,row.sourceSectionCount,row.sourceSubstantiveWords,row.visibleWords,`${row.substantiveCoverage*100} %`])))
  addPair('ACADEMY-STAGE-5-SECTION-DISPOSITION-0.14K',{schema:'wplab-stage5-disposition-v1',phase:'0.14K',counts:{total:dispositions.length,retained:dispositions.filter(({action})=>action==='retained').length},dispositions},'Disposición de secciones fuente · etapa 5 · 0.14K',table(['Lección','Sección','Acción','Targets'],dispositions.map((row)=>[row.lessonId,row.sourceSectionId,row.action,row.targetSectionIds.join(', ')])))
  addPair('ACADEMY-STAGE-5-PLANNED-REF-RESOLUTION-0.14K',{schema:'wplab-stage5-ref-resolution-v1',phase:'0.14K',historicalIds:ACADEMY_STAGE_5_PLANNED_REFS,counts:{refs:ACADEMY_STAGE_5_INTEGRATION_REFS.length,implementedMethod:ACADEMY_STAGE_5_INTEGRATION_REFS.filter(({curriculumResolutionStatus})=>curriculumResolutionStatus==='implemented-method').length,projectSourceNeeded:ACADEMY_STAGE_5_INTEGRATION_REFS.filter(({projectDataStatus})=>projectDataStatus==='source-needed').length},resolutions:ACADEMY_STAGE_5_INTEGRATION_REFS},'Resolución de refs históricos · etapa 5 · 0.14K',table(['Ref','Currículo','Proyecto','Lecciones'],ACADEMY_STAGE_5_INTEGRATION_REFS.map((row)=>[row.ref,row.curriculumResolutionStatus,row.projectDataStatus,row.resolvedByLessonIds.join(', ')])))
  addPair('ACADEMY-STAGE-5-PARTIAL-RESOLUTION-0.14K',{schema:'wplab-stage5-partials-v1',phase:'0.14K',counts:{partials:ACADEMY_STAGE_5_PARTIAL_RESOLUTIONS.length,implementedMethod:ACADEMY_STAGE_5_PARTIAL_RESOLUTIONS.length},resolutions:ACADEMY_STAGE_5_PARTIAL_RESOLUTIONS},'Cierre de temas parciales · etapa 5 · 0.14K',table(['Ref','Estado','Lecciones','Dossier'],ACADEMY_STAGE_5_PARTIAL_RESOLUTIONS.map((row)=>[row.ref,row.status,row.lessonIds.join(', '),row.dossierSection])))
  addPair('ACADEMY-STAGE-5-INTEGRATION-PROJECT-0.14K',{schema:'wplab-stage5-integration-project-contract-v1',phase:'0.14K',persistence:{local:true,profileIsolated:true,coordinatedAcademyState:true,networkRequired:false,export:'validated-json',import:'schema-validated',versionConflicts:'preserve-copy'},fixture,dossier},'Contrato del proyecto personal · etapa 5 · 0.14K','Entidad compañera enlazable a `WatchProject`: reutiliza el perfil y la coordinación durable de Academia; añade autoridad, dimensiones, interfaces y dossier sin duplicar geometría 3D. El fixture del informe no contiene datos personales.')
  addPair('ACADEMY-STAGE-5-DOCUMENT-AUTHORITY-0.14K',{schema:'wplab-stage5-document-authority-v1',phase:'0.14K',policy:ACADEMY_STAGE_5_DOCUMENT_AUTHORITY},'Autoridad documental · etapa 5 · 0.14K','Visual-match-only, estimación y fuente secundaria no se elevan. Toda dimensión conserva aplicabilidad, datum, unidad y verificación.')
  addPair('ACADEMY-STAGE-5-COMPATIBILITY-MATRIX-0.14K',{schema:'wplab-stage5-compatibility-v1',phase:'0.14K',counts:{interfaces:ACADEMY_STAGE_5_INTERFACE_SEEDS.length},interfaces:ACADEMY_STAGE_5_INTERFACE_SEEDS},'Matriz de compatibilidad · etapa 5 · 0.14K',table(['Interfaz','Componentes','Método','Datos requeridos'],ACADEMY_STAGE_5_INTERFACE_SEEDS.map((row)=>[row.interfaceId,`${row.componentA} ↔ ${row.componentB}`,row.checkMethod,row.requiredData.join(', ')])))
  addPair('ACADEMY-STAGE-5-DIMENSIONAL-CHAINS-0.14K',{schema:'wplab-stage5-chains-v1',phase:'0.14K',rules:{unknownIsZero:false,datumRequiredForHeights:true,negativeMargin:'conflict-found',derivedInputsPreserved:true},chains:ACADEMY_STAGE_5_CHAIN_TEMPLATES},'Cadenas dimensionales · etapa 5 · 0.14K',table(['Cadena','Datum','Dirección','Miembros'],ACADEMY_STAGE_5_CHAIN_TEMPLATES.map((row)=>[row.chainId,row.datum,row.direction,row.members.map(({role})=>role).join(' → ')])))
  addPair('ACADEMY-STAGE-5-INTERFERENCES-0.14K',{schema:'wplab-stage5-interferences-v1',phase:'0.14K',boundary:'no-conflict-in-represented-model is not physical compatibility',checks:ACADEMY_STAGE_5_INTERFERENCE_TEMPLATES},'Interferencias · etapa 5 · 0.14K',table(['Check','Clase','Evaluados','Omitidos'],ACADEMY_STAGE_5_INTERFERENCE_TEMPLATES.map((row)=>[row.checkId,row.kind,row.statesEvaluated.join(', '),row.statesOmitted.join(', ')])))
  addPair('ACADEMY-STAGE-5-ASSEMBLY-PLAN-0.14K',{schema:'wplab-stage5-assembly-plan-v1',phase:'0.14K',physicalExecution:false,universalSequence:false,steps:ACADEMY_STAGE_5_ASSEMBLY_PLAN,dossierSections:ACADEMY_STAGE_5_DOSSIER_SECTIONS},'Plan de montaje · etapa 5 · 0.14K',table(['Orden','Paso','Checkpoint','Detener'],ACADEMY_STAGE_5_ASSEMBLY_PLAN.map((row)=>[row.order,row.title,row.checkpoint,row.stopCondition])))
  addPair('ACADEMY-STAGE-5-VISUALS-0.14K',{schema:'wplab-stage5-visuals-v1',phase:'0.14K',counts:{reused:ACADEMY_STAGE_5_REUSED_VISUALS.length,new:ACADEMY_STAGE_5_VISUAL_DESIGNS.length,questions:ACADEMY_STAGE_5_VISUAL_QUESTION_COVERAGE.length,photoBriefs:ACADEMY_STAGE_5_PHOTO_BRIEFS.length},reusedVisualIds:ACADEMY_STAGE_5_REUSED_VISUALS,newDesigns:ACADEMY_STAGE_5_VISUAL_DESIGNS,questionCoverage:ACADEMY_STAGE_5_VISUAL_QUESTION_COVERAGE,photoBriefs:ACADEMY_STAGE_5_PHOTO_BRIEFS},'Visuales · etapa 5 · 0.14K',`Se reutiliza ${ACADEMY_STAGE_5_REUSED_VISUALS.length} visual existente y se implementan ${ACADEMY_STAGE_5_VISUAL_DESIGNS.length} diagramas semánticos originales para ${ACADEMY_STAGE_5_VISUAL_QUESTION_COVERAGE.length} preguntas. Los ${ACADEMY_STAGE_5_PHOTO_BRIEFS.length} briefs no cuentan como visuales implementados.`)
  addPair('ACADEMY-STAGE-5-3D-STATES-0.14K',{schema:'wplab-stage5-3d-v1',phase:'0.14K',policy:ACADEMY_STAGE_5_3D_POLICY,states:ACADEMY_STAGE_5_3D_STATES},'Estados 3D/CAD · etapa 5 · 0.14K','Todos los checks comienzan input-incomplete. No hay cotas por defecto, escala física del fixture 8215 ni afirmación de compatibilidad.')
  addPair('ACADEMY-STAGE-5-ACTIVITIES-0.14K',{schema:'wplab-stage5-activities-v1',phase:'0.14K',counts:{presentations:ACADEMY_STAGE_5_ACTIVITY_PRESENTATIONS.length,corpusActivities:corpus.counts.activities,physicalEvidenceClaims:0},presentations:ACADEMY_STAGE_5_ACTIVITY_PRESENTATIONS},'Actividades curriculares · etapa 5 · 0.14K',table(['Actividad','Lección','Evidencia','P'],ACADEMY_STAGE_5_ACTIVITY_PRESENTATIONS.map((row)=>[row.activityId,row.lessonId,row.evidenceProfile.modalities.join('+'),row.evidenceProfile.physicalExecutionRequired])))
  addPair('ACADEMY-STAGE-5-PRACTICES-0.14K',{schema:'wplab-stage5-practices-v1',phase:'0.14K',counts:{practices:ACADEMY_STAGE_5_PERSONAL_PRACTICES.length,affectsProgress:0,createsMastery:0,completesLesson:0},practices:ACADEMY_STAGE_5_PERSONAL_PRACTICES},'Prácticas personales · etapa 5 · 0.14K',table(['Práctica','Lecciones','Certificación'],ACADEMY_STAGE_5_PERSONAL_PRACTICES.map((row)=>[row.personalPracticeId,row.lessonIds.join(', '),row.certificationStatus])))
  addPair('ACADEMY-STAGE-5-CLAIMS-0.14K',{schema:'wplab-stage5-claims-v1',phase:'0.14K',counts:{claims:ACADEMY_STAGE_5_CLAIMS.length,numericClaims:0,formulas:ACADEMY_STAGE_5_FORMULAS.length},claims:ACADEMY_STAGE_5_CLAIMS,formulas:ACADEMY_STAGE_5_FORMULAS},'Claims y fórmulas · etapa 5 · 0.14K',table(['Claim','Lección','Autoridad','Límite'],ACADEMY_STAGE_5_CLAIMS.map((row)=>[row.claimId,row.lessonId,row.authority,row.limitations.join('; ')])))
  addPair('ACADEMY-PERSONAL-REVIEW-QUEUE-0.14K',{schema:'wplab-personal-review-queue-v5',phase:'0.14K',counts:{unique:ACADEMY_PERSONAL_REVIEW_QUEUE_014K.length,stage5:ACADEMY_STAGE_5_CATALOG.filter(({lessonId})=>ACADEMY_PERSONAL_REVIEW_QUEUE_014K.some((row)=>row.lessonId===lessonId)).length,methodSelfReview:ACADEMY_STAGE_5_METHOD_SELF_REVIEW.length},queue:ACADEMY_PERSONAL_REVIEW_QUEUE_014K,methodSelfReview:ACADEMY_STAGE_5_METHOD_SELF_REVIEW},'Cola de revisión personal · 0.14K',`Las 16 lecciones están deduplicadas por lessonId. La auto-revisión del método tiene ${ACADEMY_STAGE_5_METHOD_SELF_REVIEW.length} aspectos y no certifica competencia.`)
  outputs.set('ACADEMY-UX-QA-0.14K.md',md(`# QA de experiencia · 0.14K\n\nViewports: ${ACADEMY_014K_QA_VIEWPORTS.join(', ')}. Casos previstos: ${ACADEMY_014K_QA_CASES.length}; capturas encontradas: ${screenshots.length}. Fixture explícito, local, sin datos privados ni validación humana simulada. El QA de navegador se registra separadamente de los tests automatizados.`))
  outputs.set('ACADEMY-SCREENSHOT-INDEX-0.14K.md',md(`# Índice de capturas · 0.14K\n\nDirectorio: \`docs/academy-ux/screenshots/0.14K/\`.\n\n${table(['Archivo','Viewport','Panel','Estado','Asunto','SHA-256'],ACADEMY_014K_QA_CASES.map((qa)=>{const shot=screenshots.find(({fileName})=>fileName===qa.fileName);return[qa.fileName,qa.viewport,qa.panel,qa.status,qa.subject,shot?.sha256??'pendiente']}))}`))
  outputs.set('ACADEMY-0.14K-SUMMARY.md',md(`# Watch Prototype Lab 0.14K · resumen\n\n- Baseline protegido: 8 paquetes, 24 rutas, 217 módulos, 222 lecciones y 289 actividades.\n- Etapa 5: 5 capítulos, 12 anchors, 4 supports y 16 lecciones curadas.\n- Resolución: 8 refs históricos y 5 parciales con método; los datos de cada proyecto siguen separados.\n- Proyecto: local, por perfil, versionado, exportable e importable con validación.\n- Compatibilidad: ${ACADEMY_STAGE_5_INTERFACE_SEEDS.length} interfaces, 5 cadenas y ${ACADEMY_STAGE_5_INTERFERENCE_TEMPLATES.length} checks.\n- Evidencia: K/V/R; ninguna actividad digital produce P.\n\n0.14K cierra pedagógicamente la etapa 5 sin afirmar que un reloj físico haya sido montado o validado.`))
  if(outputs.size!==ACADEMY_014K_OUTPUT_FILES.length||[...outputs.keys()].some((name)=>!ACADEMY_014K_OUTPUT_FILES.includes(name as typeof ACADEMY_014K_OUTPUT_FILES[number])))throw new Error(`El contrato exige ${ACADEMY_014K_OUTPUT_FILES.length} salidas.`)
  if(ACADEMY_PLANNED_CONTENT.some(({ref,status})=>ACADEMY_STAGE_5_PLANNED_REFS.includes(ref)&&status!=='implemented-method'))throw new Error('Algún ref histórico no está resuelto por método.')
  return outputs
}

async function main(){const repositoryRoot=resolve(process.cwd());const outputs=await buildAcademy014KOutputs(repositoryRoot);const root=join(repositoryRoot,'docs','generated');const check=process.argv.includes('--check');if(!check){await mkdir(root,{recursive:true});await Promise.all([...outputs].map(([name,content])=>writeFile(join(root,name),content,'utf8')));console.log(`Academia 0.14K: ${outputs.size} informes generados.`);return}const mismatches:string[]=[];for(const[name,content]of outputs){const existing=await readFile(join(root,name),'utf8').catch(()=>null);if(existing!==content)mismatches.push(name)}if(mismatches.length)throw new Error(`Salidas 0.14K desactualizadas: ${mismatches.join(', ')}`);console.log(`Academia 0.14K: ${outputs.size} informes verificados.`)}
const invoked=process.argv[1]?pathToFileURL(resolve(process.argv[1])).href:'';if(import.meta.url===invoked)main().catch((error)=>{console.error(error);process.exitCode=1})
