import type { AcademyCurriculumPathRole } from '../types'
import { academyStage3EditorialContract, type AcademyStage3EditorialContract } from './stage3EditorialContracts'

export interface AcademyStage3CatalogEntry extends AcademyStage3EditorialContract {
  lessonId: string
  chapterId: 'chapter.3.1' | 'chapter.3.2' | 'chapter.3.3' | 'chapter.3.4'
  pathRole: AcademyCurriculumPathRole
  centralQuestion: string
  observableOutcome: string
  editorialFocus: string
  workedExample: string
  sourceScope: string
  requiredActivityId?: string
  visualDesignIds: readonly string[]
}

type Source = Omit<AcademyStage3CatalogEntry, keyof AcademyStage3EditorialContract>
const entry = (value: Source): AcademyStage3CatalogEntry => ({ ...value, ...academyStage3EditorialContract(value.lessonId) })

export const ACADEMY_STAGE_3_CATALOG: readonly AcademyStage3CatalogEntry[] = [
  entry({ lessonId: 'lesson.metrology.observe-before-measuring', chapterId: 'chapter.3.1', pathRole: 'anchor', requiredActivityId: 'activity.metrology.preparar-una-inspeccion', visualDesignIds: ['visual.metrology.observe-first.v1'], centralQuestion: '¿Qué puedes afirmar antes de medir o intervenir?', observableOutcome: 'Separar observación, identificación, inferencia, hipótesis y diagnóstico.', editorialFocus: 'Una observación describe algo comprobable bajo condiciones declaradas; la identificación nombra provisionalmente, la inferencia interpreta, la hipótesis se abre a prueba y el diagnóstico exige evidencia suficiente.', workedExample: '“Franja brillante bajo luz rasante” conserva la apariencia; “desgaste” queda como hipótesis hasta una comprobación que pueda refutarla.', sourceScope: 'VIM y GUM aportan vocabulario metrológico; el ejemplo es educativo y no diagnostica una pieza.' }),
  entry({ lessonId: 'lesson.metrology.inspection-findings', chapterId: 'chapter.3.1', pathRole: 'anchor', requiredActivityId: 'activity.metrology.registrar-hallazgo', visualDesignIds: ['visual.stage3.finding-record.v1'], centralQuestion: '¿Cómo se registra un hallazgo sin perder evidencia ni incertidumbre?', observableOutcome: 'Crear un registro reproducible con hipótesis rivales y siguiente comprobación.', editorialFocus: 'El hallazgo identifica objeto, zona, condición, medio, escala o aumento, evidencia, explicaciones posibles, dato ausente, confianza, incertidumbre y siguiente comprobación.', workedExample: 'En vez de “pieza dañada”, registra la zona y la condición observable, conserva la imagen propia y anota qué observación distinguiría dos causas.', sourceScope: 'Estructura editorial original apoyada en vocabulario metrológico; no fija una taxonomía universal de defectos.' }),
  entry({ lessonId: 'lesson.encyclopedia.service-tribology.recepcion-y-linea-base', chapterId: 'chapter.3.1', pathRole: 'anchor', requiredActivityId: 'activity.encyclopedia.service-tribology.recepcion-y-linea-base', visualDesignIds: ['visual.intake.baseline-sequence.v1'], centralQuestion: '¿Qué estado debe conservarse antes de una prueba que pueda alterarlo?', observableOutcome: 'Registrar recepción, historia, estado y una decisión segura antes de abrir.', editorialFocus: 'La línea base reúne identificación, exterior, funciones observables, daños, fotografías propias, intervenciones conocidas, desconocidos y la decisión de probar o detenerse.', workedExample: 'Si dar cuerda puede agravar una condición desconocida, el registro se cierra como “no probado todavía” y conserva la razón.', sourceScope: 'Método general; no es protocolo comercial ni impone una prueba universal.' }),
  entry({ lessonId: 'lesson.encyclopedia.service-tribology.tm-inspeccion-previa', chapterId: 'chapter.3.1', pathRole: 'optional-branch', visualDesignIds: ['visual.stage3.historical-boundary.v1'], centralQuestion: '¿Qué conserva vigencia del orden histórico de inspección y qué no?', observableOutcome: 'Extraer el hábito de observar antes de desmontar sin importar normas de 1945.', editorialFocus: 'El TM ordena exterior, caja, esfera, cuerda, puesta en hora, agujas, balance, tren visible, historia y marcha dentro de su contexto militar.', workedExample: 'La secuencia orienta dónde mirar; una cifra, sustancia o aceptación del manual permanece histórica hasta corroboración moderna y aplicable.', sourceScope: 'TM 9-1575, sección III, páginas impresas 20–22; fuente histórica, no autoridad moderna de seguridad o tolerancias.' }),
  entry({ lessonId: 'lesson.metrology.units-scale-resolution', chapterId: 'chapter.3.2', pathRole: 'anchor', requiredActivityId: 'activity.metrology.diferenciar-resolucion-y-precision', visualDesignIds: ['visual.stage3.measurement-terms.v1'], centralQuestion: '¿Qué relación existe entre magnitud, unidad, escala, resolución y resultado?', observableOutcome: 'Declarar una medición sin equiparar resolución, precisión, exactitud, incertidumbre o tolerancia.', editorialFocus: 'La magnitud define qué se mide; la unidad comunica el valor; la resolución limita el incremento legible. Precisión describe repetición, exactitud relación con una referencia e incertidumbre la duda razonada.', workedExample: 'Mostrar más dígitos no demuestra que el resultado esté más cerca de una referencia ni que cumpla una tolerancia.', sourceScope: 'VIM JCGM 200:2012; no se importan especificaciones de instrumentos concretos.' }),
  entry({ lessonId: 'lesson.metrology.instruments', chapterId: 'chapter.3.2', pathRole: 'anchor', requiredActivityId: 'activity.metrology.seleccionar-instrumento', visualDesignIds: ['visual.stage3.instrument-choice.v1'], centralQuestion: '¿Qué instrumento responde a la pregunta con el menor riesgo razonable?', observableOutcome: 'Elegir por magnitud, rango, resolución, geometría, acceso, fuerza, superficie y referencia.', editorialFocus: 'La tarea gobierna la selección. Cero, datum, alineación, paralaje, fuerza de medición, temperatura y repetibilidad se declaran cuando afectan el resultado.', workedExample: 'Un instrumento con más dígitos puede ser peor si no accede a la geometría o aplica una fuerza que altera la pieza.', sourceScope: 'Principios metrológicos generales; disponibilidad, resolución y calibración reales deben comprobarse en el instrumento usado.' }),
  entry({ lessonId: 'lesson.metrology.physical-measurement', chapterId: 'chapter.3.2', pathRole: 'anchor', requiredActivityId: 'activity.metrology.medir-diametro', visualDesignIds: ['visual.stage3.repeat-measurement.v1'], centralQuestion: '¿Cómo se obtiene una serie defendible sin inventar valor verdadero?', observableOutcome: 'Registrar método, unidad, referencia, lecturas repetidas e incertidumbre.', editorialFocus: 'Una captura digital puede aportar K/R; solo una ejecución física explícita aporta P. R no sustituye P y la ruta conceptual puede avanzar sin certificar manipulación.', workedExample: 'Tres lecturas se conservan como serie con orientación y método; su dispersión informa repetibilidad, no demuestra exactitud.', sourceScope: 'Práctica metrológica educativa; no certifica calibración ni habilidad física.' }),
  entry({ lessonId: 'lesson.metrology.precision-accuracy-uncertainty', chapterId: 'chapter.3.2', pathRole: 'support', visualDesignIds: ['visual.stage3.measurement-terms.v1'], centralQuestion: '¿Por qué una serie agrupada puede seguir siendo inexacta?', observableOutcome: 'Distinguir precisión, exactitud, repetibilidad, reproducibilidad, error e incertidumbre.', editorialFocus: 'La repetibilidad mantiene condiciones; la reproducibilidad cambia condiciones declaradas. La exactitud necesita referencia adecuada y no se expresa como un número aislado de “exactitud”.', workedExample: 'Lecturas muy juntas pueden compartir el mismo sesgo; la poca dispersión no demuestra proximidad a la referencia.', sourceScope: 'VIM y GUM; no se introduce propagación estadística avanzada como requisito inicial.' }),
  entry({ lessonId: 'lesson.metrology.compare-data', chapterId: 'chapter.3.2', pathRole: 'support', visualDesignIds: ['visual.stage3.comparability.v1'], centralQuestion: '¿Cuándo dos números describen resultados comparables?', observableOutcome: 'Comprobar magnitud, unidad, datum, método, condición, orientación, redondeo e incertidumbre.', editorialFocus: 'Compartir unidad no basta: las definiciones del mensurando y las condiciones deben permitir la misma interpretación.', workedExample: 'Dos diámetros en milímetros no se comparan si uno usa otra zona, orientación o referencia.', sourceScope: 'Comparación metrológica general; no crea tolerancias de aceptación.' }),
  entry({ lessonId: 'lesson.horology.failure-prediction', chapterId: 'chapter.3.3', pathRole: 'anchor', requiredActivityId: 'activity.horology.justify-hypothesis', visualDesignIds: ['visual.failure-prediction.hypothesis.v1'], centralQuestion: '¿Qué prueba separa causas plausibles de un mismo síntoma?', observableOutcome: 'Formular hipótesis rivales, predecir resultados y actualizar confianza.', editorialFocus: 'El síntoma abre candidatos; una prueba discriminante resulta útil cuando posibles resultados favorecen o debilitan hipótesis diferentes.', workedExample: 'Si la indicación no avanza, “roce” y “transmisión interrumpida” predicen observaciones distintas; repetir el síntoma no las separa.', sourceScope: 'Mapa funcional original y simulación V; no diagnostica una unidad física.' }),
  entry({ lessonId: 'lesson.encyclopedia.service-tribology.diagnostico-y-control-final', chapterId: 'chapter.3.3', pathRole: 'anchor', requiredActivityId: 'activity.encyclopedia.service-tribology.diagnostico-y-control-final', visualDesignIds: ['visual.diagnosis.final-control.v1', 'visual.stage3.acceptance-authority.v1'], centralQuestion: '¿Cómo se separa una conclusión causal de la aceptación del resultado?', observableOutcome: 'Vincular diagnóstico, intervención propuesta, control final y autoridad del criterio.', editorialFocus: 'El diagnóstico orienta una decisión; el control final comprueba un criterio declarado. Un resultado satisfactorio no demuestra por sí solo la causa original.', workedExample: 'Si una función reaparece, registra el cambio y la incertidumbre residual; no reescribas la hipótesis inicial como certeza retrospectiva.', sourceScope: 'Método general; criterios numéricos dependen de fabricante, diseño o fuente actual aplicable.' }),
  entry({ lessonId: 'lesson.encyclopedia.service-tribology.tm-diagnostico-sintomas', chapterId: 'chapter.3.3', pathRole: 'anchor', requiredActivityId: 'activity.encyclopedia.service-tribology.tm-diagnostico-sintomas', visualDesignIds: ['visual.diagnosis.tm-symptom-tree.v1'], centralQuestion: '¿Qué puede aprenderse de un árbol histórico de síntomas sin copiar sus recetas?', observableOutcome: 'Usar subsistemas y pruebas como patrón histórico no accionable.', editorialFocus: 'El TM conecta síntomas, causas candidatas e inspección por subsistemas; sus sustancias, intervalos, tolerancias y ajustes permanecen fuera de la práctica vigente.', workedExample: 'Conserva “síntoma → candidatos → comprobación” y omite cualquier receta de época; una operación real necesitaría documentación moderna.', sourceScope: 'TM 9-1575, páginas impresas 44–83; contexto militar de 1945 y corroboración moderna obligatoria para operación.' }),
  entry({ lessonId: 'lesson.encyclopedia.atlas-restoration-design.tm-hamilton-992b', chapterId: 'chapter.3.3', pathRole: 'optional-branch', visualDesignIds: [], centralQuestion: '¿Cómo limita la identificación la transferencia de un caso histórico?', observableOutcome: 'Conservar calibre, revisión y alcance al comparar un expediente.', editorialFocus: 'El caso no exige modelo V, presupuesto de error ni arquitectura moderna como prerrequisitos; esos marcos solo pueden aparecer como comparación posterior opcional.', workedExample: 'Que dos relojes compartan marca o tamaño no autoriza piezas, secuencia o aceptación equivalentes.', sourceScope: 'TM 9-1575, Hamilton 992B, páginas impresas 84–116; caso histórico específico.' }),
  entry({ lessonId: 'lesson.encyclopedia.service-tribology.limpieza-e-inspeccion', chapterId: 'chapter.3.4', pathRole: 'anchor', requiredActivityId: 'activity.encyclopedia.service-tribology.limpieza-e-inspeccion', visualDesignIds: ['visual.diagnosis.cleaning-inspection.v1'], centralQuestion: '¿Qué evidencia puede desaparecer al limpiar y qué justifica hacerlo?', observableOutcome: 'Documentar estado, objetivo, fuente, riesgo, control y parada antes de una limpieza.', editorialFocus: 'Limpiar no es el primer paso universal. Antes se conserva la condición, se identifica la evidencia que podría desaparecer y se comprueba material, acabado y fuente aplicable.', workedExample: 'Una marca propia se fotografía y describe antes de decidir si es contaminación, daño o dato todavía desconocido.', sourceScope: 'Decisión general no química; ninguna sustancia, tiempo, concentración o secuencia histórica se presenta como instrucción.' }),
  entry({ lessonId: 'lesson.encyclopedia.service-tribology.tribologia-y-lubricantes', chapterId: 'chapter.3.4', pathRole: 'anchor', requiredActivityId: 'activity.encyclopedia.service-tribology.tribologia-y-lubricantes', visualDesignIds: ['visual.tribology.contact-function.v1'], centralQuestion: '¿Qué debe conocerse del contacto antes de considerar lubricación?', observableOutcome: 'Relacionar superficies, movimiento, función, pérdidas y documentación sin prescribir producto.', editorialFocus: 'Contacto, movimiento relativo, carga, velocidad, contaminación, desgaste, exceso, defecto, migración y envejecimiento forman el problema; no determinan por sí solos un producto.', workedExample: 'Un punto, producto o cantidad concretos quedan “fuente necesaria” hasta existir documento oficial de calibre y variante con localizador.', sourceScope: 'Theory of Horology para principio general; fabricante actual para lubricación específica.' }),
  entry({ lessonId: 'lesson.encyclopedia.service-tribology.montaje-y-puntos-de-control', chapterId: 'chapter.3.4', pathRole: 'anchor', requiredActivityId: 'activity.encyclopedia.service-tribology.montaje-y-puntos-de-control', visualDesignIds: ['visual.assembly.control-gates.v1', 'visual.assembly.reasoned-example.v1', 'visual.stage3.acceptance-authority.v1'], centralQuestion: '¿Dónde se comprueba un montaje antes de que un error quede oculto?', observableOutcome: 'Planificar estado, acción, asiento, libertad, interacción, control, parada y registro.', editorialFocus: 'Los controles intermedios se colocan tras cada interfaz relevante. La aceptación declara si procede de fabricante, diseño, medición propia, criterio educativo, comparación histórica o desconocido.', workedExample: 'Si una pieza no asienta libremente, se detiene la secuencia y se revisa evidencia; no se fuerza para alcanzar el control final.', sourceScope: 'Patrón funcional, no secuencia universal ni montaje del MIYOTA 8215.' }),
  entry({ lessonId: 'lesson.advanced.service-clean-lube', chapterId: 'chapter.3.4', pathRole: 'optional-branch', visualDesignIds: [], centralQuestion: '¿Cómo se audita una decisión de servicio que depende de documentación específica?', observableOutcome: 'Separar necesidad, dato confirmado, riesgo, fuente y bloqueo.', editorialFocus: 'Una matriz de decisión puede ordenar pieza, material, contaminante, exclusiones, inspección y fuente sin recomendar un proceso concreto.', workedExample: 'Si falta documentación aplicable, el campo se mantiene bloqueado; una tabla de otro calibre solo enseña estructura documental.', sourceScope: 'Rama documental avanzada; no prescribe química, lubricantes o servicio físico.' }),
] as const

export const ACADEMY_STAGE_3_ANCHOR_IDS = ACADEMY_STAGE_3_CATALOG.filter(({ pathRole }) => pathRole === 'anchor').map(({ lessonId }) => lessonId)
export const ACADEMY_STAGE_3_SUPPORT_IDS = ACADEMY_STAGE_3_CATALOG.filter(({ pathRole }) => pathRole === 'support').map(({ lessonId }) => lessonId)
export const ACADEMY_STAGE_3_OPTIONAL_IDS = ACADEMY_STAGE_3_CATALOG.filter(({ pathRole }) => pathRole === 'optional-branch').map(({ lessonId }) => lessonId)
