import { academyStage3SectionId } from './stage3Sections'

export interface AcademyStage3ClaimAudit {
  claimId: string
  lessonId: string
  sectionId: string
  claimType: 'principle' | 'measurement' | 'diagnosis' | 'procedure' | 'safety' | 'historical-context'
  generalOrSpecific: 'general' | 'calibre-specific'
  primarySourceId: string
  supportingSourceIds: readonly string[]
  locator: string | null
  historicalStatus: 'current' | 'historical' | 'mixed'
  manufacturerApplicability: string
  scope: string
  limitations: readonly string[]
  verificationStatus: 'source-reviewed' | 'source-limited' | 'source-needed' | 'historical-only'
  decision: 'keep' | 'clarify' | 'narrow' | 'source-needed' | 'historical-only' | 'non-actionable'
}

const claim = (value: AcademyStage3ClaimAudit) => value

export const ACADEMY_STAGE_3_CLAIMS: readonly AcademyStage3ClaimAudit[] = [
  claim({ claimId: 'claim.014i.stage3.observation-distinction', lessonId: 'lesson.metrology.observe-before-measuring', sectionId: academyStage3SectionId.focus('lesson.metrology.observe-before-measuring'), claimType: 'principle', generalOrSpecific: 'general', primarySourceId: 'source.metrology.bipm.vim', supportingSourceIds: ['source.metrology.bipm.gum'], locator: 'JCGM 200:2012 (VIM), §2.3; JCGM 100:2008 (GUM)', historicalStatus: 'current', manufacturerApplicability: 'not-applicable', scope: 'Mensurando, medición e incertidumbre; la separación editorial de observación e inferencia se declara como método educativo.', limitations: ['No convierte una observación en diagnóstico.'], verificationStatus: 'source-reviewed', decision: 'clarify' }),
  claim({ claimId: 'claim.014i.stage3.measurement-vocabulary', lessonId: 'lesson.metrology.units-scale-resolution', sectionId: academyStage3SectionId.focus('lesson.metrology.units-scale-resolution'), claimType: 'measurement', generalOrSpecific: 'general', primarySourceId: 'source.metrology.bipm.vim', supportingSourceIds: ['source.metrology.bipm.gum'], locator: 'JCGM 200:2012 (VIM), §§2.13, 2.15, 2.26 y 4.14', historicalStatus: 'current', manufacturerApplicability: 'not-applicable', scope: 'Exactitud, precisión, incertidumbre y resolución como conceptos diferentes.', limitations: ['No especifica un instrumento ni crea tolerancias.'], verificationStatus: 'source-reviewed', decision: 'keep' }),
  claim({ claimId: 'claim.014i.stage3.instrument-selection', lessonId: 'lesson.metrology.instruments', sectionId: academyStage3SectionId.focus('lesson.metrology.instruments'), claimType: 'measurement', generalOrSpecific: 'general', primarySourceId: 'source.metrology.nist.handbook', supportingSourceIds: ['source.metrology.bipm.vim'], locator: 'NIST/SEMATECH e-Handbook of Statistical Methods · Measurement Process Characterization', historicalStatus: 'current', manufacturerApplicability: 'Consultar manual del instrumento usado.', scope: 'Selección condicionada por tarea, rango, método y proceso de medición.', limitations: ['La resolución y calibración concretas se comprueban en el instrumento real.'], verificationStatus: 'source-reviewed', decision: 'narrow' }),
  claim({ claimId: 'claim.014i.stage3.repeated-measurement', lessonId: 'lesson.metrology.physical-measurement', sectionId: academyStage3SectionId.focus('lesson.metrology.physical-measurement'), claimType: 'measurement', generalOrSpecific: 'general', primarySourceId: 'source.metrology.bipm.vim', supportingSourceIds: ['source.metrology.bipm.gum'], locator: 'JCGM 200:2012 (VIM), §§2.20 y 2.26', historicalStatus: 'current', manufacturerApplicability: 'not-applicable', scope: 'Repetibilidad e incertidumbre en una serie declarada.', limitations: ['Una serie digital R no demuestra ejecución física P.'], verificationStatus: 'source-reviewed', decision: 'keep' }),
  claim({ claimId: 'claim.014i.stage3.tm-inspection', lessonId: 'lesson.encyclopedia.service-tribology.tm-inspeccion-previa', sectionId: academyStage3SectionId.focus('lesson.encyclopedia.service-tribology.tm-inspeccion-previa'), claimType: 'historical-context', generalOrSpecific: 'general', primarySourceId: 'source.official.tm9-1575.inspection', supportingSourceIds: [], locator: 'TM 9-1575, sección III, PDF 25–27, impresas 12–14', historicalStatus: 'historical', manufacturerApplicability: 'Equipos y revisión militar declarados en 1945.', scope: 'Orden histórico de inspección antes del desmontaje.', limitations: ['No autoridad moderna de seguridad, tolerancias, química o aceptación.'], verificationStatus: 'historical-only', decision: 'historical-only' }),
  claim({ claimId: 'claim.014i.stage3.rival-hypotheses', lessonId: 'lesson.horology.failure-prediction', sectionId: academyStage3SectionId.focus('lesson.horology.failure-prediction'), claimType: 'diagnosis', generalOrSpecific: 'general', primarySourceId: 'source.horology.original-functional-map', supportingSourceIds: [], locator: 'Blueprint editorial · primer módulo funcional; simulación declarativa 0.1.0', historicalStatus: 'current', manufacturerApplicability: 'not-applicable', scope: 'Razonamiento por subsistemas e hipótesis rivales dentro de un modelo simbólico.', limitations: ['No diagnostica una unidad física.'], verificationStatus: 'source-limited', decision: 'clarify' }),
  claim({ claimId: 'claim.014i.stage3.tm-diagnosis', lessonId: 'lesson.encyclopedia.service-tribology.tm-diagnostico-sintomas', sectionId: academyStage3SectionId.focus('lesson.encyclopedia.service-tribology.tm-diagnostico-sintomas'), claimType: 'historical-context', generalOrSpecific: 'general', primarySourceId: 'source.official.tm9-1575.diagnosis', supportingSourceIds: ['source.private.chicago.35'], locator: 'TM 9-1575, PDF 49–88, impresas 19–44', historicalStatus: 'historical', manufacturerApplicability: 'Contexto militar de 1945.', scope: 'Patrón histórico de síntomas, causas candidatas e inspección por subsistemas.', limitations: ['No se trasladan sustancias, intervalos, tolerancias, ajustes o recetas.'], verificationStatus: 'historical-only', decision: 'non-actionable' }),
  claim({ claimId: 'claim.014i.stage3.hamilton-992b-scope', lessonId: 'lesson.encyclopedia.atlas-restoration-design.tm-hamilton-992b', sectionId: academyStage3SectionId.focus('lesson.encyclopedia.atlas-restoration-design.tm-hamilton-992b'), claimType: 'historical-context', generalOrSpecific: 'calibre-specific', primarySourceId: 'source.official.tm9-1575.hamilton-992b', supportingSourceIds: ['source.external.pocket-watch-database'], locator: 'TM 9-1575, PDF 90–107, impresas 47–48, Figs. 46–71', historicalStatus: 'historical', manufacturerApplicability: 'Hamilton 992B y revisión documentada.', scope: 'Identidad y expediente histórico del calibre.', limitations: ['No se generaliza a otro Hamilton ni a práctica moderna.'], verificationStatus: 'historical-only', decision: 'narrow' }),
  claim({ claimId: 'claim.014i.stage3.cleaning-before-evidence', lessonId: 'lesson.encyclopedia.service-tribology.limpieza-e-inspeccion', sectionId: academyStage3SectionId.focus('lesson.encyclopedia.service-tribology.limpieza-e-inspeccion'), claimType: 'safety', generalOrSpecific: 'general', primarySourceId: 'source.institutional.awci.standards', supportingSourceIds: ['source.external.naked-watchmaker'], locator: 'AWCI Official Standards and Practices for Watchmakers (2011), documento completo enlazado', historicalStatus: 'mixed', manufacturerApplicability: 'El proceso concreto depende de material y documentación vigente.', scope: 'Conservar evidencia y justificar la limpieza antes de ejecutarla.', limitations: ['La fuente institucional no basta para seleccionar química o proceso actual.'], verificationStatus: 'source-needed', decision: 'source-needed' }),
  claim({ claimId: 'claim.014i.stage3.tribology-no-prescription', lessonId: 'lesson.encyclopedia.service-tribology.tribologia-y-lubricantes', sectionId: academyStage3SectionId.focus('lesson.encyclopedia.service-tribology.tribologia-y-lubricantes'), claimType: 'procedure', generalOrSpecific: 'general', primarySourceId: 'source.private.daniels.jewelling', supportingSourceIds: ['source.institutional.awci.standards'], locator: 'Daniels · Watchmaking, capítulo Jewelling; inventario curado, revisión visual pendiente para detalles', historicalStatus: 'mixed', manufacturerApplicability: 'Producto, punto y cantidad requieren documento oficial de calibre y variante.', scope: 'Contacto, fricción, desgaste y contaminación como marco general.', limitations: ['No prescribe lubricante, punto o cantidad.'], verificationStatus: 'source-limited', decision: 'narrow' }),
  claim({ claimId: 'claim.014i.stage3.assembly-controls', lessonId: 'lesson.encyclopedia.service-tribology.montaje-y-puntos-de-control', sectionId: academyStage3SectionId.focus('lesson.encyclopedia.service-tribology.montaje-y-puntos-de-control'), claimType: 'procedure', generalOrSpecific: 'general', primarySourceId: 'source.institutional.awci.standards', supportingSourceIds: [], locator: 'AWCI Official Standards and Practices for Watchmakers (2011), documento completo enlazado', historicalStatus: 'current', manufacturerApplicability: 'Secuencia y criterio dependen del fabricante.', scope: 'Controles intermedios y criterio de parada como patrón educativo.', limitations: ['No es secuencia universal ni montaje del 8215.'], verificationStatus: 'source-limited', decision: 'clarify' }),
]

export const ACADEMY_STAGE_3_FORMULA_REVIEWS: readonly [] = []
