import type { AcademyStage3EditorialArchetype } from '../types'

export interface AcademyStage3EditorialContract {
  whyNow: string
  editorialArchetype: AcademyStage3EditorialArchetype
  checkpointPrompt: string
  checkpointExpectedElements: readonly string[]
}

const c = (value: AcademyStage3EditorialContract) => value

export const ACADEMY_STAGE_3_EDITORIAL_CONTRACTS: Readonly<Record<string, AcademyStage3EditorialContract>> = {
  'lesson.metrology.observe-before-measuring': c({ whyNow: 'La etapa comienza conservando evidencia antes de elegir instrumento o intervención.', editorialArchetype: 'observation-inspection', checkpointPrompt: 'Describe un rasgo sin convertirlo en causa.', checkpointExpectedElements: ['condición observable', 'medio y contexto', 'inferencia separada', 'dato ausente'] }),
  'lesson.metrology.inspection-findings': c({ whyNow: 'Después de separar observación e inferencia, hace falta convertirlas en un hallazgo trazable.', editorialArchetype: 'observation-inspection', checkpointPrompt: 'Construye un hallazgo que otra persona pueda volver a inspeccionar.', checkpointExpectedElements: ['objeto y zona', 'evidencia', 'hipótesis rivales', 'confianza y siguiente comprobación'] }),
  'lesson.encyclopedia.service-tribology.recepcion-y-linea-base': c({ whyNow: 'La recepción fija el estado que podría desaparecer al probar o abrir.', editorialArchetype: 'observation-inspection', checkpointPrompt: 'Decide qué registrar y cuándo detener una prueba inicial.', checkpointExpectedElements: ['historia disponible', 'estado externo', 'desconocidos', 'decisión antes de abrir'] }),
  'lesson.encyclopedia.service-tribology.tm-inspeccion-previa': c({ whyNow: 'El caso histórico muestra la disciplina de inspeccionar primero sin convertir criterios de 1945 en norma vigente.', editorialArchetype: 'historical-case', checkpointPrompt: 'Separa el principio todavía útil del dato histórico no transferible.', checkpointExpectedElements: ['orden de observación', 'contexto histórico', 'límite de autoridad', 'fuente actual pendiente'] }),
  'lesson.metrology.units-scale-resolution': c({ whyNow: 'Una observación cuantitativa necesita magnitud, unidad y resolución declaradas antes de comparar.', editorialArchetype: 'measurement', checkpointPrompt: 'Explica qué permite y qué no permite afirmar la resolución.', checkpointExpectedElements: ['magnitud', 'unidad', 'incremento legible', 'exactitud no inferida'] }),
  'lesson.metrology.instruments': c({ whyNow: 'El instrumento se elige por la tarea y el riesgo, no por el número de dígitos.', editorialArchetype: 'measurement', checkpointPrompt: 'Justifica una elección de instrumento para una magnitud concreta.', checkpointExpectedElements: ['rango y acceso', 'resolución necesaria', 'alineación o fuerza', 'riesgo y referencia'] }),
  'lesson.metrology.physical-measurement': c({ whyNow: 'La lectura solo resulta defendible cuando conserva método, repetición y duda.', editorialArchetype: 'measurement', checkpointPrompt: 'Redacta un resultado sin fabricar precisión.', checkpointExpectedElements: ['unidad', 'datum o referencia', 'serie de lecturas', 'incertidumbre y límite'] }),
  'lesson.metrology.precision-accuracy-uncertainty': c({ whyNow: 'Este apoyo impide confundir agrupación de resultados, proximidad a una referencia y duda asociada.', editorialArchetype: 'measurement', checkpointPrompt: 'Compara precisión, exactitud e incertidumbre sin usarlas como sinónimos.', checkpointExpectedElements: ['repetición', 'referencia', 'dispersión', 'duda declarada'] }),
  'lesson.metrology.compare-data': c({ whyNow: 'Dos números solo se comparan después de comprobar magnitud, unidad, datum, método y condición.', editorialArchetype: 'data-comparison', checkpointPrompt: 'Decide si dos registros son comparables y por qué.', checkpointExpectedElements: ['misma magnitud y unidad', 'datum y método', 'condición', 'redondeo e incertidumbre'] }),
  'lesson.horology.failure-prediction': c({ whyNow: 'Las cadenas funcionales permiten formular hipótesis rivales sin diagnosticar una unidad física.', editorialArchetype: 'diagnosis', checkpointPrompt: 'Elige una prueba que produzca resultados distintos para dos hipótesis.', checkpointExpectedElements: ['síntoma', 'dos hipótesis', 'predicción por hipótesis', 'actualización según resultado'] }),
  'lesson.encyclopedia.service-tribology.diagnostico-y-control-final': c({ whyNow: 'Diagnóstico y aceptación responden preguntas distintas y necesitan evidencia distinta.', editorialArchetype: 'diagnosis', checkpointPrompt: 'Separa la prueba de causa del control de resultado.', checkpointExpectedElements: ['causa provisional', 'prueba discriminante', 'criterio con autoridad', 'incertidumbre residual'] }),
  'lesson.encyclopedia.service-tribology.tm-diagnostico-sintomas': c({ whyNow: 'El manual histórico aporta una estructura de síntomas y subsistemas, no recetas ni tolerancias actuales.', editorialArchetype: 'historical-case', checkpointPrompt: 'Extrae el patrón diagnóstico sin importar el procedimiento de época.', checkpointExpectedElements: ['síntoma', 'subsistemas candidatos', 'prueba', 'límite histórico'] }),
  'lesson.encyclopedia.atlas-restoration-design.tm-hamilton-992b': c({ whyNow: 'El 992B sirve como expediente histórico opcional y no como requisito de marcos modernos de diseño.', editorialArchetype: 'historical-case', checkpointPrompt: 'Limita una conclusión al calibre y revisión documentados.', checkpointExpectedElements: ['identidad', 'revisión', 'dato transferible', 'dato no transferible'] }),
  'lesson.encyclopedia.service-tribology.limpieza-e-inspeccion': c({ whyNow: 'La limpieza se decide después de documentar la evidencia que podría borrar.', editorialArchetype: 'reasoned-service', checkpointPrompt: 'Justifica si limpiar aporta más información de la que destruye.', checkpointExpectedElements: ['estado previo', 'objetivo', 'material y fuente', 'control y parada'] }),
  'lesson.encyclopedia.service-tribology.tribologia-y-lubricantes': c({ whyNow: 'La tribología explica contactos y pérdidas sin prescribir un producto de calibre.', editorialArchetype: 'reasoned-service', checkpointPrompt: 'Explica qué datos faltan antes de decidir una lubricación concreta.', checkpointExpectedElements: ['contacto y movimiento', 'carga o función', 'documento aplicable', 'producto, punto y cantidad pendientes'] }),
  'lesson.encyclopedia.service-tribology.montaje-y-puntos-de-control': c({ whyNow: 'Los controles intermedios localizan el primer estado que deja de ser defendible.', editorialArchetype: 'reasoned-service', checkpointPrompt: 'Sitúa controles y criterios de parada entre acciones.', checkpointExpectedElements: ['estado previo', 'asiento y libertad', 'interacción', 'autoridad de aceptación'] }),
  'lesson.advanced.service-clean-lube': c({ whyNow: 'La rama avanzada organiza decisiones documentales sin convertirse en secuencia universal.', editorialArchetype: 'reasoned-service', checkpointPrompt: 'Audita una decisión de servicio sin elegir producto por intuición.', checkpointExpectedElements: ['necesidad', 'fuente aplicable', 'riesgo', 'dato bloqueado'] }),
}

export function academyStage3EditorialContract(lessonId: string): AcademyStage3EditorialContract {
  const result = ACADEMY_STAGE_3_EDITORIAL_CONTRACTS[lessonId]
  if (!result) throw new Error(`Falta el contrato editorial de etapa 3 para ${lessonId}.`)
  return result
}
