import { academyReaderStableHash } from '../../academyReaderIdentity'
import type { AcademySourceLocator, AcademyStage1VisualDesign } from '../types'

const toh = (chapter: 'ch03' | 'ch06' | 'ch15', page: string, figure?: string): AcademySourceLocator => ({
  sourceId: `source.private.toh.${chapter}`,
  documentLocator: `reference-library/originals/Theory of Horology-20260809T132232Z-1-001.zip#${chapter === 'ch03' ? 'ToH ch 1-3.pdf' : chapter === 'ch06' ? 'ToH ch 6.pdf' : 'TOH chap. 15.pdf'}`,
  page,
  ...(figure ? { figure } : {}),
  verificationMethod: 'visual-pdf-inspection',
  verifiedAt: '2026-08-15',
})

type VisualInput = Omit<AcademyStage1VisualDesign, 'contentHash' | 'visualHash'>
const visual = (input: VisualInput): AcademyStage1VisualDesign => ({
  ...input,
  contentHash: academyReaderStableHash([input.pedagogicalQuestion, input.longDescription, ...input.limitations].join('\n')),
  visualHash: academyReaderStableHash(JSON.stringify(input.semanticPayload)),
})

export const ACADEMY_STAGE_1_VISUAL_DESIGNS: readonly AcademyStage1VisualDesign[] = [
  visual({
    visualDesignId: 'visual.stage1.watch-system.v1',
    lessonIds: ['lesson.horology.system'],
    sectionIds: ['reader.section.block.horology.system.014g-capas'],
    pedagogicalQuestion: '¿Qué aporta cada capa al reloj completo?',
    semanticPayload: {
      title: 'Capas y funciones del reloj completo',
      nodes: [
        { id: 'watch', label: 'Reloj completo', detail: 'Sistema que puede protegerse, ajustarse y leerse', lane: 'reloj', emphasis: 'primary' },
        { id: 'case', label: 'Protección', detail: 'Sostiene y separa el interior del entorno', lane: 'reloj' },
        { id: 'display', label: 'Indicación', detail: 'Convierte estados en lectura', lane: 'reloj' },
        { id: 'interface', label: 'Interfaz', detail: 'Permite ajustar o accionar', lane: 'reloj' },
        { id: 'energy', label: 'Energía', detail: 'Fuente o acumulador dentro del movimiento', lane: 'movimiento' },
        { id: 'regulation', label: 'Regulación o control', detail: 'Mantiene referencia y controla la entrega', lane: 'movimiento' },
        { id: 'transmission', label: 'Transmisión', detail: 'Entrega un estado a la indicación', lane: 'movimiento' },
        { id: 'movement', label: 'Movimiento', detail: 'Conjunto funcional interior', lane: 'movimiento', emphasis: 'primary' },
      ],
      edges: [
        { from: 'case', to: 'watch', label: 'protege', kind: 'mechanical' },
        { from: 'movement', to: 'watch', label: 'forma parte', kind: 'timing' },
        { from: 'display', to: 'watch', label: 'hace legible', kind: 'comparison' },
        { from: 'interface', to: 'movement', label: 'ajusta', kind: 'decision' },
        { from: 'energy', to: 'regulation', label: 'entrega', kind: 'energy' },
        { from: 'regulation', to: 'transmission', label: 'dosifica', kind: 'timing' },
        { from: 'transmission', to: 'display', label: 'indica', kind: 'mechanical' },
        { from: 'transmission', to: 'movement', label: 'integra', kind: 'mechanical' },
      ],
      annotations: ['Una función puede estar distribuida y una pieza puede participar en varias funciones.'],
    },
    sourceIds: ['source.private.toh.ch03', 'source.horology.original-functional-map'],
    sourceLocators: [toh('ch03', 'PDF 33 / impresa 33'), toh('ch03', 'PDF 38 / impresa 38')],
    fidelity: 'conceptual', limitations: ['No representa escala, ensamblaje ni calibre.'],
    accessibilitySummary: 'Dos carriles distinguen reloj completo, protección, indicación e interfaz de energía, regulación, transmisión y movimiento.',
    longDescription: 'El reloj completo reúne protección, indicación, interfaz y movimiento. Dentro del movimiento, energía, regulación o control y transmisión forman una secuencia funcional que termina en la indicación.',
    implementationStatus: 'implemented', colorIndependent: true, reducedMotionSafe: true,
  }),
  visual({
    visualDesignId: 'visual.stage1.mechanical-feedback.v1',
    lessonIds: ['lesson.encyclopedia.mechanical-energy-trains.toh-movimiento-simple', 'lesson.horology.mechanical-chain'],
    sectionIds: [
      'reader.section.block.encyclopedia.mechanical-energy-trains.toh-movimiento-simple.014g-organos',
      'reader.section.block.horology.mechanical-chain.014g-mapa',
    ],
    pedagogicalQuestion: '¿Dónde termina la ruta de energía y dónde aparece el retorno de temporización?',
    semanticPayload: {
      title: 'Ruta energética, bucle temporal y rama de indicación',
      nodes: [
        { id: 'source', label: 'Fuente y barrilete', detail: 'Energía almacenada', lane: 'energía' },
        { id: 'train', label: 'Tren', detail: 'Transmite movimiento', lane: 'energía' },
        { id: 'escapement', label: 'Escape', detail: 'Bloqueo, liberación e impulso', lane: 'temporización', emphasis: 'primary' },
        { id: 'oscillator', label: 'Volante y espiral', detail: 'Referencia oscilante', lane: 'temporización', emphasis: 'primary' },
        { id: 'display', label: 'Indicación', detail: 'Salida legible', lane: 'indicación' },
      ],
      edges: [
        { from: 'source', to: 'train', label: 'energía', kind: 'energy' },
        { from: 'train', to: 'escapement', label: 'tendencia al avance', kind: 'energy' },
        { from: 'escapement', to: 'oscillator', label: 'impulso', kind: 'energy' },
        { from: 'oscillator', to: 'escapement', label: 'momento de liberación', kind: 'timing' },
        { from: 'train', to: 'display', kind: 'mechanical' },
      ],
      annotations: ['No es una simulación de fuerzas ni un diagrama de servicio.'],
    },
    sourceIds: ['source.private.toh.ch03', 'source.private.toh.ch06'],
    sourceLocators: [toh('ch03', 'PDF 38–39 / impresas 38–39'), toh('ch06', 'PDF 1 / impresa 99', 'Fig. 6-1')],
    fidelity: 'conceptual', limitations: ['No muestra relaciones de engranaje, amplitud, fuerza, fricción o lubricación.'],
    accessibilitySummary: 'Tres carriles distinguen energía, temporización e indicación; dos flechas opuestas forman el bucle escape–oscilador.',
    longDescription: 'La energía va de fuente a tren y escape. El escape impulsa al oscilador y el oscilador devuelve la condición temporal al escape. Desde el tren sale una rama separada hacia la indicación.',
    implementationStatus: 'implemented', colorIndependent: true, reducedMotionSafe: true,
  }),
  visual({
    visualDesignId: 'visual.stage1.quartz-functional.v1',
    lessonIds: ['lesson.horology.quartz-chain'],
    sectionIds: ['reader.section.block.horology.quartz-chain.014g-mapa'],
    pedagogicalQuestion: '¿Cómo se convierte una referencia eléctrica en movimiento visible?',
    semanticPayload: {
      title: 'Cadena funcional del cuarzo analógico',
      nodes: [
        { id: 'battery', label: 'Batería', detail: 'Energía eléctrica', lane: 'energía' },
        { id: 'quartz', label: 'Cuarzo', detail: 'Referencia periódica', lane: 'tiempo' },
        { id: 'circuit', label: 'Circuito', detail: 'Mantiene y divide la referencia', lane: 'tiempo' },
        { id: 'motor', label: 'Bobina, estator y rotor', detail: 'Conversión electromecánica', lane: 'movimiento', emphasis: 'primary' },
        { id: 'train', label: 'Tren reductor', detail: 'Transmisión', lane: 'movimiento' },
        { id: 'display', label: 'Agujas', detail: 'Indicación', lane: 'movimiento' },
      ],
      edges: [
        { from: 'battery', to: 'circuit', label: 'alimenta', kind: 'energy' },
        { from: 'quartz', to: 'circuit', label: 'referencia', kind: 'timing' },
        { from: 'circuit', to: 'motor', label: 'orden temporizada', kind: 'timing' },
        { from: 'motor', to: 'train', label: 'paso mecánico', kind: 'mechanical' },
        { from: 'train', to: 'display', label: 'movimiento reducido', kind: 'mechanical' },
      ],
    },
    sourceIds: ['source.private.toh.ch15', 'source.miyota.2035.parts-list-exploded-view'],
    sourceLocators: [
      toh('ch15', 'PDF 3 / impresa 331', 'Fig. 15-6'), toh('ch15', 'PDF 11 / impresa 339', 'Fig. 15-22'),
      toh('ch15', 'PDF 13 / impresa 341', 'Fig. 15-28'), toh('ch15', 'PDF 14 / impresa 342', 'Figs. 15-29–30'),
      { sourceId: 'source.miyota.2035.parts-list-exploded-view', documentLocator: 'Registro canónico: documentación oficial MIYOTA 2035', section: 'parts list / exploded view', verificationMethod: 'official-document' },
    ],
    fidelity: 'conceptual', limitations: ['No muestra frecuencia, consumo, tolerancia ni disposición universal.'],
    accessibilitySummary: 'Cinco conexiones etiquetadas separan energía, referencia, conversión y transmisión hasta las agujas.',
    longDescription: 'La batería alimenta al circuito y el cuarzo aporta la referencia. El circuito gobierna el motor; el rotor mueve el tren y el tren las agujas. Cada transición declara su función.',
    implementationStatus: 'implemented', colorIndependent: true, reducedMotionSafe: true,
  }),
  visual({
    visualDesignId: 'visual.stage1.functional-equivalence.v1',
    lessonIds: ['lesson.horology.functional-equivalence'],
    sectionIds: ['reader.section.block.horology.functional-equivalence.014g-matriz'],
    pedagogicalQuestion: '¿Qué se puede comparar y qué límite impide afirmar igualdad física?',
    semanticPayload: {
      title: 'Matriz de equivalencias funcionales',
      nodes: [
        { id: 'energy-function', label: 'Energía', detail: 'Función comparada', lane: 'energía', emphasis: 'primary' },
        { id: 'energy-solutions', label: 'Muelle ↔ batería', detail: 'Soluciones físicas distintas', lane: 'energía' },
        { id: 'energy-grade', label: 'Analogía parcial', detail: 'Comparten el papel de fuente', lane: 'energía' },
        { id: 'energy-limit', label: 'No: mismo fenómeno', detail: 'No implica igualdad física', lane: 'energía', emphasis: 'warning' },
        { id: 'reference-function', label: 'Referencia temporal', detail: 'Función comparada', lane: 'referencia', emphasis: 'primary' },
        { id: 'reference-solutions', label: 'Volante ↔ cuarzo', detail: 'La función está distribuida', lane: 'referencia' },
        { id: 'reference-grade', label: 'Función distribuida', detail: 'No existe pareja pieza a pieza', lane: 'referencia' },
        { id: 'reference-limit', label: 'No: pieza por pieza', detail: 'La comparación se mantiene en el nivel funcional', lane: 'referencia', emphasis: 'warning' },
        { id: 'control-function', label: 'Control e impulso', detail: 'Funciones combinadas de modo diferente', lane: 'control', emphasis: 'primary' },
        { id: 'control-solutions', label: 'Escape / circuito-motor', detail: 'Conjuntos de arquitectura distinta', lane: 'control' },
        { id: 'control-grade', label: 'Sin equivalente directo', detail: 'Negarse a emparejar es una respuesta válida', lane: 'control' },
        { id: 'control-limit', label: 'No: escape = motor', detail: 'No implica sustitución ni compatibilidad', lane: 'control', emphasis: 'warning' },
      ],
      edges: [
        { from: 'energy-function', to: 'energy-solutions', kind: 'comparison' },
        { from: 'energy-solutions', to: 'energy-grade', kind: 'comparison' },
        { from: 'energy-grade', to: 'energy-limit', kind: 'comparison' },
        { from: 'reference-function', to: 'reference-solutions', kind: 'comparison' },
        { from: 'reference-solutions', to: 'reference-grade', kind: 'comparison' },
        { from: 'reference-grade', to: 'reference-limit', kind: 'comparison' },
        { from: 'control-function', to: 'control-solutions', kind: 'comparison' },
        { from: 'control-solutions', to: 'control-grade', kind: 'comparison' },
        { from: 'control-grade', to: 'control-limit', kind: 'comparison' },
      ],
    },
    sourceIds: ['source.private.toh.ch03', 'source.private.toh.ch15', 'source.horology.original-functional-map'],
    sourceLocators: [toh('ch03', 'PDF 38 / impresa 38'), toh('ch15', 'PDF 3 / impresa 331', 'Fig. 15-6')],
    fidelity: 'conceptual', limitations: ['Síntesis editorial; ninguna fila prueba compatibilidad o equivalencia física.'],
    accessibilitySummary: 'Tres filas comparan función, soluciones de ambas arquitecturas, grado de analogía y límite.',
    longDescription: 'La energía admite una analogía parcial entre muelle y batería. La referencia temporal está distribuida de forma diferente. Control e impulso no ofrecen una equivalencia directa entre escape y circuito-motor. Cada fila termina con un límite explícito contra la igualdad física.',
    implementationStatus: 'implemented', colorIndependent: true, reducedMotionSafe: true,
  }),
  visual({
    visualDesignId: 'visual.stage1.document-authority.v1',
    lessonIds: ['lesson.encyclopedia.history-language.leer-documentacion'],
    sectionIds: ['reader.section.block.encyclopedia.history-language.leer-documentacion.014g-tipos'],
    pedagogicalQuestion: '¿Qué puede y qué no puede demostrar cada documento?',
    semanticPayload: {
      title: 'Qué puede demostrar cada documento',
      nodes: [
        { id: 'official', label: 'Ficha oficial', detail: 'Documento aplicable al producto', lane: 'ficha', emphasis: 'primary' },
        { id: 'official-allows', label: 'Sí: dato declarado', detail: 'Especificación dentro de alcance', lane: 'ficha' },
        { id: 'official-denies', label: 'No: dato ausente', detail: 'No completa lo que el documento no trata', lane: 'ficha', emphasis: 'warning' },
        { id: 'parts', label: 'Despiece', detail: 'Piezas y relaciones representadas', lane: 'despiece', emphasis: 'primary' },
        { id: 'parts-allows', label: 'Sí: identidad o relación', detail: 'Lo que el dibujo representa', lane: 'despiece' },
        { id: 'parts-denies', label: 'No: orden de servicio', detail: 'No demuestra una secuencia', lane: 'despiece', emphasis: 'warning' },
        { id: 'database', label: 'Base secundaria', detail: 'Descubrimiento y contraste', lane: 'base', emphasis: 'primary' },
        { id: 'database-allows', label: 'Sí: pista de búsqueda', detail: 'Identificación preliminar', lane: 'base' },
        { id: 'database-denies', label: 'No: criterio de servicio', detail: 'Requiere fuente aplicable', lane: 'base', emphasis: 'warning' },
      ],
      edges: [
        { from: 'official', to: 'official-allows', kind: 'decision' },
        { from: 'official-allows', to: 'official-denies', kind: 'decision' },
        { from: 'parts', to: 'parts-allows', kind: 'decision' },
        { from: 'parts-allows', to: 'parts-denies', kind: 'decision' },
        { from: 'database', to: 'database-allows', kind: 'decision' },
        { from: 'database-allows', to: 'database-denies', kind: 'decision' },
      ],
    },
    sourceIds: ['source.official.miyota.2035', 'source.official.miyota.8215', 'source.eta.6497-2.communication'],
    sourceLocators: [
      { sourceId: 'source.official.miyota.2035', documentLocator: 'Registro canónico: recurso oficial MIYOTA 2035', verificationMethod: 'official-document' },
      { sourceId: 'source.official.miyota.8215', documentLocator: 'Registro canónico: recurso oficial MIYOTA 8215', verificationMethod: 'official-document' },
      { sourceId: 'source.eta.6497-2.communication', documentLocator: 'Registro canónico: comunicación técnica ETA 6497-2', verificationMethod: 'official-document' },
    ],
    fidelity: 'conceptual', limitations: ['No muestra el contenido de documentos ni decide autoridad sin una pregunta y aplicabilidad.'],
    accessibilitySummary: 'Tres filas distinguen documento, afirmación permitida y afirmación no demostrada para ficha oficial, despiece y base secundaria.',
    longDescription: 'Una ficha oficial permite usar datos que declara, pero no completa datos ausentes. Un despiece permite identificar piezas y relaciones representadas, pero no demuestra orden de servicio. Una base secundaria aporta pistas de búsqueda, no un criterio final de servicio.',
    implementationStatus: 'implemented', colorIndependent: true, reducedMotionSafe: true,
  }),
  visual({
    visualDesignId: 'visual.stage1.claim-trace.v1',
    lessonIds: ['lesson.advanced.atlas-authority'],
    sectionIds: ['reader.section.block.advanced.atlas-authority.014g-ruta'],
    pedagogicalQuestion: '¿Qué pasos hacen revisable una afirmación técnica?',
    semanticPayload: {
      title: 'Trazabilidad de una afirmación',
      nodes: [
        { id: 'claim', label: 'Afirmación', detail: 'Una proposición técnica revisable', lane: 'traza', emphasis: 'primary' },
        { id: 'source', label: 'Fuente', detail: 'Autoridad aplicable a la materia', lane: 'traza' },
        { id: 'locator', label: 'Localizador', detail: 'Página, figura, tabla o sección', lane: 'traza' },
        { id: 'limitation', label: 'Limitación', detail: 'Lo que no puede concluirse', lane: 'revisión', emphasis: 'warning' },
        { id: 'scope', label: 'Alcance', detail: 'Producto, variante, edición y materia', lane: 'revisión' },
        { id: 'review', label: 'Revisión aplicable', detail: 'Verificación visual o documental pertinente', lane: 'revisión' },
      ],
      edges: [
        { from: 'claim', to: 'source', kind: 'decision' },
        { from: 'source', to: 'locator', kind: 'decision' },
        { from: 'locator', to: 'review', kind: 'decision' },
        { from: 'review', to: 'scope', kind: 'decision' },
        { from: 'scope', to: 'limitation', kind: 'decision' },
      ],
    },
    sourceIds: ['source.official.miyota.2035', 'source.official.miyota.8215', 'source.eta.6497-2.communication'],
    sourceLocators: [
      { sourceId: 'source.official.miyota.2035', documentLocator: 'Registro canónico: recurso oficial MIYOTA 2035', verificationMethod: 'official-document' },
      { sourceId: 'source.official.miyota.8215', documentLocator: 'Registro canónico: recurso oficial MIYOTA 8215', verificationMethod: 'official-document' },
      { sourceId: 'source.eta.6497-2.communication', documentLocator: 'Registro canónico: comunicación técnica ETA 6497-2', verificationMethod: 'official-document' },
    ],
    fidelity: 'conceptual', limitations: ['No verifica por sí solo la exactitud de ninguna afirmación ni muestra documentos privados.'],
    accessibilitySummary: 'Seis pasos enlazan afirmación, fuente, localizador, revisión aplicable, alcance y limitación.',
    longDescription: 'Una afirmación conduce a una fuente aplicable y a un localizador concreto. La revisión comprueba la aplicabilidad, delimita el alcance y termina declarando qué no puede concluirse.',
    implementationStatus: 'implemented', colorIndependent: true, reducedMotionSafe: true,
  }),
] as const

const visualBySectionId = new Map(ACADEMY_STAGE_1_VISUAL_DESIGNS.flatMap((design) => design.sectionIds.map((sectionId) => [sectionId, design] as const)))

export function academyStage1VisualForSection(sectionId: string): AcademyStage1VisualDesign | undefined {
  return visualBySectionId.get(sectionId)
}
